Embedded Library: ErrorCodeParser Class Reference
ErrorCodeParser Class Reference
#include <ErrorCodeParser.hpp>
Static Public Member Functions
static general_err_t postToMqtt (const db_id &id, const general_err_t &err, const std::string &description="")
postToMqtt sends a signle error code to the database with the given ID
Static Private Member Functions
const static std::string toString (const db_id &id, const general_err_t &err, const std::string &description)
Detailed Description
Definition at line 49 of file ErrorCodeParser.hpp.
Member Function Documentation
postToMqtt()
general_err_t ErrorCodeParser::postToMqtt (const db_id & id, const general_err_t & err, const std::string & description = "") static
postToMqtt sends a signle error code to the database with the given ID
Parameters
id
err
Returns
general_err_t
Definition at line 29 of file ErrorCodeParser.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> ErrorCodeParser::postToMqtt >> ");
 #endif
     // Executable code:
     mqtt_api_v2 mqtt;
 #ifdef DEBUG
     std::cout << "writing to topic <mqtt/error_codes> with ID <" << std::to_string(map.at(id))
               << "> error code <"
               << std::to_string(static_cast<uint8_t>(err) + 10 /* offset zero values for grafana */)
               << "and description <" << description << "> \n";
     LOG_PRINT_INFO(LOG_TAG, "<<  ErrorCodeParser::postToMqtt << ");
 #endif
     return mqtt.publish("mqtt/error_codes", toString(id, err, description));
 }
References LOG_PRINT_INFO, LOG_TAG, map, mqtt_api_v2::publish(), and toString().
Referenced by Maintainer::check_system_functions(), Maintainer::periodic_restart(), SensorControllerBase::postError(), and ServiceBase< MQTT_Message >::postError().
toString()
const static std::string ErrorCodeParser::toString (const db_id & id, const general_err_t & err, const std::string & description) inline static private
Definition at line 66 of file ErrorCodeParser.hpp.
     {
         return std::to_string(map.at(id)) + "," + std::to_string(Timeservice::getTimeNow()) + "," +
                std::to_string(static_cast<uint8_t>(err) + 10 /* offset zero values for grafana */) +
                "," + description;
     };
References Timeservice::getTimeNow(), and map.
Referenced by postToMqtt().
The documentation for this class was generated from the following files:
Components/Objects/ErrorHandler/include/ErrorCodeParser.hpp
Components/Objects/ErrorHandler/src/ErrorCodeParser.cpp