Embedded Library: MQTT_Message Class Reference
MQTT_Message Class Reference
#include <MQTT_Message.hpp>
Classes
struct msg_conf_t
Public Member Functions
MQTT_Message (const uint64_t &entity_id, const size_t &buffer_size=1)
MQTT_Message (const msg_conf_t &conf)
~MQTT_Message ()
general_err_t addData (const uint64_t &data)
general_err_t addData (const uint64_t &time, const uint64_t &data)
general_err_t addData_f (const float &data)
bool isEmpty (void) const
const std::string toString (void) const
general_err_t clear (void)
auto getBufferSize (void) const
general_err_t append (const MQTT_Message &msg)
const auto & getData (void) const
auto getMaxAllowedBufferSize () const
auto getEntityId () const
general_err_t copyTo (MQTT_Message &message) const
Static Public Member Functions
static MQTT_Message construct (const std::string &str)
Private Attributes
const uint64_t m_entity_id
const size_t m_buffer_size
std::vector< std::pair< uint64_t, uint64_t > > m_data
std::string m_semaphore
Detailed Description
Definition at line 84 of file MQTT_Message.hpp.
Class Documentation
MQTT_Message::msg_conf_t
struct MQTT_Message::msg_conf_t
Definition at line 90 of file MQTT_Message.hpp.
Class Members
size_t buffer_size
db_id entity_id
Constructor & Destructor Documentation
MQTT_Message() [1/2]
MQTT_Message::MQTT_Message (const uint64_t & entity_id, const size_t & buffer_size = 1) explicit
Definition at line 39 of file MQTT_Message.cpp.
     : m_entity_id{entity_id}, m_buffer_size{buffer_size}, m_semaphore{"mqtt message"}
 {
 #ifdef __ESP32__
     m_semaphore.give();
 #endif
 }
MQTT_Message() [2/2]
MQTT_Message::MQTT_Message (const msg_conf_t & conf) explicit
Definition at line 47 of file MQTT_Message.cpp.
     : m_entity_id{map.at(conf.entity_id)}, m_buffer_size{conf.buffer_size}, m_semaphore{
                                                                                 "mqtt message"}
 {
 #ifdef __ESP32__
     m_semaphore.give();
 #endif
 }
References conf, and map.
~MQTT_Message()
MQTT_Message::~MQTT_Message ()
Definition at line 56 of file MQTT_Message.cpp.
 {}
Member Function Documentation
addData() [1/2]
general_err_t MQTT_Message::addData (const uint64_t & data)
Definition at line 58 of file MQTT_Message.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MQTT_Message::addData >> ");
 #endif
     // Executable code:
     if(m_buffer_size <= m_data.size())
     {
         return GE_OUT_OF_RANGE;
     }
 #ifdef __ESP32__
     if(!m_semaphore.take(5000, "addData"))
     {
         return GE_SEMAPHORE_NOT_TAKEN;
     }
 #endif
     m_data.push_back({Timeservice::getTimeNow(), data});
 #ifdef __ESP32__
     m_semaphore.give();
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MQTT_Message::addData << ");
 #endif
     return GE_OK;
 }
References GE_OK, GE_OUT_OF_RANGE, GE_SEMAPHORE_NOT_TAKEN, Timeservice::getTimeNow(), LOG_PRINT_INFO, LOG_TAG, m_buffer_size, m_data, and m_semaphore.
Referenced by append(), copyTo(), DistanceSensorController::main_function(), ActiveCurrentSensor::main_function(), WaterEstimator_Service::mainFunction(), and OnlineDetector_service::mainFunction().
addData() [2/2]
general_err_t MQTT_Message::addData (const uint64_t & time, const uint64_t & data)
Definition at line 85 of file MQTT_Message.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MQTT_Message::addData >> ");
 #endif
     // Executable code:
     if(m_buffer_size <= m_data.size())
     {
         return GE_OUT_OF_RANGE;
     }
 #ifdef __ESP32__
     if(!m_semaphore.take(5000, "addData"))
     {
         return GE_SEMAPHORE_NOT_TAKEN;
     }
 #endif
     m_data.push_back({time, data});
 #ifdef __ESP32__
     m_semaphore.give();
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MQTT_Message::addData << ");
 #endif
     return GE_OK;
 }
References GE_OK, GE_OUT_OF_RANGE, GE_SEMAPHORE_NOT_TAKEN, LOG_PRINT_INFO, LOG_TAG, m_buffer_size, m_data, and m_semaphore.
addData_f()
general_err_t MQTT_Message::addData_f (const float & data)
Definition at line 113 of file MQTT_Message.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> enclosing_method >> ");
 #endif
     // Executable code:
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< enclosing_method << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
append()
general_err_t MQTT_Message::append (const MQTT_Message & msg)
Definition at line 209 of file MQTT_Message.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MQTT_Message::append >> ");
 #endif
     // Executable code:
     if(msg.isEmpty())
     {
         return GE_EMPTY;
     }
     for(const auto& ele : msg.getData())
     {
         // for each element in input message, call addData(...) to append internal buffer
         this->addData(ele.first, ele.second);
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MQTT_Message::append << ");
 #endif
     return GE_OK;
 }
References addData(), GE_EMPTY, GE_OK, getData(), isEmpty(), LOG_PRINT_INFO, and LOG_TAG.
clear()
general_err_t MQTT_Message::clear (void)
Definition at line 161 of file MQTT_Message.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MQTT_Message::clear >> ");
 #endif
 #ifdef __ESP32__
     // Executable code:
     if(!m_semaphore.take(5000, "toString"))
     {
         return GE_SEMAPHORE_NOT_TAKEN;
     }
 #endif
     m_data.clear();
 #ifdef __ESP32__
     m_semaphore.give();
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MQTT_Message::clear << ");
 #endif
     return GE_OK;
 }
References GE_OK, GE_SEMAPHORE_NOT_TAKEN, LOG_PRINT_INFO, LOG_TAG, m_data, and m_semaphore.
Referenced by copyTo(), DistanceSensorController::main_function(), ActiveCurrentSensor::main_function(), WaterEstimator_Service::mainFunction(), and OnlineDetector_service::mainFunction().
construct()
MQTT_Message MQTT_Message::construct (const std::string & str) static
Definition at line 184 of file MQTT_Message.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MQTT_Message::construct >> ");
 #endif
     // Executable code:
     auto vec = basic_utils::split(str, ",");
     if(vec.empty() or vec.size() < CONSTRUCT_MIN_SIZE or
        ((vec.size() - CONSTRUCT_PARAMETER_OFFSET) % CONSTRUCT_EXPECTED_MOD))
     {
         std::cout << "fault in construction of MQTT message! \n";
         Logger::write({GE_FAIL, GR_NO_RESPONSE, "fault in construction of MQTT message!"});
     }
     MQTT_Message msg{0, 0};
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MQTT_Message::construct << ");
 #endif
     return msg;
 }
References CONSTRUCT_EXPECTED_MOD, CONSTRUCT_MIN_SIZE, CONSTRUCT_PARAMETER_OFFSET, GE_FAIL, GR_NO_RESPONSE, LOG_PRINT_INFO, LOG_TAG, basic_utils::split(), vec, and Logger::write().
Referenced by IGNORE_TEST().
copyTo()
general_err_t MQTT_Message::copyTo (MQTT_Message & message) const
Definition at line 232 of file MQTT_Message.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MQTT_Message::fcn >> ");
 #endif
     if(this->getMaxAllowedBufferSize() != message.getMaxAllowedBufferSize())
     {
         return GE_OVERFLOW;
     }
     if(this->getEntityId() != message.getEntityId())
     {
         return GE_OVERFLOW;
     }
     // Executable code:
     message.clear();
     for(const auto& ele : this->getData())
     {
         // for each element in input message, call addData(...) to append internal buffer
         message.addData(ele.first, ele.second);
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  MQTT_Message::fcn << ");
 #endif
     return GE_OK;
 }
References addData(), clear(), GE_OK, GE_OVERFLOW, getData(), getEntityId(), getMaxAllowedBufferSize(), LOG_PRINT_INFO, and LOG_TAG.
Referenced by DistanceSensorController::updateInternalBuffer().
getBufferSize()
auto MQTT_Message::getBufferSize (void) const inline
Definition at line 107 of file MQTT_Message.hpp.
     {
         return m_data.size();
     }
References m_data.
Referenced by ServiceBase< MQTT_Message >::postData().
getData()
const auto& MQTT_Message::getData (void) const inline
Definition at line 114 of file MQTT_Message.hpp.
     {
         return m_data;
     };
References m_data.
Referenced by append(), copyTo(), and WaterEstimator_Service::mainFunction().
getEntityId()
auto MQTT_Message::getEntityId () const inline
Definition at line 122 of file MQTT_Message.hpp.
     {
         return m_entity_id;
     }
References m_entity_id.
Referenced by copyTo().
getMaxAllowedBufferSize()
auto MQTT_Message::getMaxAllowedBufferSize () const inline
Definition at line 118 of file MQTT_Message.hpp.
     {
         return m_buffer_size;
     }
References m_buffer_size.
Referenced by copyTo(), and DistanceSensorController::main_function().
isEmpty()
bool MQTT_Message::isEmpty (void) const inline
Definition at line 101 of file MQTT_Message.hpp.
     {
         return m_data.empty();
     };
References m_data.
Referenced by append().
toString()
const std::string MQTT_Message::toString (void) const
Definition at line 127 of file MQTT_Message.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MQTT_Message::toString >> ");
 #endif
     // Executable code:
     std::string str = "";
 #ifdef __ESP32__
     if(!m_semaphore.take(5000, "toString"))
     {
         return str;
     }
 #endif
     str = std::to_string(m_entity_id) + ",";
     for(auto ele : m_data)
     {
         str += std::to_string(ele.first);
         str += ",";
         str += std::to_string(ele.second);
         str += ",";
     }
 #ifdef __ESP32__
     m_semaphore.give();
 #endif
     // remove the last ","
     str = str.substr(0, str.size() - 1);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MQTT_Message::toString << ");
 #endif
     return str;
 }
References LOG_PRINT_INFO, LOG_TAG, m_data, m_entity_id, and m_semaphore.
Referenced by ActiveCurrentSensor::main_function(), SensorControllerBase::postData(), and ServiceBase< MQTT_Message >::postData().
Member Data Documentation
m_buffer_size
const size_t MQTT_Message::m_buffer_size private
Definition at line 131 of file MQTT_Message.hpp.
Referenced by addData(), and getMaxAllowedBufferSize().
m_data
std::vector<std::pair<uint64_t, uint64_t> > MQTT_Message::m_data private
Definition at line 132 of file MQTT_Message.hpp.
Referenced by addData(), clear(), getBufferSize(), getData(), isEmpty(), and toString().
m_entity_id
const uint64_t MQTT_Message::m_entity_id private
Definition at line 130 of file MQTT_Message.hpp.
Referenced by getEntityId(), and toString().
m_semaphore
std::string MQTT_Message::m_semaphore private
Definition at line 136 of file MQTT_Message.hpp.
Referenced by addData(), clear(), and toString().
The documentation for this class was generated from the following files:
Components/Protocols/MQTT/include/MQTT_Message.hpp
Components/Protocols/MQTT/src/MQTT_Message.cpp