Embedded Library: Components/Objects/Watchdog/test/test/watch_clock_test.cpp File Reference
watch_clock_test.cpp File Reference
#include "../../include/Watch_Clock.hpp"
#include <iostream>
#include "CppUTest/TestHarness.h"
Functions
TEST_GROUP (WCH_CLK_GRP)
TEST (WCH_CLK_GRP, notinit)
TEST (WCH_CLK_GRP, ok)
TEST (WCH_CLK_GRP, test_nothing)
TEST (WCH_CLK_GRP, test_send)
TEST (WCH_CLK_GRP, test_wrong_time)
TEST (WCH_CLK_GRP, test_send_multi)
TEST (WCH_CLK_GRP, test_send_multi2)
TEST (WCH_CLK_GRP, test_reset_1)
TEST (WCH_CLK_GRP, test_reset_2)
TEST (WCH_CLK_GRP, new_init)
Variables
uint32_t fake_start_time
uint32_t fake_end_time
Function Documentation
TEST() [1/10]
TEST (WCH_CLK_GRP , new_init)
Definition at line 126 of file watch_clock_test.cpp.
 {
     Watch_Clock clock(200);
     fake_end_time = Timeservice::getTimeNow();
     auto evt = clock.watch();
     CHECK_EQUAL(watchdog_event_t::NO_EVENT, evt);
 }
References fake_end_time, Timeservice::getTimeNow(), NO_EVENT, and Watch_Clock::watch().
TEST() [2/10]
TEST (WCH_CLK_GRP , notinit)
Definition at line 31 of file watch_clock_test.cpp.
 {
     Watch_Clock wa;
     CHECK_EQUAL(watchdog_event_t::FAIL_EVENT, wa.watch());
 }
References FAIL_EVENT, and Watch_Clock::watch().
TEST() [3/10]
TEST (WCH_CLK_GRP , ok)
Definition at line 37 of file watch_clock_test.cpp.
 {
     CHECK_EQUAL(watchdog_event_t::NO_EVENT, m_clock.watch());
 }
References NO_EVENT.
TEST() [4/10]
TEST (WCH_CLK_GRP , test_nothing)
Definition at line 43 of file watch_clock_test.cpp.
 {
     fake_end_time = 100;
     CHECK_EQUAL(watchdog_event_t::NO_EVENT, m_clock.watch());
 }
References fake_end_time, and NO_EVENT.
TEST() [5/10]
TEST (WCH_CLK_GRP , test_reset_1)
Definition at line 95 of file watch_clock_test.cpp.
 {
     fake_end_time = 0;
     for(size_t i = 0; i < 10; i++)
     {
         fake_end_time += 150;
         CHECK_EQUAL(watchdog_event_t::NO_EVENT, m_clock.watch());
         m_clock.reset();
     }
 }
References fake_end_time, and NO_EVENT.
TEST() [6/10]
TEST (WCH_CLK_GRP , test_reset_2)
Definition at line 107 of file watch_clock_test.cpp.
 {
     fake_end_time = 0;
     for(size_t i = 0; i < 10; i++)
     {
         fake_end_time += 150;
         CHECK_EQUAL(watchdog_event_t::NO_EVENT, m_clock.watch());
         m_clock.reset();
     }
     for(size_t i = 0; i < 10; i++)
     {
         fake_end_time += 201;
         CHECK_EQUAL(watchdog_event_t::SEND_EVENT, m_clock.watch());
         //  m_clock.reset();
     }
 }
References fake_end_time, NO_EVENT, and SEND_EVENT.
TEST() [7/10]
TEST (WCH_CLK_GRP , test_send)
Definition at line 50 of file watch_clock_test.cpp.
 {
     fake_end_time = 1000;
     CHECK_EQUAL(watchdog_event_t::SEND_EVENT, m_clock.watch());
 }
References fake_end_time, and SEND_EVENT.
TEST() [8/10]
TEST (WCH_CLK_GRP , test_send_multi)
Definition at line 67 of file watch_clock_test.cpp.
 {
     fake_end_time = 1000;
     for(size_t i = 0; i < 10; i++)
     {
         fake_end_time += 201;
         CHECK_EQUAL(watchdog_event_t::SEND_EVENT, m_clock.watch());
     }
 }
References fake_end_time, and SEND_EVENT.
TEST() [9/10]
TEST (WCH_CLK_GRP , test_send_multi2)
Definition at line 78 of file watch_clock_test.cpp.
 {
     fake_end_time = 51;
     CHECK_EQUAL(watchdog_event_t::NO_EVENT, m_clock.watch());
     fake_end_time += 51;
     CHECK_EQUAL(watchdog_event_t::NO_EVENT, m_clock.watch());
     fake_end_time += 51;
     CHECK_EQUAL(watchdog_event_t::NO_EVENT, m_clock.watch());
     fake_end_time += 51;
     CHECK_EQUAL(watchdog_event_t::NO_EVENT, m_clock.watch());
     fake_end_time += 51;
     CHECK_EQUAL(watchdog_event_t::SEND_EVENT, m_clock.watch());
     fake_end_time += 51;
     CHECK_EQUAL(watchdog_event_t::NO_EVENT, m_clock.watch());
 }
References fake_end_time, NO_EVENT, and SEND_EVENT.
TEST() [10/10]
TEST (WCH_CLK_GRP , test_wrong_time)
Definition at line 57 of file watch_clock_test.cpp.
 {
     Watch_Clock wa;
     fake_end_time = 10;
     fake_start_time = 1000;
     wa.initialize(200);
     CHECK_EQUAL(watchdog_event_t::FAIL_EVENT, wa.watch());
 }
References FAIL_EVENT, fake_end_time, fake_start_time, Watch_Clock::initialize(), and Watch_Clock::watch().
TEST_GROUP()
TEST_GROUP (WCH_CLK_GRP)
Definition at line 16 of file watch_clock_test.cpp.
 {
     Watch_Clock m_clock;
     void setup()
     {
         fake_start_time = 21;
         m_clock.initialize(200);
     }
     void teardown()
     {
         // Uninit stuff
     }
 };
References fake_start_time, and Watch_Clock::initialize().
Variable Documentation
fake_end_time
uint32_t fake_end_time
Referenced by Watch_Clock::reset(), TEST(), and Watch_Clock::watch().
fake_start_time
uint32_t fake_start_time
Referenced by Watch_Clock::initialize(), TEST(), and TEST_GROUP().