Embedded Library: Timeservice Class Reference
Timeservice Class Reference
#include <Timeservice.hpp>
Public Member Functions
Timeservice ()=default
~Timeservice ()=default
Static Public Member Functions
static uint64_t getTimeNow () noexcept
return the time in ms
static uint64_t getTimeInUsNow () noexcept
return the time in µs
static general_err_t wait_ms (size_t ms_to_wait)
static general_err_t wait_sec (size_t sec_to_wait)
static general_err_t wait_untill_ms (const uint64_t &start_time, const uint64_t &ms_to_wait)
static general_err_t initialize_sntp ()
static std::string getCurrentDate () noexcept
static std::string getCurrentDate (const timeval &time) noexcept
static uint64_t convertTimevalToTime (const timeval &time) noexcept
static std::string getYearMonthDay () noexcept
Detailed Description
Definition at line 72 of file Timeservice.hpp.
Constructor & Destructor Documentation
Timeservice()
Timeservice::Timeservice () default
~Timeservice()
Timeservice::~Timeservice () default
Member Function Documentation
convertTimevalToTime()
uint64_t Timeservice::convertTimevalToTime (const timeval & time) static noexcept
Definition at line 194 of file Timeservice.cpp.
 {
     if(time.tv_usec > 1000)
     {
         // add the milisec part
         return (time.tv_sec * 1000) + (time.tv_usec / 1000);
     }
     return time.tv_sec * 1000;
 }
Referenced by IGNORE_TEST(), and TEST().
getCurrentDate() [1/2]
std::string Timeservice::getCurrentDate () static noexcept
Definition at line 158 of file Timeservice.cpp.
 {
     time_t now = time(nullptr);
     struct tm tstruct
     {
     };
     char buf[80];
     tstruct = *localtime(&now);
     strftime(buf, sizeof(buf), "%Y%m%d_%H%M_%S", &tstruct);
     const auto ms = Timeservice::getTimeNow() % 1000;
     std::string str = buf;
     str.append("_");
     str.append(std::to_string(ms));
     return str;
 }
References getTimeNow().
Referenced by Utility_Image::putDate(), and TEST().
getCurrentDate() [2/2]
std::string Timeservice::getCurrentDate (const timeval & time) static noexcept
Definition at line 176 of file Timeservice.cpp.
 {
     time_t now = time.tv_sec;
     struct tm tstruct
     {
     };
     char buf[80];
     tstruct = *localtime(&now);
     strftime(buf, sizeof(buf), "%Y%m%d_%H%M_%S", &tstruct);
     const auto ms = Timeservice::getTimeNow() % 1000;
     std::string str = buf;
     str.append("_");
     str.append(std::to_string(ms));
     return str;
 }
References getTimeNow().
getTimeInUsNow()
uint64_t Timeservice::getTimeInUsNow () static noexcept
return the time in µs
Attention
Returns
GE_OK
Definition at line 117 of file Timeservice.cpp.
 {
     return std::chrono::duration_cast<std::chrono::microseconds>(
                std::chrono::system_clock::now().time_since_epoch())
         .count();
 }
getTimeNow()
uint64_t Timeservice::getTimeNow () static noexcept
return the time in ms
Attention
Returns
GE_OK
Definition at line 95 of file Timeservice.cpp.
 {
 #ifdef __UNITTEST__
 #ifdef __WITH_MOCK_TIME__ // can be used to overwrite the timestamp in unit tests
     return 1000UL;
 #endif
 #endif
     return std::chrono::duration_cast<std::chrono::milliseconds>(
                std::chrono::system_clock::now().time_since_epoch())
         .count();
 }
Referenced by QueryMessageBase< float >::addData(), MQTT_Message::addData(), getCurrentDate(), IGNORE_TEST(), Watch_Clock::initialize(), DistanceSensorController::main_function(), Maintainer::periodic_restart(), Watch_Clock::reset(), TEST(), ErrorCodeParser::toString(), wait_untill_ms(), Watch_Clock::watch(), Watch_Clock::Watch_Clock(), and Logger::write().
getYearMonthDay()
std::string Timeservice::getYearMonthDay () static noexcept
function to return the year, month and day in the formate "YYYYMMDD" as an example : "20211102" @usage this function can be used for folder structure if we want to save images to a given location with seperation for each new day.
Definition at line 204 of file Timeservice.cpp.
 {
     time_t now = time(nullptr);
     struct tm tstruct
     {
     };
     char buf[80];
     tstruct = *localtime(&now);
     strftime(buf, sizeof(buf), "%Y%m%d", &tstruct);
     std::string str = buf;
     return str;
 }
Referenced by TEST().
initialize_sntp()
general_err_t Timeservice::initialize_sntp () static
Definition at line 35 of file Timeservice.cpp.
 {
 #ifdef __DEBUG__
     LOG_PRINT_INFO(LOG_TAG, ">> Timeservice::refresh_time >> ");
 #endif
     // Executable code:
     return RTC_HAL::sntp_update();
 #ifdef __DEBUG__
     LOG_PRINT_INFO(LOG_TAG, "<< Timeservice::refresh_time << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, LOG_TAG, and RTC_HAL::sntp_update().
wait_ms()
general_err_t Timeservice::wait_ms (size_t ms_to_wait) static
Definition at line 67 of file Timeservice.cpp.
 {
 #ifdef __DEBUG__
     LOG_PRINT_INFO(LOG_TAG, ">> Timeservice::wait_poll_ms >> ");
 #endif
 // Executable code:
 #ifdef __ESP32__
     vTaskDelay(ms_to_wait / portTICK_PERIOD_MS);
 #else
     std::this_thread::sleep_for(std::chrono::milliseconds(ms_to_wait));
 #endif
 #ifdef __DEBUG__
     LOG_PRINT_INFO(LOG_TAG, "<< Timeservice::wait_poll_ms << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by Maintainer::checkOTAUpdate(), Fault_Handler::handle(), IGNORE_TEST(), DistanceSensorController::main_function(), DataBroker::main_function(), ActiveCurrentSensor::main_function(), DataBroker::run(), SensorControllerBase::run(), MG996R::setToMaximumSlowly(), MG996R::setToMinimumSlowly(), and wait_untill_ms().
wait_sec()
general_err_t Timeservice::wait_sec (size_t sec_to_wait) static
Definition at line 49 of file Timeservice.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Timeservice::wait_sec >> ");
 #endif
     // Executable code:
 #ifdef __ESP32__
     vTaskDelay((sec_to_wait * 1000UL) / portTICK_PERIOD_MS);
 #else
     std::this_thread::sleep_for(std::chrono::seconds(sec_to_wait));
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Timeservice::wait_sec << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by Maintainer::run().
wait_untill_ms()
general_err_t Timeservice::wait_untill_ms (const uint64_t & start_time, const uint64_t & ms_to_wait) static
Definition at line 124 of file Timeservice.cpp.
 {
 #ifdef __DEBUG__
     LOG_PRINT_INFO(LOG_TAG, ">> Timeservice::wait_untill_ms >> ");
 #endif
     // Executable code:
     uint64_t time_now = getTimeNow();
     if(start_time > time_now)
     {
         // we have to please the watchdog even with an error
         wait_ms(ms_to_wait);
         return GE_FAIL;
     }
     auto time_diff = time_now - start_time;
     if(time_diff > ms_to_wait)
     {
 #ifdef __DEBUG__
         std::cout << "time_diff : " << (int)time_diff << " ms to wait : " << (int)ms_to_wait
                   << "\n";
 #endif
         // we have to please the watchdog even with an error
         wait_ms(ms_to_wait);
         return GE_TIMEOUT;
     }
     wait_ms(ms_to_wait - time_diff);
 #ifdef __DEBUG__
     LOG_PRINT_INFO(LOG_TAG, "<< Timeservice::wait_untill_ms << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, GE_TIMEOUT, getTimeNow(), LOG_PRINT_INFO, LOG_TAG, and wait_ms().
The documentation for this class was generated from the following files:
Components/Objects/Timeservice/include/Timeservice.hpp
Components/Objects/Timeservice/src/Timeservice.cpp