Embedded Library: OTA Class Reference
OTA Class Reference
#include <OTA.hpp>
Public Member Functions
OTA ()
~OTA ()
Static Public Member Functions
static general_err_t update (const char *msg, const size_t &length)
static bool isUpdateStarted (void)
Static Private Member Functions
static general_err_t start_process (const char *msg, const size_t &length)
static general_err_t stop_process (const char *msg, const size_t &length)
static general_err_t update_process (const char *msg, const size_t &length)
Detailed Description
Definition at line 69 of file OTA.hpp.
Constructor & Destructor Documentation
OTA()
OTA::OTA ()
Definition at line 43 of file OTA.cpp.
 {}
~OTA()
OTA::~OTA ()
Definition at line 45 of file OTA.cpp.
 {}
Member Function Documentation
isUpdateStarted()
bool OTA::isUpdateStarted (void) static
Definition at line 151 of file OTA.cpp.
 {
     return is_req_body_started;
 }
References is_req_body_started.
Referenced by Maintainer::isOTAUpdateStarted().
start_process()
general_err_t OTA::start_process (const char * msg, const size_t & length) static private
Definition at line 81 of file OTA.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> OTA::start_process >> ");
 #endif
     // Executable code:
 #ifdef __ESP32__
     const esp_partition_t* update_partition = esp_ota_get_next_update_partition(NULL);
     ESP_ERROR_CHECK(esp_ota_begin(update_partition, OTA_SIZE_UNKNOWN, &ota_handle));
 #endif
     is_req_body_started = true;
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< OTA::start_process << ");
 #endif
     return GE_OK;
 }
References GE_OK, is_req_body_started, LOG_PRINT_INFO, and LOG_TAG.
Referenced by update().
stop_process()
general_err_t OTA::stop_process (const char * msg, const size_t & length) static private
Definition at line 100 of file OTA.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> OTA::stop_process >> ");
 #endif
     // Executable code:
     std::cout << " we have finished updating, and recieved a total of : " << content_received
               << " bytes \n";
 #ifdef __ESP32__
     ESP_ERROR_CHECK(esp_ota_end(ota_handle));
     const esp_partition_t* update_partition = esp_ota_get_next_update_partition(NULL);
     esp_err_t err = esp_ota_set_boot_partition(update_partition);
     const esp_partition_t* boot_partition = esp_ota_get_boot_partition();
     ESP_LOGI(LOG_TAG, "Next boot partition subtype %d at offset 0x%x", boot_partition->subtype,
              boot_partition->address);
     ESP_LOGI(LOG_TAG, "Prepare to restart system!");
     esp_restart();
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< OTA::stop_process << ");
 #endif
     return GE_OK;
 }
References content_received, GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by update().
update()
general_err_t OTA::update (const char * msg, const size_t & length) static
Definition at line 47 of file OTA.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> OTA::update >> ");
 #endif
     // Executable code:
     if(length < 25)
     {
         std::string str{msg, length};
         std::cout << str << "\n";
         if(str.compare("ota_start") == 0)
         {
             std::cout << "do ota start process ....\n";
             start_process(msg, length);
         }
         if(str.compare("ota_stop") == 0)
         {
             std::cout << "do ota stop process ....\n";
             stop_process(msg, length);
         }
     }
     else
     {
         update_process(msg, length);
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< OTA::update << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, LOG_TAG, start_process(), stop_process(), and update_process().
update_process()
general_err_t OTA::update_process (const char * msg, const size_t & length) static private
Definition at line 126 of file OTA.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> OTA::update_process >> ");
 #endif
     // Executable code:
     if(is_req_body_started)
     {
 #ifdef __ESP32__
         esp_ota_write(ota_handle, msg, length);
 #endif
         content_received += length;
     }
     else
     {
         return GE_FAIL;
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< OTA::update_process << ");
 #endif
     return GE_OK;
 }
References content_received, GE_FAIL, GE_OK, is_req_body_started, LOG_PRINT_INFO, and LOG_TAG.
Referenced by update().
The documentation for this class was generated from the following files:
Components/Objects/OTA/include/OTA.hpp
Components/Objects/OTA/src/OTA.cpp