Embedded Library: WiFi_SAL_esp32 Class Reference
WiFi_SAL_esp32 Class Reference final
#include <WiFi_SAL_esp32.hpp>
Public Member Functions
WiFi_SAL_esp32 (const wifi_conf_t &config)
WiFi_SAL_esp32 (const std::string &ssid, const std::string &pwd)
virtual ~WiFi_SAL_esp32 ()
general_err_t connect () override
general_err_t disconnect () override
Public Member Functions inherited from WiFiBase
WiFiBase (const std::string &ssid, const std::string &pwd)
virtual ~WiFiBase ()
Public Member Functions inherited from ConnectorBase
ConnectorBase ()
virtual ~ConnectorBase ()
Private Member Functions
WiFi_SAL_esp32 & operator= (WiFi_SAL_esp32 const &rhs)=delete
WiFi_SAL_esp32 (WiFi_SAL_esp32 const &src)=delete
Static Private Member Functions
static void event_handler (void *arg, esp_event_base_t event_base, int32_t event_id, void *event_data)
Private Attributes
esp_event_handler_instance_t instance_any_id
esp_event_handler_instance_t instance_got_ip
wifi_init_config_t m_cfg
Additional Inherited Members
Protected Attributes inherited from WiFiBase
const std::string m_ssid
const std::string m_pwd
Detailed Description
Definition at line 73 of file WiFi_SAL_esp32.hpp.
Constructor & Destructor Documentation
WiFi_SAL_esp32() [1/3]
WiFi_SAL_esp32::WiFi_SAL_esp32 (const wifi_conf_t & config)
Definition at line 48 of file WiFi_SAL_esp32.cpp.
                                                         : WiFiBase(config.ssid, config.password)
 {
 #ifdef __ESP32__
     // Initialize NVS
     esp_err_t ret = nvs_flash_init();
     if(ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND)
     {
         ESP_ERROR_CHECK(nvs_flash_erase());
         ret = nvs_flash_init();
     }
     ESP_ERROR_CHECK(ret);
 #endif
 }
WiFi_SAL_esp32() [2/3]
WiFi_SAL_esp32::WiFi_SAL_esp32 (const std::string & ssid, const std::string & pwd)
Definition at line 33 of file WiFi_SAL_esp32.cpp.
     : WiFiBase(ssid, pwd)
 {
 #ifdef __ESP32__
     // Initialize NVS
     esp_err_t ret = nvs_flash_init();
     if(ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND)
     {
         ESP_ERROR_CHECK(nvs_flash_erase());
         ret = nvs_flash_init();
     }
     ESP_ERROR_CHECK(ret);
 #endif
 }
~WiFi_SAL_esp32()
WiFi_SAL_esp32::~WiFi_SAL_esp32 () virtual
Definition at line 62 of file WiFi_SAL_esp32.cpp.
 {}
WiFi_SAL_esp32() [3/3]
WiFi_SAL_esp32::WiFi_SAL_esp32 (WiFi_SAL_esp32 const & src) private delete
Member Function Documentation
connect()
general_err_t WiFi_SAL_esp32::connect () override virtual
Implements ConnectorBase.
Definition at line 64 of file WiFi_SAL_esp32.cpp.
 {
 #ifdef DEBUG
     std::cout << " >> WiFi_SAL_esp32::connect >> \n";
 #endif
     // do magic
 #ifdef __ESP32__
     ESP_ERROR_CHECK(esp_netif_init());
     ESP_ERROR_CHECK(esp_event_loop_create_default());
     esp_netif_create_default_wifi_sta();
     m_cfg = WIFI_INIT_CONFIG_DEFAULT();
     ESP_ERROR_CHECK(esp_wifi_init(&m_cfg));
     ESP_ERROR_CHECK(esp_event_handler_instance_register(
         WIFI_EVENT, ESP_EVENT_ANY_ID, &WiFi_SAL_esp32::event_handler, NULL, &instance_any_id));
     ESP_ERROR_CHECK(esp_event_handler_instance_register(
         IP_EVENT, IP_EVENT_STA_GOT_IP, &WiFi_SAL_esp32::event_handler, NULL, &instance_got_ip));
     wifi_config_t wifi_config;
     ::memcpy(wifi_config.sta.ssid, m_ssid.data(), m_ssid.size());
     ::memcpy(wifi_config.sta.password, m_pwd.data(), m_pwd.size());
     // wifi_config.sta.ssid = reinterpret_cast<uint8_t>(const_cast<char*>(m_ssid.c_str()));
     // wifi_config.sta.password = reinterpret_cast<uint8_t*>(const_cast<char*>(m_pwd.c_str()));
     wifi_config.sta.scan_method = WIFI_FAST_SCAN;
     wifi_config.sta.bssid_set = false;
     wifi_config.sta.channel = 0;
     wifi_config.sta.listen_interval = 0;
     wifi_config.sta.sort_method = WIFI_CONNECT_AP_BY_SIGNAL;
     wifi_config.sta.threshold.authmode = WIFI_AUTH_WEP;
     wifi_config.sta.pmf_cfg.capable = true;
     wifi_config.sta.pmf_cfg.required = false;
     //  wifi_config.sta.threshold.authmode = ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD;
     ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
     ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_config));
     std::cout << " start WiFi .. \n";
     ESP_ERROR_CHECK(esp_wifi_start());
 #endif
     while(!WIFI_CONNECTION_SUCCESS and !WIFI_CONNECTION_FAIL)
     {
         std::cout << "waiting for wifi ... \n";
         Timeservice::wait_sec(1);
     }
     if(WIFI_CONNECTION_SUCCESS)
     {
         std::cout << " we have sucessfully connected to wifi! \n";
 #ifdef __ESP32__
         std::cout << "wifi info : \n";
         wifi_ap_record_t ap_info;
         esp_wifi_sta_get_ap_info(&ap_info);
         std::cout << " RSSI valus for <" << m_ssid << "> is : " << (int)ap_info.rssi << "\n";
 #endif
         return GE_OK;
     }
     else
     {
         std::cout << "we failed to connect to wifi ... \n";
         return GE_FAIL;
     }
 #ifdef DEBUG
     std::cout << " << WiFi_SAL_esp32::connect << \n";
 #endif
     return GE_OK;
 }
References event_handler(), GE_FAIL, GE_OK, instance_any_id, instance_got_ip, m_cfg, WiFiBase::m_pwd, WiFiBase::m_ssid, Timeservice::wait_sec(), WIFI_CONNECTION_FAIL, and WIFI_CONNECTION_SUCCESS.
disconnect()
general_err_t WiFi_SAL_esp32::disconnect () override virtual
Implements ConnectorBase.
Definition at line 137 of file WiFi_SAL_esp32.cpp.
 {
 #ifdef DEBUG
     std::cout << " >> WiFi_SAL_esp32::disconnect >> \n";
 #endif
     // do magic
 #ifdef DEBUG
     std::cout << " << WiFi_SAL_esp32::disconnect << \n";
 #endif
     return GE_OK;
 }
References GE_OK.
event_handler()
void WiFi_SAL_esp32::event_handler (void * arg, esp_event_base_t event_base, int32_t event_id, void * event_data) static private
Definition at line 151 of file WiFi_SAL_esp32.cpp.
 {
     std::cout << "recieved an event! \n";
 #ifdef __ESP32__
     if(event_base == WIFI_EVENT)
     {
         std::cout << "The event is WiFi and id is {" << (int)event_id << " } \n";
     }
     else
     {
         std::cout << "The event was no a wifi event... \n";
     }
     if(event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START)
     {
         std::cout << " event is : WIFI_EVENT_STA_START ... starting wifi \n";
         esp_wifi_connect();
     }
     else if(event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED)
     {
         std::cout << " event is : WIFI_EVENT_STA_DISCONNECTED ... retrying to connect \n";
         WIFI_CONNECTION_SUCCESS = false;
         if(s_retry_num < MAXIMUM_RETRY)
         {
             esp_wifi_connect();
             s_retry_num++;
         }
         else
         {
             std::cout << " could not connect to wifi ... \n";
             WIFI_CONNECTION_FAIL = true;
         }
     }
     else if(event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED)
     {
         std::cout << " event is : WIFI_EVENT_STA_CONNECTED ... WiFI connected! \n";
     }
     else if(event_base == WIFI_EVENT && event_id == IP_EVENT_STA_GOT_IP)
     {
         std::cout << " event is : IP_EVENT_STA_GOT_IP ... Got IP! \n";
         ip_event_got_ip_t* event = (ip_event_got_ip_t*)event_data;
         ESP_LOGI(LOG_TAG, "got ip:" IPSTR, IP2STR(&event->ip_info.ip));
         s_retry_num = 0;
         WIFI_CONNECTION_SUCCESS = true;
         WIFI_CONNECTION_FAIL = false;
     }
     else if(event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP)
     {
         ip_event_got_ip_t* event = (ip_event_got_ip_t*)event_data;
         ESP_LOGI(LOG_TAG, "got ip:" IPSTR, IP2STR(&event->ip_info.ip));
         s_retry_num = 0;
         WIFI_CONNECTION_SUCCESS = true;
         WIFI_CONNECTION_FAIL = false;
     }
 #endif
 }
References LOG_TAG, MAXIMUM_RETRY, s_retry_num, WIFI_CONNECTION_FAIL, and WIFI_CONNECTION_SUCCESS.
Referenced by connect().
operator=()
WiFi_SAL_esp32& WiFi_SAL_esp32::operator= (WiFi_SAL_esp32 const & rhs) private delete
Member Data Documentation
instance_any_id
esp_event_handler_instance_t WiFi_SAL_esp32::instance_any_id private
Definition at line 83 of file WiFi_SAL_esp32.hpp.
Referenced by connect().
instance_got_ip
esp_event_handler_instance_t WiFi_SAL_esp32::instance_got_ip private
Definition at line 84 of file WiFi_SAL_esp32.hpp.
Referenced by connect().
m_cfg
wifi_init_config_t WiFi_SAL_esp32::m_cfg private
Definition at line 85 of file WiFi_SAL_esp32.hpp.
Referenced by connect().
The documentation for this class was generated from the following files:
Components/Connector/WiFi_v2/include/WiFi_SAL_esp32.hpp
Components/Connector/WiFi_v2/src/WiFi_SAL_esp32.cpp