Embedded Library: ConnectedComponents Class Reference
ConnectedComponents Class Reference
#include <ConnectedComponents.hpp>
Classes
struct container_t
struct ellipse_data_t
Static Public Member Functions
static general_err_t drawConnectedComponents (const cv::Mat &forground, cv::Mat &drawing)
static uint32_t maxConnectedComponents (const cv::Mat &forground, int ksize=2)
static container_t statsConnectedComponents (const cv::Mat &forground, int ksize=2)
Detailed Description
Definition at line 69 of file ConnectedComponents.hpp.
Class Documentation
ConnectedComponents::container_t
struct ConnectedComponents::container_t
Definition at line 83 of file ConnectedComponents.hpp.
Class Members
size_t amount_of_connections
ellipse_data_t ellipse
uint32_t maxConnected
ConnectedComponents::ellipse_data_t
struct ConnectedComponents::ellipse_data_t
Definition at line 75 of file ConnectedComponents.hpp.
Class Members
float area
float aspect_ratio
float height
float width
Member Function Documentation
drawConnectedComponents()
general_err_t ConnectedComponents::drawConnectedComponents (const cv::Mat & forground, cv::Mat & drawing) static
Definition at line 30 of file ConnectedComponents.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> ConnectedComponents::drawConnectedComponents >> ");
 #endif
     // Executable code:
     if(forground.empty())
     {
         return GE_EMPTY;
     }
     int ksize = 2;
     cv::morphologyEx(forground, forground, cv::MORPH_OPEN,
                      cv::getStructuringElement(cv::MORPH_RECT, cv::Size_<int>{ksize, ksize}));
     cv::morphologyEx(forground, forground, cv::MORPH_CLOSE,
                      cv::getStructuringElement(cv::MORPH_RECT, cv::Size_<int>{ksize, ksize}));
     bool cont_found = false;
     std::vector<std::vector<cv::Point>> cont;
     findContours(forground, cont, cv::CHAIN_APPROX_SIMPLE, cv::RETR_TREE, cv::Point(0, 0));
     std::vector<int> ix;
     for(size_t i = 0; i < cont.size(); i++)
     {
         auto& ele = cont.at(i);
         double len = ele.size();
         double q = (forground.cols + forground.rows) / 4;
         std::cout << " size of len :" << (int)len << " size of q : " << (int)q << "\n";
         if(len > q)
         {
             ix.push_back(i);
         }
     }
     std::cout << " size of ix :" << (int)ix.size() << "\n";
     for(auto ele : ix)
     {
         cv::drawContours(drawing, cont, ele, cv::Scalar{255, 255, 0}, 1);
         cont_found = true;
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< ConnectedComponents::drawConnectedComponents << ");
 #endif
     return cont_found == true ? GE_OK : GE_NO_DATA;
 }
References GE_EMPTY, GE_NO_DATA, GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by TEST().
maxConnectedComponents()
uint32_t ConnectedComponents::maxConnectedComponents (const cv::Mat & forground, int ksize = 2) static
Definition at line 81 of file ConnectedComponents.cpp.
 {
     if(forground.empty())
     {
         return 0;
     }
     cv::morphologyEx(forground, forground, cv::MORPH_OPEN,
                      cv::getStructuringElement(cv::MORPH_RECT, cv::Size_<int>{ksize, ksize}));
     cv::morphologyEx(forground, forground, cv::MORPH_CLOSE,
                      cv::getStructuringElement(cv::MORPH_RECT, cv::Size_<int>{ksize, ksize}));
     std::vector<std::vector<cv::Point>> cont;
     findContours(forground, cont, cv::CHAIN_APPROX_SIMPLE, cv::RETR_TREE, cv::Point(0, 0));
     uint32_t max = 0;
     for(auto ele : cont)
     {
         if(ele.size() > max)
         {
             max = ele.size();
         }
     }
     return max;
 }
Referenced by Background_Extractor::countConnectedComponents(), and TEST().
statsConnectedComponents()
ConnectedComponents::container_t ConnectedComponents::statsConnectedComponents (const cv::Mat & forground, int ksize = 2) static
Definition at line 109 of file ConnectedComponents.cpp.
 {
     container_t data{0};
     if(forground.empty())
     {
         return data;
     }
     cv::morphologyEx(forground, forground, cv::MORPH_OPEN,
                      cv::getStructuringElement(cv::MORPH_RECT, cv::Size_<int>{ksize, ksize}));
     cv::morphologyEx(forground, forground, cv::MORPH_CLOSE,
                      cv::getStructuringElement(cv::MORPH_RECT, cv::Size_<int>{ksize, ksize}));
     std::vector<std::vector<cv::Point>> cont;
     findContours(forground, cont, cv::CHAIN_APPROX_SIMPLE, cv::RETR_TREE, cv::Point(0, 0));
     data.maxConnected = 0;
     data.amount_of_connections = cont.size();
     // "best" way to get index of max connected
     int index = 0;
     int count = 0;
     for(auto ele : cont)
     {
         if(ele.size() > data.maxConnected)
         {
             data.maxConnected = ele.size();
             index = count;
         }
         count++;
     }
     if(data.maxConnected > 5)
     {
         auto ellipse = cv::fitEllipse(cont.at(index));
         data.ellipse.height = ellipse.size.height;
         data.ellipse.width = ellipse.size.width;
         data.ellipse.aspect_ratio = ellipse.size.aspectRatio();
         data.ellipse.area = ellipse.size.area();
     }
     return data;
 }
Referenced by Background_Extractor::statsConnectedComponents(), and TEST().
The documentation for this class was generated from the following files:
Components/AnalysisTools/ImageAnalysis_OpenCV/include/ConnectedComponents.hpp
Components/AnalysisTools/ImageAnalysis_OpenCV/src/ConnectedComponents.cpp