Embedded Library: General_Error Class Reference
General_Error Class Reference
#include <General_Error.hpp>
Static Public Member Functions
static std::string errorToString (general_err_t errCode)
static const char * responseToString (general_resp_t respCode)
static void printError (general_err_t errCode)
static void printError (const std::string &LOGTAG, general_err_t errCode)
static bool check_error (const general_err_t &errcode, const std::string &msg, const general_err_t &expected=GE_OK)
Detailed Description
Definition at line 97 of file General_Error.hpp.
Member Function Documentation
check_error()
bool General_Error::check_error (const general_err_t & errcode, const std::string & msg, const general_err_t & expected = GE_OK) static
Definition at line 98 of file General_Error.cpp.
 {
     if(err != expected)
     {
         std::cout << msg << "\n"
                   << "mismatch in expected error code:\n";
         std::cout << "got : " << errorToString(err) << " expected : " << errorToString(expected)
                   << "\n";
         return false;
     }
     return true;
 }
References errorToString().
errorToString()
std::string General_Error::errorToString (general_err_t errCode) static
Definition at line 28 of file General_Error.cpp.
 {
     // #lizard forgives the complexity
     switch(errCode)
     {
         case GE_OK:
             return ("OK");
         case GE_FAIL:
             return ("FAIL");
         case GE_OUT_OF_RANGE:
             return ("GE_OUT_OF_RANGE");
         case GE_OVERFLOW:
             return ("GE_OVERFLOW");
         case GE_UNDERFLOW:
             return ("GE_UNDERFLOW");
         case GE_NULLPTR:
             return ("GE_NULLPTR");
         case GE_TIMEOUT:
             return ("GE_TIMEOUT");
         case GE_NO_DATA:
             return ("GE_NO_DATA");
         case GE_UPPER_BOUNDERY:
             return ("GE_UPPER_BOUNDERY");
         case GE_LOWER_BOUNDERY:
             return ("GE_LOWER_BOUNDERY");
         case GE_NOT_INITIALIZED:
             return ("GE_NOT_INITIALIZED");
         case GE_CLOSED:
             return ("GE_CLOSED");
         case GE_EMPTY:
             return ("GE_EMPTY");
         case GE_SEMAPHORE_NOT_TAKEN:
             return ("GE_SEMAPHORE_NOT_TAKEN");
         case GE_VIRTUAL_SENSOR:
             return ("GE_VIRTUAL_SENSOR");
         case GE_OPEN:
             return ("GE_OPEN");
         case GE_NOT_CONNECTED:
             return ("GE_NOT_CONNECTED");
         default:
             return ("UNKNOWN ERROR CODE");
     }
 }
References GE_CLOSED, GE_EMPTY, GE_FAIL, GE_LOWER_BOUNDERY, GE_NO_DATA, GE_NOT_CONNECTED, GE_NOT_INITIALIZED, GE_NULLPTR, GE_OK, GE_OPEN, GE_OUT_OF_RANGE, GE_OVERFLOW, GE_SEMAPHORE_NOT_TAKEN, GE_TIMEOUT, GE_UNDERFLOW, GE_UPPER_BOUNDERY, and GE_VIRTUAL_SENSOR.
Referenced by MG996R::actuate(), check_error(), printError(), and Logger::write().
printError() [1/2]
void General_Error::printError (const std::string & LOGTAG, general_err_t errCode) static
Definition at line 85 of file General_Error.cpp.
 {
     if(errCode == GE_OK)
     {
         return;
     }
 #ifdef DISABLE_LOG_TO_OUTPUT
     return;
 #endif
     std::cout << LOGTAG << " ERROR :: " << errorToString(errCode) << "\n";
     return;
 }
References errorToString(), and GE_OK.
printError() [2/2]
void General_Error::printError (general_err_t errCode) static
Definition at line 72 of file General_Error.cpp.
 {
     if(errCode == GE_OK)
     {
         return;
     }
 #ifdef DISABLE_LOG_TO_OUTPUT
     return;
 #endif
     std::cout << LOG_TAG << "ERROR :: " << errorToString(errCode) << "\n";
     return;
 }
References errorToString(), GE_OK, and LOG_TAG.
responseToString()
const char * General_Error::responseToString (general_resp_t respCode) static
Definition at line 112 of file General_Error.cpp.
 {
     switch(respCode)
     {
         case GR_NO_RESPONSE:
             return ("NO RESPONSE");
         case GR_REBOOT:
             return ("REBOOT");
         case GR_EXIT:
             return ("EXIT");
         default:
             return ("UNKNOWN RESPONSE CODE");
     }
 }
References GR_EXIT, GR_NO_RESPONSE, and GR_REBOOT.
Referenced by Logger::write().
The documentation for this class was generated from the following files:
Components/Objects/ErrorHandler/include/General_Error.hpp
Components/Objects/ErrorHandler/src/General_Error.cpp