Embedded Library: EnvSensing_service Class Reference
EnvSensing_service Class Reference final
#include <EnvSensing_service.hpp>
Public Member Functions
EnvSensing_service (const db_id error_id, size_t delay, const db_id temperature_id, const db_id humidity_id, const i2c_conf_t &conf)
~EnvSensing_service ()
Public Member Functions inherited from ServiceTimeBase<&Timeservice::wait_sec >
ServiceTimeBase (const MQTT_Message &buffer, const db_id error_id, const size_t delay)
virtual ~ServiceTimeBase (void)
Public Member Functions inherited from ServiceBase< MQTT_Message >
ServiceBase (const MQTT_Message &buffer, const db_id error_id)
Construct a new Service Base object.
virtual ~ServiceBase ()
const auto & isActive () const
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Private Member Functions
general_err_t mainFunction () override
Main function for the derived class to work in It is expected that the function is a single-run function And that it should not be blocking.
Private Attributes
MQTT_Message msg_temperature
MQTT_Message msg_humidity
AM2320_Humidity m_humidity_sensor
AM2320_Temperature m_temperature_sensor
Additional Inherited Members
Protected Member Functions inherited from ServiceTimeBase<&Timeservice::wait_sec >
void run (void *data) override
loop for the service We are waiting "forever" on a queue recieve When we recieve something we will call the mainFunction() Which should be a single-end run for the derived class if any error happends it will be reported online.
Protected Member Functions inherited from ServiceBase< MQTT_Message >
virtual void setIsActive (bool isActive)
Set the Is Active object.
general_err_t postData (const MQTT_Message &message, const std::string &topic="mqtt/burst_msg")
Function to post data to database.
virtual general_err_t postError (const std::string &message, const general_err_t &err)
Method to post errors to the database.
Protected Attributes inherited from ServiceBase< MQTT_Message >
GPIO_API m_test_pin
const MQTT_Message & m_buffer
db_id m_error_id
Detailed Description
Definition at line 53 of file EnvSensing_service.hpp.
Constructor & Destructor Documentation
EnvSensing_service()
EnvSensing_service::EnvSensing_service (const db_id error_id, size_t delay, const db_id temperature_id, const db_id humidity_id, const i2c_conf_t & conf) inline
Definition at line 59 of file EnvSensing_service.hpp.
         : ServiceTimeBase<&Timeservice::wait_sec>(MQTT_Message{{db_id::CCTV01_DEBUG4, 1}}, error_id,
                                                   delay),
           msg_temperature{{temperature_id, 1}}, msg_humidity{{humidity_id, 1}},
           m_humidity_sensor{conf}, m_temperature_sensor{conf}
     {
         this->postError("[EnvSensing_service] :: Just rebooted", GE_OK);
     };
References CCTV01_DEBUG4.
~EnvSensing_service()
EnvSensing_service::~EnvSensing_service () inline
Definition at line 68 of file EnvSensing_service.hpp.
 {};
Member Function Documentation
mainFunction()
general_err_t EnvSensing_service::mainFunction () override private virtual
Main function for the derived class to work in It is expected that the function is a single-run function And that it should not be blocking.
Returns
general_err_t
Implements ServiceTimeBase<&Timeservice::wait_sec >.
Definition at line 29 of file EnvSensing_service.cpp.
 {
 #ifdef DEBUG
     std::cout << " >> EnvSensing_service::mainFunction >> \n";
 #endif
     // do magic
     auto temp_val = m_temperature_sensor.getMeasurement();
     if(temp_val > 0)
     {
         std::cout << " sending temperature data \n";
         msg_temperature.addData(temp_val);
         postData(msg_temperature);
         msg_temperature.clear();
     }
     auto hum_val = m_humidity_sensor.getMeasurement();
     if(hum_val > 0)
     {
         std::cout << " sending humidity data \n";
         msg_humidity.addData(hum_val);
         postData(msg_humidity);
         msg_humidity.clear();
     }
 #ifdef DEBUG
     std::cout << " << EnvSensing_service::mainFunction << \n";
 #endif
     return GE_OK;
 }
References MQTT_Message::addData(), MQTT_Message::clear(), GE_OK, AM2320_Base::getMeasurement(), m_humidity_sensor, m_temperature_sensor, msg_humidity, msg_temperature, and ServiceBase< MQTT_Message >::postData().
Member Data Documentation
m_humidity_sensor
AM2320_Humidity EnvSensing_service::m_humidity_sensor private
Definition at line 74 of file EnvSensing_service.hpp.
Referenced by mainFunction().
m_temperature_sensor
AM2320_Temperature EnvSensing_service::m_temperature_sensor private
Definition at line 75 of file EnvSensing_service.hpp.
Referenced by mainFunction().
msg_humidity
MQTT_Message EnvSensing_service::msg_humidity private
Definition at line 73 of file EnvSensing_service.hpp.
Referenced by mainFunction().
msg_temperature
MQTT_Message EnvSensing_service::msg_temperature private
Definition at line 72 of file EnvSensing_service.hpp.
Referenced by mainFunction().
The documentation for this class was generated from the following files:
Components/Service/EnvSensing/include/EnvSensing_service.hpp
Components/Service/EnvSensing/src/EnvSensing_service.cpp