Embedded Library: Watch_Clock Class Reference
Watch_Clock Class Reference
#include <Watch_Clock.hpp>
Public Member Functions
Watch_Clock (const size_t &parameter)
Watch_Clock ()
~Watch_Clock ()
general_err_t initialize (uint32_t parameter) override
initialize the block
watchdog_event_t watch () override
Watch the parameter.
general_err_t reset ()
reset the watchdog, this is also called pet-the-dog
Public Member Functions inherited from Watchdog_Base< uint32_t >
Watchdog_Base ()
virtual ~Watchdog_Base ()
Private Attributes
uint32_t m_last_time = 0
Additional Inherited Members
Protected Attributes inherited from Watchdog_Base< uint32_t >
uint32_t m_watch
bool m_initialized
Detailed Description
Definition at line 76 of file Watch_Clock.hpp.
Constructor & Destructor Documentation
Watch_Clock() [1/2]
Watch_Clock::Watch_Clock (const size_t & parameter)
Definition at line 35 of file Watch_Clock.cpp.
 {
     m_watch = parameter;
     m_last_time = Timeservice::getTimeNow();
     m_initialized = true;
 }
References Timeservice::getTimeNow(), Watchdog_Base< uint32_t >::m_initialized, m_last_time, and Watchdog_Base< uint32_t >::m_watch.
Watch_Clock() [2/2]
Watch_Clock::Watch_Clock ()
Definition at line 42 of file Watch_Clock.cpp.
 {}
~Watch_Clock()
Watch_Clock::~Watch_Clock ()
Definition at line 43 of file Watch_Clock.cpp.
 {}
Member Function Documentation
initialize()
general_err_t Watch_Clock::initialize (uint32_t parameter) override virtual
initialize the block
Attention
Returns
GE_OK
Implements Watchdog_Base< uint32_t >.
Definition at line 55 of file Watch_Clock.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Watch_Clock::initialize >> ");
 #endif
     // Executable code:
     // delay between current time and last time
     m_watch = parameter;
 // get time:
 #ifndef __UNITTEST__
     m_last_time = Timeservice::getTimeNow();
 #else
     // extern uint32_t fake_start_time; // found in watch_clock_test
     m_last_time = fake_start_time;
 #endif
     m_initialized = true;
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Watch_Clock::initialize << ");
 #endif
     return GE_OK;
 }
References fake_start_time, GE_OK, Timeservice::getTimeNow(), LOG_PRINT_INFO, LOG_TAG, Watchdog_Base< uint32_t >::m_initialized, m_last_time, and Watchdog_Base< uint32_t >::m_watch.
Referenced by TEST(), and TEST_GROUP().
reset()
general_err_t Watch_Clock::reset ()
reset the watchdog, this is also called pet-the-dog
Attention
Returns
GE_OK
Definition at line 141 of file Watch_Clock.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Watch_Clock::reset >> ");
 #endif
 // Executable code:
 // get time:
 #ifndef __UNITTEST__
     uint32_t current_time = Timeservice::getTimeNow();
 #else
     //  extern uint32_t fake_end_time; // found in watch_clock_test
     uint32_t current_time = fake_end_time;
 #endif
     m_last_time = current_time;
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Watch_Clock::reset << ");
 #endif
     return GE_OK;
 }
References fake_end_time, GE_OK, Timeservice::getTimeNow(), LOG_PRINT_INFO, LOG_TAG, and m_last_time.
watch()
watchdog_event_t Watch_Clock::watch () override virtual
Watch the parameter.
Parameters
[in] uint32_t timestamp
Returns
GE_OK
Implements Watchdog_Base< uint32_t >.
Definition at line 92 of file Watch_Clock.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Watch_Clock::watch >> ");
 #endif
     // Executable code:
     if(!m_initialized)
     {
         return watchdog_event_t::FAIL_EVENT;
     }
     // get time:
 #ifndef __UNITTEST__
     uint32_t current_time = Timeservice::getTimeNow();
 #else
     // extern uint32_t fake_end_time; // found in watch_clock_test
     uint32_t current_time = fake_end_time;
 #endif
     if(current_time < m_last_time)
     {
         return watchdog_event_t::FAIL_EVENT;
     }
     if((current_time - m_last_time) > m_watch)
     {
         // we should update the last time here
         m_last_time = current_time;
         return watchdog_event_t::SEND_EVENT;
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Watch_Clock::watch << ");
 #endif
     return watchdog_event_t::NO_EVENT;
 }
References FAIL_EVENT, fake_end_time, Timeservice::getTimeNow(), LOG_PRINT_INFO, LOG_TAG, Watchdog_Base< uint32_t >::m_initialized, m_last_time, Watchdog_Base< uint32_t >::m_watch, NO_EVENT, and SEND_EVENT.
Referenced by TEST().
Member Data Documentation
m_last_time
uint32_t Watch_Clock::m_last_time = 0 private
Definition at line 87 of file Watch_Clock.hpp.
Referenced by initialize(), reset(), watch(), and Watch_Clock().
The documentation for this class was generated from the following files:
Components/Objects/Watchdog/include/Watch_Clock.hpp
Components/Objects/Watchdog/src/Watch_Clock.cpp