Embedded Library: MG996R Class Reference
MG996R Class Reference final
#include <MG996R.hpp>
Public Member Functions
MG996R (const mg996r_conf_t &conf)
~MG996R ()
general_err_t setToMaximum (void) override
Set the To Maximum value.
general_err_t setToMinimum (void) override
Set the To Minimum value.
general_err_t setToMaximumSlowly (void)
Set the To Maximum Slowly value.
general_err_t setToMinimumSlowly (void)
Set the To Minimum Slowly value.
Public Member Functions inherited from Actuator_Base< mg996r_conf_t, float >
Actuator_Base (const mg996r_conf_t &conf)
virtual ~Actuator_Base ()
general_err_t execute (const float &value)
const float & getValue (void) const
Private Member Functions
general_err_t setPoint (const float &value) override
general_err_t actuate (void) override
Private Attributes
PWM_API_ESP32 m_pwm
float m_setPointValue
Additional Inherited Members
Protected Attributes inherited from Actuator_Base< mg996r_conf_t, float >
float m_value
mg996r_conf_t m_conf
Fault_Handler m_faulthanlder
internal faulthandler
Detailed Description
class for MG996R pwm driven servo motor
Attention
due to the servo motors internal parameters we are limited to a pwm duty cycle between 2.5% and 13%
 // initialize the motor config:
mg996r_conf_t conf = { "servo motor 1" {gpio_pin,duty_cycle,frequency,lcd_channel,speed_mode } };
MG996R m_servo{conf};
 // somewhere in the main function
for(;;)
{
 m_servo.execute(incremental_value);
}
Definition at line 101 of file MG996R.hpp.
Constructor & Destructor Documentation
MG996R()
MG996R::MG996R (const mg996r_conf_t & conf)
Definition at line 40 of file MG996R.cpp.
     : Actuator_Base(conf), m_pwm{conf.conf, "pwm"}, m_setPointValue{m_value}
 {
     // this is the only way to initialize m_value to a non-zero value
     // even though static analysis complains
     m_value = conf.conf.duty;
     m_setPointValue = m_value;
 }
References mg996r_conf_t::conf.
~MG996R()
MG996R::~MG996R ()
Definition at line 49 of file MG996R.cpp.
 {}
Member Function Documentation
actuate()
general_err_t MG996R::actuate (void) override private virtual
Purely virtual function for the derived class to define for it self.
Implements Actuator_Base< mg996r_conf_t, float >.
Definition at line 80 of file MG996R.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MG996R::actuate >> ");
 #endif
     // Executable code:
     auto err = m_pwm.setDutyCycle(m_setPointValue);
     if(err != GE_OK)
     {
         m_faulthanlder.handleFault({FaultHandler_n::severity::medium, " MG996R::actuate(void)",
                                     " error is : " + General_Error::errorToString(err)});
         return GE_FAIL;
     }
     // at this point we can assume that the set point value is equivalent to the m_value
     m_value = m_setPointValue;
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MG996R::actuate << ");
 #endif
     return GE_OK;
 }
References General_Error::errorToString(), GE_FAIL, GE_OK, Fault_Handler::handleFault(), LOG_PRINT_INFO, LOG_TAG, Actuator_Base< mg996r_conf_t, float >::m_faulthanlder, m_pwm, m_setPointValue, Actuator_Base< mg996r_conf_t, float >::m_value, FaultHandler_n::medium, and PWM_API_ESP32::setDutyCycle().
Referenced by setToMaximumSlowly(), and setToMinimumSlowly().
setPoint()
general_err_t MG996R::setPoint (const float & value) override private virtual
Setpoint function, the derived class is able to define its own function to accommodate fault handling
Attention
: no fault handling applied in the default function
Reimplemented from Actuator_Base< mg996r_conf_t, float >.
Definition at line 51 of file MG996R.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MG996R::setPoint >> ");
 #endif
     // Executable code:
     if(value > MAX_VALUE)
     {
         m_setPointValue = MAX_VALUE;
         return GE_UPPER_BOUNDERY;
     }
     if(value < MIN_VALUE)
     {
         m_setPointValue = MIN_VALUE;
         return GE_LOWER_BOUNDERY;
     }
     if(value == m_setPointValue)
     {
         return GE_NO_DATA;
     }
     m_setPointValue = value;
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MG996R::setPoint << ");
 #endif
     return GE_OK;
 }
References GE_LOWER_BOUNDERY, GE_NO_DATA, GE_OK, GE_UPPER_BOUNDERY, LOG_PRINT_INFO, LOG_TAG, m_setPointValue, MAX_VALUE, and MIN_VALUE.
Referenced by setToMaximumSlowly(), setToMinimumSlowly(), and TEST_GROUP().
setToMaximum()
general_err_t MG996R::setToMaximum (void) override virtual
Set the To Maximum value.
Returns
general_err_t
Implements Actuator_Base< mg996r_conf_t, float >.
Definition at line 103 of file MG996R.cpp.
 {
     return execute(MAX_VALUE);
 }
References Actuator_Base< mg996r_conf_t, float >::execute(), and MAX_VALUE.
setToMaximumSlowly()
general_err_t MG996R::setToMaximumSlowly (void)
Set the To Maximum Slowly value.
Attention
the function is executing with a velocity of ~1sec
Returns
general_err_t
Definition at line 113 of file MG996R.cpp.
 {
     general_err_t err = GE_OK;
     do
     {
         float tick = getValue() + SLOW_INCREMENT;
         err = setPoint(tick);
         if(err == GE_NO_DATA)
         {
             return err;
         }
         err = actuate();
         Timeservice::wait_ms(SLOW_DELAY);
     } while(getValue() < MAX_VALUE && err == GE_OK);
     return err;
 }
References actuate(), GE_NO_DATA, GE_OK, Actuator_Base< mg996r_conf_t, float >::getValue(), MAX_VALUE, setPoint(), SLOW_DELAY, SLOW_INCREMENT, and Timeservice::wait_ms().
Referenced by DogFeederDoor::open().
setToMinimum()
general_err_t MG996R::setToMinimum (void) override virtual
Set the To Minimum value.
Returns
general_err_t
Implements Actuator_Base< mg996r_conf_t, float >.
Definition at line 108 of file MG996R.cpp.
 {
     return execute(MIN_VALUE);
 }
References Actuator_Base< mg996r_conf_t, float >::execute(), and MIN_VALUE.
setToMinimumSlowly()
general_err_t MG996R::setToMinimumSlowly (void)
Set the To Minimum Slowly value.
Attention
the function is executing with a velocity of ~1sec
Returns
general_err_t
Definition at line 130 of file MG996R.cpp.
 {
     general_err_t err = GE_OK;
     do
     {
         float tick = getValue() - SLOW_INCREMENT;
         err = setPoint(tick);
         if(err == GE_NO_DATA)
         {
             return err;
         }
         err = actuate();
         Timeservice::wait_ms(SLOW_DELAY);
     } while(getValue() > MIN_VALUE && err == GE_OK);
     return err;
 }
References actuate(), GE_NO_DATA, GE_OK, Actuator_Base< mg996r_conf_t, float >::getValue(), MIN_VALUE, setPoint(), SLOW_DELAY, SLOW_INCREMENT, and Timeservice::wait_ms().
Referenced by DogFeederDoor::close().
Member Data Documentation
m_pwm
PWM_API_ESP32 MG996R::m_pwm private
Definition at line 137 of file MG996R.hpp.
Referenced by actuate().
m_setPointValue
float MG996R::m_setPointValue private
Definition at line 138 of file MG996R.hpp.
Referenced by actuate(), and setPoint().
The documentation for this class was generated from the following files:
Components/Actuator/ServoMotor/include/MG996R.hpp
Components/Actuator/ServoMotor/src/MG996R.cpp