Embedded Library: postgresql_interface Class Reference
postgresql_interface Class Reference final
#include <postgresql_interface.hpp>
Public Member Functions
postgresql_interface ()=default
~postgresql_interface ()
general_err_t open (void) override
general_err_t post (const std::string &str) override
general_err_t close (void) override
Public Member Functions inherited from ProtocolBase
ProtocolBase ()
virtual ~ProtocolBase ()
auto & getResponse ()
Private Attributes
bool m_open = false
Detailed Description
Definition at line 79 of file postgresql_interface.hpp.
Constructor & Destructor Documentation
postgresql_interface()
postgresql_interface::postgresql_interface () default
~postgresql_interface()
postgresql_interface::~postgresql_interface ()
Definition at line 43 of file postgresql_interface.cpp.
 {}
Member Function Documentation
close()
general_err_t postgresql_interface::close (void) override virtual
Implements ProtocolBase.
Definition at line 117 of file postgresql_interface.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> postgresql_interface::close >> ");
 #endif
     // Executable code:
     m_open = false;
 #ifdef __RPI__
 #ifdef __WITH_DATABASE__
     try
     {
         m_connect.close();
     }
     catch(const std::exception& e)
     {
         std::cerr << e.what() << std::endl;
         return GE_FAIL;
     }
 #endif
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< postgresql_interface::close << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, LOG_PRINT_INFO, LOG_TAG, and m_open.
Referenced by post().
open()
general_err_t postgresql_interface::open (void) override virtual
Implements ProtocolBase.
Definition at line 45 of file postgresql_interface.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> postgresql_interface::open >> ");
 #endif
     // Executable code:
 #ifdef __RPI__
 #ifdef __WITH_DATABASE__
     try
     {
         m_connect = pqxx::connection("dbname = sensordb user = write2db password = 1234 \
             hostaddr = 192.168.1.157 port = 5432");
     }
     catch(const std::exception& e)
     {
         std::cerr << e.what() << std::endl;
         return GE_FAIL;
     }
 #endif
 #endif
     m_open = true;
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< postgresql_interface::open << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, LOG_PRINT_INFO, LOG_TAG, and m_open.
Referenced by post().
post()
general_err_t postgresql_interface::post (const std::string & str) override virtual
Implements ProtocolBase.
Definition at line 74 of file postgresql_interface.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> postgresql_interface::close >> ");
 #endif
     // Executable code:
     std::cout << " sql querey : " << str << "\n";
 #ifdef __RPI__
 #ifdef __WITH_DATABASE__
     try
     {
         if(!m_connect.is_open())
         {
             std::cout << "Can't open database" << std::endl;
             // firstly lets close it correctly:
             close();
             // we will try to open the database, and see if we are ready next time
             open();
             return GE_NOT_CONNECTED;
         }
         /* Create a transactional object. */
         pqxx::work W(m_connect);
         /* Execute SQL query */
         W.exec(str.c_str());
         W.commit();
     }
     catch(const std::exception& e)
     {
         std::cerr << e.what() << std::endl;
         return GE_FAIL;
     }
 #endif
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< postgresql_interface::close << ");
 #endif
     return GE_OK;
 }
References close(), GE_FAIL, GE_NOT_CONNECTED, GE_OK, LOG_PRINT_INFO, LOG_TAG, and open().
Member Data Documentation
m_open
bool postgresql_interface::m_open = false private
Definition at line 93 of file postgresql_interface.hpp.
Referenced by close(), and open().
The documentation for this class was generated from the following files:
Components/Protocols/HTTP/include/postgresql_interface.hpp
Components/Protocols/HTTP/src/postgresql_interface.cpp