Embedded Library: DataBroker Class Reference
DataBroker Class Reference final
#include <DataBroker.hpp>
Public Member Functions
DataBroker (const size_t delay_ms, SensorControllerBase &sensor)
~DataBroker ()
general_err_t addService (ServiceBase< MQTT_Message > *service)
const MQTT_Message & getSafeBuffer ()
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Private Member Functions
void run (void *data) override
Body of the task to execute.
general_err_t main_function ()
Private Attributes
const size_t m_delay_ms
SensorControllerBase & m_sensor
std::vector< ServiceBase< MQTT_Message > * > m_service_array
Detailed Description
Definition at line 53 of file DataBroker.hpp.
Constructor & Destructor Documentation
DataBroker()
DataBroker::DataBroker (const size_t delay_ms, SensorControllerBase & sensor) inline
Definition at line 59 of file DataBroker.hpp.
         : m_delay_ms{delay_ms}, m_sensor{sensor} {};
~DataBroker()
DataBroker::~DataBroker () inline
Definition at line 61 of file DataBroker.hpp.
 {};
Member Function Documentation
addService()
general_err_t DataBroker::addService (ServiceBase< MQTT_Message > * service)
Definition at line 30 of file DataBroker.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> DataBroker::fcn >> ");
 #endif
     m_service_array.push_back(service);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  DataBroker::fcn << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, LOG_TAG, and m_service_array.
getSafeBuffer()
const MQTT_Message& DataBroker::getSafeBuffer () inline
Definition at line 63 of file DataBroker.hpp.
     {
         return m_sensor.getSafeBuffer();
     }
References SensorControllerBase::getSafeBuffer(), and m_sensor.
main_function()
general_err_t DataBroker::main_function () private
check all the available flags to see if any of the services are in use. If they are in use, wait 500ms and poll again
we are assuming that we will hit a break at some point.
Definition at line 45 of file DataBroker.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> DataBroker::fcn >> ");
 #endif
     if(m_sensor.isDataReady())
     {
         // auto& buffer = m_sensor.getSafeBuffer();
         std::atomic<size_t> inUseCoder;
         inUseCoder = 0xdeadbeef; // reset
         std::for_each(m_service_array.begin(), m_service_array.end(),
                       [&inUseCoder](ServiceBase<MQTT_Message>* ele) {
                           ele->getQueue().send(&inUseCoder, QUEUE_SEND_MAX_TIMOUT);
                       });
         bool isActive = false;
         do
         {
             isActive = false;
             std::for_each(m_service_array.begin(), m_service_array.end(),
                           [&isActive](ServiceBase<MQTT_Message>* ele) {
                               if(ele->isActive())
{
                                   isActive = true;
                               }
                           });
             Timeservice::wait_ms(500);
         } while(isActive);
         // just collected the data
         m_sensor.setDataReady(false);
         return GE_OK;
     }
     /*
      *  we want to set the WantData flag to
      *  true here, in order to get new data
      */
     m_sensor.setWantDataTrue();
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  DataBroker::fcn << ");
 #endif
     return GE_NO_DATA;
 }
References GE_OK, SensorControllerBase::isDataReady(), LOG_PRINT_INFO, LOG_TAG, m_sensor, m_service_array, SensorControllerBase::setDataReady(), and Timeservice::wait_ms().
Referenced by run().
run()
void DataBroker::run (void * data) override private virtual
Body of the task to execute.
This function must be implemented in the subclass that represents the actual task to run. When a task is started by calling start(), this is the code that is executed in the newly created task. WHY IS IT NOT PRIVATE???
Parameters
[in] data The data passed in to the newly started task.
Implements Task.
Definition at line 98 of file DataBroker.cpp.
 {
     for(;;)
     {
         main_function();
         Timeservice::wait_ms(m_delay_ms);
     }
 }
References m_delay_ms, main_function(), and Timeservice::wait_ms().
Member Data Documentation
m_delay_ms
const size_t DataBroker::m_delay_ms private
Definition at line 71 of file DataBroker.hpp.
Referenced by run().
m_sensor
SensorControllerBase& DataBroker::m_sensor private
Definition at line 72 of file DataBroker.hpp.
Referenced by getSafeBuffer(), and main_function().
m_service_array
std::vector<ServiceBase<MQTT_Message>*> DataBroker::m_service_array private
Definition at line 73 of file DataBroker.hpp.
Referenced by addService(), and main_function().
The documentation for this class was generated from the following files:
Components/Objects/DataBroker/include/DataBroker.hpp
Components/Objects/DataBroker/src/DataBroker.cpp