Embedded Library: Logger Class Reference
Logger Class Reference
#include <Logger.hpp>
Classes
struct msg_t
Static Public Member Functions
static general_err_t write (const msg_t &msg)
Detailed Description
Definition at line 100 of file Logger.hpp.
Class Documentation
Logger::msg_t
struct Logger::msg_t
Definition at line 106 of file Logger.hpp.
Class Members
general_err_t error_code
string msg
general_resp_t respons_code
Member Function Documentation
write()
general_err_t Logger::write (const msg_t & msg) static
Definition at line 36 of file Logger.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Logger::write >> ");
 #endif
     // Executable code:
     if(msg.msg.empty())
     {
         return GE_NO_DATA;
     }
     // construct the message:
     std::string str;
     str.append("[");
     str.append(std::to_string((long long int)Timeservice::getTimeNow()));
     str.append("] [");
     str.append(PROJECT_NAME);
     str.append("] [");
     str.append(General_Error::errorToString(msg.error_code));
     str.append("] [");
     str.append(General_Error::responseToString(msg.respons_code));
     str.append("] [");
     str.append(msg.msg);
     str.append("]");
     hal::write(str);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Logger::write << ");
 #endif
     return GE_OK;
 }
References Logger::msg_t::error_code, General_Error::errorToString(), GE_NO_DATA, GE_OK, Timeservice::getTimeNow(), LOG_PRINT_INFO, LOG_TAG, Logger::msg_t::msg, PROJECT_NAME, Logger::msg_t::respons_code, and General_Error::responseToString().
Referenced by MQTT_Message::construct(), Fault_Handler::handle(), and TEST().
The documentation for this class was generated from the following files:
Components/Objects/Logger/include/Logger.hpp
Components/Objects/Logger/src/Logger.cpp