Embedded Library: Components/Objects/Maintainer/test/test/maintainer_test.cpp File Reference
maintainer_test.cpp File Reference
#include "../../include/Maintainer.hpp"
#include <iostream>
#include "CppUTest/TestHarness.h"
Functions
TEST_GROUP (MAINTAINER_GRP)
bool good_test (void)
bool bad_test (void)
TEST (MAINTAINER_GRP, init)
bool good_test2 (void)
TEST (MAINTAINER_GRP, init2)
Function Documentation
bad_test()
bool bad_test (void)
Definition at line 29 of file maintainer_test.cpp.
 {
     return false;
 }
Referenced by TEST().
good_test()
bool good_test (void)
Definition at line 25 of file maintainer_test.cpp.
 {
     return true;
 }
Referenced by good_test2(), and TEST().
good_test2()
bool good_test2 (void)
Definition at line 41 of file maintainer_test.cpp.
 {
     std::cout << " testing some important functionality .... \n";
     return good_test();
 }
References good_test().
Referenced by TEST().
TEST() [1/2]
TEST (MAINTAINER_GRP , init)
Definition at line 34 of file maintainer_test.cpp.
 {
     Maintainer::install_system_test_fuction(good_test);
     Maintainer::install_system_test_fuction(bad_test);
     CHECK_EQUAL(GE_FAIL, m_friend.check_sys());
 }
References bad_test(), GE_FAIL, good_test(), and Maintainer::install_system_test_fuction().
TEST() [2/2]
TEST (MAINTAINER_GRP , init2)
Definition at line 47 of file maintainer_test.cpp.
 {
     Maintainer::install_system_test_fuction(good_test2);
     CHECK_EQUAL(GE_OK, m_friend.check_sys());
 }
References GE_OK, good_test2(), and Maintainer::install_system_test_fuction().
TEST_GROUP()
TEST_GROUP (MAINTAINER_GRP)
Definition at line 14 of file maintainer_test.cpp.
 {
     Maintainer m_maintainer{{}, db_id::DEBUG_ID1};
     friend_Maintainer m_friend{&m_maintainer};
     void setup() {}
     void teardown()
     {
         // Uninit stuff
     }
 };
References DEBUG_ID1.