Embedded Library: i2c< i2c_class > Class Template Reference
i2c< i2c_class > Class Template Reference
#include <i2c.hpp>
Public Member Functions
~i2c ()
general_err_t writeByte (const uint8_t &slave_address, const uint8_t &byte)
template<size_t N>
general_err_t writeMultiBytes (const uint8_t &slave_address, const std::array< uint8_t, N > &array)
template<size_t N>
general_err_t readMultiBytes (const uint8_t &slave_address, std::array< uint8_t, N > &array)
general_err_t writeWord (const uint8_t &slave_address, const uint16_t &word)
uint8_t readByte (const uint8_t &slave_address)
uint16_t readWord (const uint8_t &slave_address)
void scan ()
Scan Scan the whole range and print out if any device is attached to the i2c channel.
bool slavePresent (const uint8_t &slave_address)
Static Public Member Functions
static i2c & getInstance (const i2c_conf_t &conf)
Get the Instance object TODO Make sure that users can re-install with new config file Currently we can pnly install it once.
Private Member Functions
i2c (const i2c_conf_t &conf)
std::array< uint8_t, 2 > word2bytes (const uint16_t &data)
uint16_t bytes2word (const std::array< uint8_t, 2 > &arr)
Private Attributes
i2c_conf_t m_conf
i2c_class m_hal
Detailed Description
template<typename i2c_class>
class i2c< i2c_class >
Definition at line 45 of file i2c.hpp.
Constructor & Destructor Documentation
~i2c()
template<typename i2c_class > i2c< i2c_class >::~i2c () inline
Definition at line 63 of file i2c.hpp.
 {};
i2c()
template<typename i2c_class > i2c< i2c_class >::i2c (const i2c_conf_t & conf) inline private
Definition at line 130 of file i2c.hpp.
 : m_hal{conf} {};
References conf.
Member Function Documentation
bytes2word()
template<typename i2c_class > uint16_t i2c< i2c_class >::bytes2word (const std::array< uint8_t, 2 > & arr) inline private
Definition at line 137 of file i2c.hpp.
     {
         return static_cast<uint16_t>((arr[0] * 256) + arr[1]);
     }
Referenced by i2c< i2c_class >::readWord().
getInstance()
template<typename i2c_class > static i2c& i2c< i2c_class >::getInstance (const i2c_conf_t & conf) inline static
Get the Instance object TODO Make sure that users can re-install with new config file Currently we can pnly install it once.
Parameters
conf
Returns
i2c&
Definition at line 58 of file i2c.hpp.
     {
         static i2c ref_to_i2c{conf};
         return ref_to_i2c;
     }
References conf.
Referenced by TEST(), and TEST_GROUP().
readByte()
template<typename i2c_class > uint8_t i2c< i2c_class >::readByte (const uint8_t & slave_address) inline
Definition at line 86 of file i2c.hpp.
     {
         return m_hal.readByte(slave_address);
     };
References i2c< i2c_class >::m_hal.
readMultiBytes()
template<typename i2c_class > template<size_t N> general_err_t i2c< i2c_class >::readMultiBytes (const uint8_t & slave_address, std::array< uint8_t, N > & array) inline
Definition at line 76 of file i2c.hpp.
     {
         return m_hal.readMultiBytes(slave_address, array.data(), array.size());
     }
References i2c< i2c_class >::m_hal.
readWord()
template<typename i2c_class > uint16_t i2c< i2c_class >::readWord (const uint8_t & slave_address) inline
Definition at line 90 of file i2c.hpp.
     {
         std::array<uint8_t, 2> arr;
         readMultiBytes<2>(slave_address, arr);
         return bytes2word(arr);
     }
References i2c< i2c_class >::bytes2word().
scan()
template<typename i2c_class > void i2c< i2c_class >::scan () inline
Scan Scan the whole range and print out if any device is attached to the i2c channel.
Definition at line 102 of file i2c.hpp.
     {
         printf("Data Pin: %d, Clock Pin: %d\n", m_conf.pin_sda, m_conf.pin_sclk);
         printf("     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f\n");
         printf("00:         ");
         for(uint8_t i = 0; i < 0x78; i++)
         {
             if(i % 16 == 0)
             {
                 printf("\n%.2x:", i);
             }
             if(slavePresent(i))
             {
                 printf(" %.2x", i);
             }
             else
             {
                 printf(" --");
             }
         }
         printf("\n");
     };
References i2c< i2c_class >::m_conf, i2c_conf_t::pin_sclk, i2c_conf_t::pin_sda, and i2c< i2c_class >::slavePresent().
slavePresent()
template<typename i2c_class > bool i2c< i2c_class >::slavePresent (const uint8_t & slave_address) inline
Definition at line 124 of file i2c.hpp.
     {
         return m_hal.slavePresent(slave_address);
     };
References i2c< i2c_class >::m_hal.
Referenced by i2c< i2c_class >::scan().
word2bytes()
template<typename i2c_class > std::array<uint8_t, 2> i2c< i2c_class >::word2bytes (const uint16_t & data) inline private
Definition at line 132 of file i2c.hpp.
     {
         return {static_cast<uint8_t>(data >> 8 & 0xff), static_cast<uint8_t>(data & 0xff)};
     }
Referenced by i2c< i2c_class >::writeWord().
writeByte()
template<typename i2c_class > general_err_t i2c< i2c_class >::writeByte (const uint8_t & slave_address, const uint8_t & byte) inline
Definition at line 64 of file i2c.hpp.
     {
         return m_hal.writeByte(slave_address, byte);
     }
References i2c< i2c_class >::m_hal.
writeMultiBytes()
template<typename i2c_class > template<size_t N> general_err_t i2c< i2c_class >::writeMultiBytes (const uint8_t & slave_address, const std::array< uint8_t, N > & array) inline
Definition at line 70 of file i2c.hpp.
     {
         return m_hal.writeMultiBytes(slave_address, array.data(), array.size());
     }
References i2c< i2c_class >::m_hal.
writeWord()
template<typename i2c_class > general_err_t i2c< i2c_class >::writeWord (const uint8_t & slave_address, const uint16_t & word) inline
Definition at line 81 of file i2c.hpp.
     {
         auto arr = word2bytes(word);
         return writeMultiBytes<2>(slave_address, arr);
     }
References i2c< i2c_class >::word2bytes().
Member Data Documentation
m_conf
template<typename i2c_class > i2c_conf_t i2c< i2c_class >::m_conf private
Definition at line 142 of file i2c.hpp.
Referenced by i2c< i2c_class >::scan().
m_hal
template<typename i2c_class > i2c_class i2c< i2c_class >::m_hal private
Definition at line 143 of file i2c.hpp.
Referenced by i2c< i2c_class >::readByte(), i2c< i2c_class >::readMultiBytes(), i2c< i2c_class >::slavePresent(), i2c< i2c_class >::writeByte(), and i2c< i2c_class >::writeMultiBytes().
The documentation for this class was generated from the following file:
Components/Protocols/I2C/include/i2c.hpp