Embedded Library: ServiceBase< BUFFER_TYPE, QUEUE_TYPE > Class Template Reference
ServiceBase< BUFFER_TYPE, QUEUE_TYPE > Class Template Reference abstract
#include <ServiceBase.hpp>
Public Member Functions
ServiceBase (size_t queue_size, size_t size_of_item, const BUFFER_TYPE &buffer, const db_id error_id)
virtual ~ServiceBase ()
const auto & isActive () const
auto & getQueue ()
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Protected Member Functions
virtual general_err_t mainFunction ()=0
Main function for the derived class to work in It is expected that the function is a single-run function And that it should not be blocking.
virtual void setIsActive (bool isActive)
Set the Is Active object.
general_err_t postData (const MQTT_Message &message, const std::string &topic="mqtt/burst_msg")
Function to post data to database.
void run (void *data) override
loop for the service We are waiting "forever" on a queue recieve When we recieve something we will call the mainFunction() Which should be a single-end run for the derived class if any error happends it will be reported online.
Protected Attributes
QUEUE_TYPE m_queue
GPIO_API m_test_pin
const BUFFER_TYPE & m_buffer
Private Attributes
std::atomic< bool > m_isActive
mqtt_api_v2 m_mqtt
db_id m_error_id
Detailed Description
template<typename BUFFER_TYPE, typename QUEUE_TYPE = FreeRTOS::Queue>
class ServiceBase< BUFFER_TYPE, QUEUE_TYPE >
Definition at line 60 of file ServiceBase.hpp.
Constructor & Destructor Documentation
ServiceBase()
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::ServiceBase (size_t queue_size, size_t size_of_item, const BUFFER_TYPE & buffer, const db_id error_id) inline
Definition at line 66 of file ServiceBase.hpp.
         : m_queue{queue_size, size_of_item}, m_test_pin{}, m_buffer{buffer}, m_isActive{false},
           m_error_id{error_id} {};
~ServiceBase()
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> virtual ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::~ServiceBase () inline virtual
Definition at line 70 of file ServiceBase.hpp.
 {};
Member Function Documentation
getQueue()
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> auto& ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::getQueue () inline
Definition at line 75 of file ServiceBase.hpp.
     {
         return m_queue;
     }
isActive()
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> const auto& ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::isActive () const inline
Definition at line 71 of file ServiceBase.hpp.
     {
         return m_isActive;
     }
Referenced by ServiceBase< MQTT_Message >::setIsActive().
mainFunction()
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> virtual general_err_t ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::mainFunction () protected pure virtual
Main function for the derived class to work in It is expected that the function is a single-run function And that it should not be blocking.
Returns
general_err_t
Implemented in WaterEstimator_Service.
Referenced by ServiceBase< MQTT_Message >::run().
postData()
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> general_err_t ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::postData (const MQTT_Message & message, const std::string & topic = "mqtt/burst_msg") inline protected
Function to post data to database.
Parameters
message
topic
Returns
general_err_t
Definition at line 106 of file ServiceBase.hpp.
     {
         // post only if data is available
         if(message.getBufferSize() > 0)
         {
             return m_mqtt.publish(topic, message.toString());
         }
         else
         {
             return GE_NO_DATA;
         }
     }
run()
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> void ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::run (void * data) inline override protected virtual
loop for the service We are waiting "forever" on a queue recieve When we recieve something we will call the mainFunction() Which should be a single-end run for the derived class if any error happends it will be reported online.
Parameters
data N/A
Implements Task.
Definition at line 128 of file ServiceBase.hpp.
     {
         size_t recived;
         constexpr size_t WAIT_FOREVER = (10000000UL);
         for(;;)
         {
             if(m_queue.recieve(&recived, WAIT_FOREVER))
             {
                 // if the queue returns 1 it means some error happend
                 // most likely the wait-time has passed.
                 // we will simply just skip the loop.
                 continue;
             }
             setIsActive(true);
             auto err = mainFunction();
             {
                 if(err != GE_OK)
                 {
                     ErrorCodeParser::postToMqtt(
                         m_error_id, err, "Some error happend in the execution of main function");
                 }
             }
             setIsActive(false);
         }
     }
setIsActive()
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> virtual void ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::setIsActive (bool isActive) inline protected virtual
Set the Is Active object.
Parameters
isActive
Reimplemented in ServiceBase_HW_TEST< BUFFER_TYPE, QUEUE_TYPE >.
Definition at line 95 of file ServiceBase.hpp.
     {
         m_isActive = isActive;
     }
Referenced by ServiceBase< MQTT_Message >::run(), and ServiceBase_HW_TEST< BUFFER_TYPE, QUEUE_TYPE >::setIsActive().
Member Data Documentation
m_buffer
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> const BUFFER_TYPE& ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::m_buffer protected
Definition at line 157 of file ServiceBase.hpp.
m_error_id
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> db_id ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::m_error_id private
Definition at line 163 of file ServiceBase.hpp.
Referenced by ServiceBase< MQTT_Message >::run().
m_isActive
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> std::atomic<bool> ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::m_isActive private
Definition at line 160 of file ServiceBase.hpp.
Referenced by ServiceBase< MQTT_Message >::isActive(), and ServiceBase< MQTT_Message >::setIsActive().
m_mqtt
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> mqtt_api_v2 ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::m_mqtt private
Definition at line 162 of file ServiceBase.hpp.
Referenced by ServiceBase< MQTT_Message >::postData().
m_queue
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> QUEUE_TYPE ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::m_queue protected
Definition at line 155 of file ServiceBase.hpp.
Referenced by ServiceBase< MQTT_Message >::getQueue(), and ServiceBase< MQTT_Message >::run().
m_test_pin
template<typename BUFFER_TYPE , typename QUEUE_TYPE = FreeRTOS::Queue> GPIO_API ServiceBase< BUFFER_TYPE, QUEUE_TYPE >::m_test_pin protected
Definition at line 156 of file ServiceBase.hpp.
The documentation for this class was generated from the following file:
Components/Interfaces/ServiceBase/include/ServiceBase.hpp