Embedded Library: NVS_esp32 Class Reference
NVS_esp32 Class Reference
#include <NVS_esp32.hpp>
Static Public Member Functions
static const uint64_t read_u64 (const std::string &key)
static general_err_t write_u64 (const std::string &key, const uint64_t &value)
Static Private Member Functions
static general_err_t initialize ()
Detailed Description
Definition at line 52 of file NVS_esp32.hpp.
Member Function Documentation
initialize()
general_err_t NVS_esp32::initialize () static private
Definition at line 30 of file NVS_esp32.cpp.
 {
     general_err_t gen_err = GE_OK;
 #ifdef __ESP32__
     esp_err_t err = nvs_flash_init();
     if(err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND)
     {
         // NVS partition was truncated and needs to be erased
         // Retry nvs_flash_init
         ESP_ERROR_CHECK(nvs_flash_erase());
         err = nvs_flash_init();
     }
     if(err != ESP_OK)
     {
         gen_err = GE_FAIL;
     }
 #endif
     return gen_err;
 }
References GE_FAIL, and GE_OK.
Referenced by read_u64(), and write_u64().
read_u64()
const uint64_t NVS_esp32::read_u64 (const std::string & key) static
Definition at line 50 of file NVS_esp32.cpp.
 {
     if(!isInitialized)
     {
         if(initialize() == GE_OK)
         {
             isInitialized = true;
         }
         else
         {
             exit(1);
         }
     }
     uint64_t value = 0; // value will default to 0, if not set yet in NVS
 #ifdef __ESP32__
     nvs_handle_t my_handle;
     nvs_open("storage", NVS_READWRITE, &my_handle);
     nvs_get_u64(my_handle, key.c_str(), &value);
     // Close
     nvs_close(my_handle);
 #endif
     return value;
 }
References GE_OK, initialize(), and isInitialized.
write_u64()
general_err_t NVS_esp32::write_u64 (const std::string & key, const uint64_t & value) static
Definition at line 74 of file NVS_esp32.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> NVS_esp32::fcn >> ");
 #endif
     // Executable code:
     if(!isInitialized)
     {
         if(initialize() == GE_OK)
         {
             isInitialized = true;
         }
         else
         {
             exit(1);
         }
     }
 #ifdef __ESP32__
     nvs_handle_t my_handle;
     nvs_open("storage", NVS_READWRITE, &my_handle);
     nvs_set_u64(my_handle, key.c_str(), value);
     nvs_commit(my_handle);
     // Close
     nvs_close(my_handle);
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  NVS_esp32::fcn << ");
 #endif
     return GE_OK;
 }
References GE_OK, initialize(), isInitialized, LOG_PRINT_INFO, and LOG_TAG.
The documentation for this class was generated from the following files:
Components/Objects/NonVolatileStorage/include/NVS_esp32.hpp
Components/Objects/NonVolatileStorage/src/NVS_esp32.cpp