Embedded Library: AM2320_Base Class Reference
AM2320_Base Class Reference abstract
#include <AM2320_Base.hpp>
Public Member Functions
AM2320_Base (const i2c_conf_t &conf, const uint8_t &slaveaddress)
virtual ~AM2320_Base ()
uint16_t getMeasurement ()
Get the Measurement object execution function to handle the i2c communication, convertion to SI and to return the actual value.
Protected Member Functions
virtual uint16_t getRaw ()=0
Get the Raw object get the raw i2c value.
uint16_t getSensorValue (const uint8_t &register_address)
Get the Sensor Value object get the i2c result from the given function code.
Protected Attributes
i2c< i2c_esp32 > m_i2c
const uint8_t m_address
const uint8_t FUNCTION_CODE_TEMPERATURE = 0x02
const uint8_t FUNCTION_CODE_HUMIDITY = 0x00
Private Member Functions
bool wakeUp ()
wake up the sensor
Detailed Description
Definition at line 52 of file AM2320_Base.hpp.
Constructor & Destructor Documentation
AM2320_Base()
AM2320_Base::AM2320_Base (const i2c_conf_t & conf, const uint8_t & slaveaddress)
Definition at line 29 of file AM2320_Base.cpp.
     : m_i2c{i2c<i2c_esp32>::getInstance(conf)}, m_address{slaveaddress}
 {
 }
References conf, and i2c< i2c_class >::getInstance().
~AM2320_Base()
AM2320_Base::~AM2320_Base () virtual
Definition at line 34 of file AM2320_Base.cpp.
 {}
Member Function Documentation
getMeasurement()
uint16_t AM2320_Base::getMeasurement ()
Get the Measurement object execution function to handle the i2c communication, convertion to SI and to return the actual value.
Attention
If return is 0 it means an error has occured
Returns
uint16_t
Definition at line 61 of file AM2320_Base.cpp.
 {
 #ifdef DEBUG
     std::cout << " >> AM2320_Base::getMeasurement >> \n";
 #endif
     if(!wakeUp())
     {
         std::cout << " could not wake up the sensor ... \n";
         return 0;
     }
     auto val = getRaw();
     return val;
 #ifdef DEBUG
     std::cout << " << AM2320_Base::getMeasurement << \n";
 #endif
     return GE_OK;
 }
References GE_OK, getRaw(), and wakeUp().
Referenced by EnvSensing_service::mainFunction(), and TEST().
getRaw()
virtual uint16_t AM2320_Base::getRaw () protected pure virtual
Get the Raw object get the raw i2c value.
Returns
uint16_t
Implemented in AM2320_Humidity, AM2320_Temperature, and AM2320_MOCK.
Referenced by getMeasurement().
getSensorValue()
uint16_t AM2320_Base::getSensorValue (const uint8_t & register_address) protected
Get the Sensor Value object get the i2c result from the given function code.
Returns
uint16_t
Definition at line 82 of file AM2320_Base.cpp.
 {
 #ifdef DEBUG
     std::cout << " >> AM2320_Base::getSensorValue >> \n";
 #endif
     // do magic
     m_i2c.writeMultiBytes<3>(m_address, {0x03, register_address, 2});
     Timeservice::wait_ms(10);
     std::array<uint8_t, 5> vec;
     m_i2c.readMultiBytes<5>(m_address, vec);
 #ifdef DEBUG
     std::cout << " << AM2320_Base::getSensorValue << \n";
 #endif
     return basic_utils::shift8BitTo16(vec.at(2), vec.at(3));
 }
References m_address, m_i2c, i2c< i2c_class >::readMultiBytes(), basic_utils::shift8BitTo16(), vec, Timeservice::wait_ms(), and i2c< i2c_class >::writeMultiBytes().
Referenced by AM2320_Humidity::getRaw(), and AM2320_Temperature::getRaw().
wakeUp()
bool AM2320_Base::wakeUp () private
wake up the sensor
Returns
true
false
Definition at line 36 of file AM2320_Base.cpp.
 {
 #ifdef DEBUG
     std::cout << " >> AM2320_Base::wakeUp >> \n";
 #endif
     // do magic
     constexpr uint8_t MAX_TRIES = 5;
     constexpr uint8_t DELAY_100ms = 100;
     uint8_t count = 0;
     bool res = false;
     do
     {
         res = m_i2c.slavePresent(m_address);
         Timeservice::wait_ms(DELAY_100ms);
     } while(!res and (++count) < MAX_TRIES);
 #ifdef DEBUG
     std::cout << " << AM2320_Base::wakeUp << \n";
 #endif
     return true;
 }
References m_address, m_i2c, i2c< i2c_class >::slavePresent(), and Timeservice::wait_ms().
Referenced by getMeasurement().
Member Data Documentation
FUNCTION_CODE_HUMIDITY
const uint8_t AM2320_Base::FUNCTION_CODE_HUMIDITY = 0x00 protected
Definition at line 74 of file AM2320_Base.hpp.
Referenced by AM2320_Humidity::getRaw().
FUNCTION_CODE_TEMPERATURE
const uint8_t AM2320_Base::FUNCTION_CODE_TEMPERATURE = 0x02 protected
Definition at line 73 of file AM2320_Base.hpp.
Referenced by AM2320_Temperature::getRaw().
m_address
const uint8_t AM2320_Base::m_address protected
Definition at line 71 of file AM2320_Base.hpp.
Referenced by getSensorValue(), and wakeUp().
m_i2c
i2c<i2c_esp32> AM2320_Base::m_i2c protected
Definition at line 70 of file AM2320_Base.hpp.
Referenced by getSensorValue(), and wakeUp().
The documentation for this class was generated from the following files:
Components/Sensor/AM2320/include/AM2320_Base.hpp
Components/Sensor/AM2320/src/AM2320_Base.cpp