Embedded Library: DistanceSensorController Class Reference
DistanceSensorController Class Reference final
#include <DistanceSensorController.hpp>
Classes
struct config
Public Member Functions
DistanceSensorController (const DistanceSensorController::config &conf)
~DistanceSensorController ()
Public Member Functions inherited from SensorControllerBase
SensorControllerBase (const init_conf &conf)
virtual ~SensorControllerBase ()
void setWantDataTrue ()
const auto & getSafeBuffer ()
const bool isDataReady ()
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Private Member Functions
general_err_t main_function () override
general_err_t updateInternalBuffer ()
Private Attributes
const uint64_t m_time_between_adc_measurements
ADC_API_ESP32 m_adc
Additional Inherited Members
Protected Member Functions inherited from SensorControllerBase
void setDataReadyTrue ()
general_err_t postData (const MQTT_Message &message, const std::string &topic="mqtt/burst_msg")
void postError (const general_err_t &err, const std::string &error_message)
Protected Attributes inherited from SensorControllerBase
MQTT_Message m_buffer_raw
MQTT_Message m_buffer_external
std::atomic< bool > m_want_data_flag
std::atomic< bool > m_data_ready_flag
const uint64_t m_delay
const db_id m_error_id
Detailed Description
Definition at line 48 of file DistanceSensorController.hpp.
Class Documentation
DistanceSensorController::config
struct DistanceSensorController::config
Definition at line 54 of file DistanceSensorController.hpp.
Class Members
config adc_conf
init_conf init_conf
const uint64_t time_between_adc_measurements
Constructor & Destructor Documentation
DistanceSensorController()
DistanceSensorController::DistanceSensorController (const DistanceSensorController::config & conf) inline
Definition at line 60 of file DistanceSensorController.hpp.
         : SensorControllerBase{conf.init_conf},
           m_time_between_adc_measurements{conf.time_between_adc_measurements},
           m_adc{conf.adc_conf} {};
References DistanceSensorController::config::init_conf.
~DistanceSensorController()
DistanceSensorController::~DistanceSensorController () inline
Definition at line 64 of file DistanceSensorController.hpp.
 {};
Member Function Documentation
main_function()
general_err_t DistanceSensorController::main_function () override private virtual
Implements SensorControllerBase.
Definition at line 29 of file DistanceSensorController.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> DistanceSensorController::fcn >> ");
 #endif
     // Executable code:
     m_buffer_raw.clear(); // make sure it is cleared
     for(size_t i = 0; i < m_buffer_raw.getMaxAllowedBufferSize(); i++)
     {
         m_buffer_raw.addData(Timeservice::getTimeNow(), m_adc.measureValue());
         Timeservice::wait_ms(m_time_between_adc_measurements);
     }
     auto err = postData(m_buffer_raw);
     updateInternalBuffer();
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  DistanceSensorController::fcn << ");
 #endif
     return err;
 }
References MQTT_Message::addData(), MQTT_Message::clear(), MQTT_Message::getMaxAllowedBufferSize(), Timeservice::getTimeNow(), LOG_PRINT_INFO, LOG_TAG, m_adc, SensorControllerBase::m_buffer_raw, m_time_between_adc_measurements, ADC_API_ESP32::measureValue(), SensorControllerBase::postData(), updateInternalBuffer(), and Timeservice::wait_ms().
updateInternalBuffer()
general_err_t DistanceSensorController::updateInternalBuffer () private
Definition at line 51 of file DistanceSensorController.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> DistanceSensorController::fcn >> ");
 #endif
     // Executable code:
     if(m_data_ready_flag)
     {
         // nothing to be done
         return GE_OK;
     }
     if(!m_want_data_flag)
     {
         // nothing to be done
         return GE_OK;
     }
     // m_buffer_external = m_buffer_raw;
     auto err = m_buffer_raw.copyTo(m_buffer_external);
     if(err != GE_OK)
     {
         return err;
     }
     setDataReadyTrue();
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  DistanceSensorController::fcn << ");
 #endif
     return GE_OK;
 }
References MQTT_Message::copyTo(), GE_OK, LOG_PRINT_INFO, LOG_TAG, SensorControllerBase::m_buffer_external, SensorControllerBase::m_buffer_raw, SensorControllerBase::m_data_ready_flag, SensorControllerBase::m_want_data_flag, and SensorControllerBase::setDataReadyTrue().
Referenced by main_function().
Member Data Documentation
m_adc
ADC_API_ESP32 DistanceSensorController::m_adc private
Definition at line 70 of file DistanceSensorController.hpp.
Referenced by main_function().
m_time_between_adc_measurements
const uint64_t DistanceSensorController::m_time_between_adc_measurements private
Definition at line 69 of file DistanceSensorController.hpp.
Referenced by main_function().
The documentation for this class was generated from the following files:
Components/Controller/DistanceSensorController/include/DistanceSensorController.hpp
Components/Controller/DistanceSensorController/src/DistanceSensorController.cpp