Embedded Library: Components/Protocols/MQTT/src/mqtt_api_v2.cpp File Reference
mqtt_api_v2.cpp File Reference
#include "../include/mqtt_api_v2.hpp"
Variables
static bool m_isSubscribed {false}
static std::atomic< bool > m_inUse {false}
static std::atomic< bool > m_connected {false}
static std::atomic< bool > m_initialized {false}
static FreeRTOS::Semaphore m_semaphore = FreeRTOS::Semaphore("mqtt_publish")
static FreeRTOS::Semaphore m_semaphore_subscribe = FreeRTOS::Semaphore("mqtt_subscribe")
static std::string m_data_recieved {""}
mqttclient m_client
static std::map< std::string, general_err_t(*)(const char *data, const size_t data_length)> mqtt_subscriber_pointer_map
Variable Documentation
m_client
mqttclient m_client
Definition at line 37 of file mqtt_api_v2.cpp.
Referenced by mqtt_api_v2::connect(), esp32_http_sal::get(), esp32_http_sal::post(), mqtt_api_v2::publish(), and mqtt_api_v2::subscribe().
m_connected
std::atomic<bool> m_connected {false} static
Definition at line 31 of file mqtt_api_v2.cpp.
Referenced by mqtt_api_v2::connect(), mqtt_api_v2::getData(), and mqtt_api_v2::publish().
m_data_recieved
std::string m_data_recieved {""} static
Definition at line 35 of file mqtt_api_v2.cpp.
Referenced by mqtt_api_v2::getData().
m_initialized
std::atomic<bool> m_initialized {false} static
Definition at line 32 of file mqtt_api_v2.cpp.
m_inUse
std::atomic<bool> m_inUse {false} static
Definition at line 30 of file mqtt_api_v2.cpp.
m_isSubscribed
bool m_isSubscribed {false} static
Definition at line 29 of file mqtt_api_v2.cpp.
Referenced by mqtt_api_v2::getData(), and mqtt_api_v2::subscribe().
m_semaphore
FreeRTOS::Semaphore m_semaphore = FreeRTOS::Semaphore("mqtt_publish") static
Definition at line 33 of file mqtt_api_v2.cpp.
Referenced by FreeRTOS::Semaphore::give(), FreeRTOS::Semaphore::giveFromISR(), mqtt_api_v2::publish(), FreeRTOS::Semaphore::take(), FreeRTOS::Semaphore::toString(), and FreeRTOS::Semaphore::~Semaphore().
m_semaphore_subscribe
FreeRTOS::Semaphore m_semaphore_subscribe = FreeRTOS::Semaphore("mqtt_subscribe") static
Definition at line 34 of file mqtt_api_v2.cpp.
Referenced by mqtt_api_v2::getData(), and mqtt_api_v2::subscribe().
mqtt_subscriber_pointer_map
std::map<std::string, general_err_t (*)(const char* data, const size_t data_length)> mqtt_subscriber_pointer_map static
Definition at line 39 of file mqtt_api_v2.cpp.
Referenced by mqtt_api_v2::handle_event(), and mqtt_api_v2::subscribe().