Embedded Library: Components/Utility/utils/test/test/utils_test.cpp File Reference
utils_test.cpp File Reference
#include "../../include/utils.h"
#include <iostream>
#include "CppUTest/TestHarness.h"
Functions
TEST_GROUP (Utils_GRP)
TEST (Utils_GRP, deconcat)
TEST (Utils_GRP, concat)
TEST (Utils_GRP, split_string)
Function Documentation
TEST() [1/3]
TEST (Utils_GRP , concat)
Definition at line 42 of file utils_test.cpp.
 {
     uint8_t m1, m2, m3, m4;
     m1 = 0xde;
     m2 = 0xad;
     m3 = 0xbe;
     m4 = 0xef;
     uint32_t test = 0xdeadbeef;
     auto val = basic_utils::shift8BitTo32(m1, m2, m3, m4);
     LONGS_EQUAL(test, val);
 }
References basic_utils::shift8BitTo32().
TEST() [2/3]
TEST (Utils_GRP , deconcat)
Definition at line 20 of file utils_test.cpp.
 {
     uint8_t m1, m2, m3, m4;
     m1 = 0xde;
     m2 = 0xad;
     m3 = 0xbe;
     m4 = 0xef;
     uint32_t test = 0xdeadbeef;
     auto val = basic_utils::shift8BitTo32(m1, m2, m3, m4);
     uint8_t b1, b2, b3, b4;
     auto err = basic_utils::shift32BitTo8(val, b1, b2, b3, b4);
     CHECK_EQUAL(GE_OK, err);
     LONGS_EQUAL(m1, b1);
     LONGS_EQUAL(m2, b2);
     LONGS_EQUAL(m3, b3);
     LONGS_EQUAL(m4, b4);
 }
References GE_OK, basic_utils::shift32BitTo8(), and basic_utils::shift8BitTo32().
TEST() [3/3]
TEST (Utils_GRP , split_string)
Definition at line 56 of file utils_test.cpp.
 {
     std::string test_string = "1123,43242,222";
     auto test_vec = basic_utils::split(test_string, ",");
     LONGS_EQUAL(3, test_vec.size());
     STRCMP_EQUAL("1123", test_vec.at(0).c_str());
     STRCMP_EQUAL("43242", test_vec.at(1).c_str());
     STRCMP_EQUAL("222", test_vec.at(2).c_str());
 }
References basic_utils::split().
TEST_GROUP()
TEST_GROUP (Utils_GRP)
Definition at line 13 of file utils_test.cpp.
                      {void setup(){
 } void teardown(){
     // Uninit stuff
 }};