Embedded Library: basic_utils Namespace Reference
basic_utils Namespace Reference
Functions
bool is_even (int16_t expr)
uint16_t leastSignificantByteExchange (uint16_t data, uint8_t exchange)
uint8_t getLeastSignificantByte (uint16_t data)
void delay (const uint32_t &delay_ms)
uint32_t shift8BitTo32 (const uint8_t &b1, const uint8_t &b2, const uint8_t &b3, const uint8_t &b4)
general_err_t shift32BitTo8 (const uint32_t &b32, uint8_t &b1, uint8_t &b2, uint8_t &b3, uint8_t &b4)
void split (const std::string &s, char delim, std::vector< std::string > &v)
std::vector< std::string > split (const std::string &s, const std::string &delim)
int random (int min, int max)
Function Documentation
delay()
void basic_utils::delay (const uint32_t & delay_ms)
Referenced by FreeRTOS::Queue::recieve(), and FreeRTOS::Queue::send().
getLeastSignificantByte()
uint8_t basic_utils::getLeastSignificantByte (uint16_t data)
Definition at line 161 of file utils.cpp.
 {
     return static_cast<uint8_t>(data & (uint16_t)0x00ff);
 }
is_even()
bool basic_utils::is_even (int16_t expr)
Definition at line 144 of file utils.cpp.
 {
     // evaluate if this even or odd
     return (expr & 0x01) ? false : true;
 }
leastSignificantByteExchange()
uint16_t basic_utils::leastSignificantByteExchange (uint16_t data, uint8_t exchange)
Definition at line 156 of file utils.cpp.
 {
     return static_cast<uint16_t>((data & 0xff00) + exchange);
 }
random()
int basic_utils::random (int min, int max)
Definition at line 193 of file utils.cpp.
 {
     if(random_first)
     {
         srand(time(NULL));
         random_first = false;
     }
     return min + rand() % ((max + 1) - min);
 }
References random_first.
shift32BitTo8()
general_err_t basic_utils::shift32BitTo8 (const uint32_t & b32, uint8_t & b1, uint8_t & b2, uint8_t & b3, uint8_t & b4)
Definition at line 172 of file utils.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> enclosing_method >> ");
 #endif
     // Executable code:
     b1 = static_cast<uint8_t>(b32 >> 24);
     b2 = static_cast<uint8_t>(b32 >> 16);
     b3 = static_cast<uint8_t>(b32 >> 8);
     b4 = static_cast<uint8_t>(b32);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< enclosing_method << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by TEST().
shift8BitTo32()
uint32_t basic_utils::shift8BitTo32 (const uint8_t & b1, const uint8_t & b2, const uint8_t & b3, const uint8_t & b4)
Definition at line 166 of file utils.cpp.
 {
     return (b1 << 24 | b2 << 16 | b3 << 8 | b4);
 }
Referenced by TEST().
split() [1/2]
void basic_utils::split (const std::string & s, char delim, std::vector< std::string > & v)
Definition at line 13 of file utils.cpp.
 {
     if(s.size() == 0)
     {
         return;
     }
     size_t i = 0;
     auto pos = s.find(delim);
     while(pos != std::string::npos)
     {
         v.push_back(s.substr(i, pos - i));
         i = ++pos;
         pos = s.find(delim, pos);
         if(pos == std::string::npos)
             v.push_back(s.substr(i, s.length()));
     }
 }
Referenced by MQTT_Message::construct(), Utility_Image::equalizeIllumination(), and TEST().
split() [2/2]
std::vector< std::string > basic_utils::split (const std::string & s, const std::string & delim)
Definition at line 32 of file utils.cpp.
 {
     std::vector<std::string> vec;
     if(s.size() == 0)
     {
         return vec;
     }
     size_t i = 0;
     auto pos = s.find(delim);
     while(pos != std::string::npos)
     {
         vec.push_back(s.substr(i, pos - i));
         i = ++pos;
         pos = s.find(delim, pos);
         if(pos == std::string::npos)
             vec.push_back(s.substr(i, s.length()));
     }
     return vec;
 }
References vec.