Embedded Library: QueryMessageBase< T > Class Template Reference
QueryMessageBase< T > Class Template Reference
#include <QueryMessageBase.hpp>
Classes
struct msg_data_t
Public Member Functions
QueryMessageBase (const uint32_t enitity_id)
QueryMessageBase (const uint32_t enitity_id, const msg_data_t &data)
virtual ~QueryMessageBase ()
virtual void addData (const T &data)
virtual void addData (const msg_data_t &data)
auto & getBuffer (void) const
auto & getId (void) const
bool isEmpty (void) const
Protected Attributes
std::vector< msg_data_t > m_buffer
Private Attributes
uint32_t m_entity_id
Detailed Description
template<typename T>
class QueryMessageBase< T >
Definition at line 75 of file QueryMessageBase.hpp.
Class Documentation
QueryMessageBase::msg_data_t
struct QueryMessageBase::msg_data_t
template<typename T>
struct QueryMessageBase< T >::msg_data_t
Definition at line 78 of file QueryMessageBase.hpp.
Class Members
T data
uint64_t time_stamp
Constructor & Destructor Documentation
QueryMessageBase() [1/2]
template<typename T > QueryMessageBase< T >::QueryMessageBase (const uint32_t enitity_id) inline
Definition at line 83 of file QueryMessageBase.hpp.
 : m_entity_id{enitity_id} {};
QueryMessageBase() [2/2]
template<typename T > QueryMessageBase< T >::QueryMessageBase (const uint32_t enitity_id, const msg_data_t & data) inline
Definition at line 84 of file QueryMessageBase.hpp.
         : m_entity_id{enitity_id}, m_buffer{data} {};
~QueryMessageBase()
template<typename T > virtual QueryMessageBase< T >::~QueryMessageBase () inline virtual
Definition at line 87 of file QueryMessageBase.hpp.
 {};
Member Function Documentation
addData() [1/2]
template<typename T > virtual void QueryMessageBase< T >::addData (const msg_data_t & data) inline virtual
Definition at line 94 of file QueryMessageBase.hpp.
     {
         m_buffer.push_back(data);
     }
addData() [2/2]
template<typename T > virtual void QueryMessageBase< T >::addData (const T & data) inline virtual
Definition at line 89 of file QueryMessageBase.hpp.
     {
         m_buffer.push_back({Timeservice::getTimeNow(), data});
     }
Referenced by TEST().
getBuffer()
template<typename T > auto& QueryMessageBase< T >::getBuffer (void) const inline
Definition at line 99 of file QueryMessageBase.hpp.
     {
         return m_buffer;
     };
Referenced by QueryAddSensorData::content(), and QueryAddExternalResources::content().
getId()
template<typename T > auto& QueryMessageBase< T >::getId (void) const inline
Definition at line 104 of file QueryMessageBase.hpp.
     {
         return m_entity_id;
     };
Referenced by QueryAddSensorData::content(), and QueryAddExternalResources::content().
isEmpty()
template<typename T > bool QueryMessageBase< T >::isEmpty (void) const inline
Definition at line 109 of file QueryMessageBase.hpp.
     {
         return m_buffer.size() == 0 ? true : false;
     };
Referenced by QueryAddSensorData::content(), and QueryAddExternalResources::content().
Member Data Documentation
m_buffer
template<typename T > std::vector<msg_data_t> QueryMessageBase< T >::m_buffer protected
Definition at line 118 of file QueryMessageBase.hpp.
Referenced by QueryMessageBase< float >::addData(), QueryMessageBase< float >::getBuffer(), and QueryMessageBase< float >::isEmpty().
m_entity_id
template<typename T > uint32_t QueryMessageBase< T >::m_entity_id private
Definition at line 112 of file QueryMessageBase.hpp.
Referenced by QueryMessageBase< float >::getId().
The documentation for this class was generated from the following file:
Components/Interfaces/QueryBase/include/QueryMessageBase.hpp