Embedded Library: Fault_Handler Class Reference
Fault_Handler Class Reference
#include <Fault_Handler.hpp>
Classes
struct counters_t
Public Member Functions
Fault_Handler (const std::string &class_name)
~Fault_Handler ()
general_err_t handleFault (const FaultHandler_n::msg_t &msg)
general_err_t resetFaultCounter (const FaultHandler_n::severity &level)
Private Member Functions
general_err_t countUp (const FaultHandler_n::msg_t &msg)
general_err_t handle (const FaultHandler_n::msg_t &msg)
std::string toString (const FaultHandler_n::msg_t &msg)
std::string severity2string (const FaultHandler_n::severity &level)
bool check_value (const uint16_t &count, const uint16_t &boundery) const
Private Attributes
std::string m_name
counters_t m_counters
Detailed Description
Class description and usage The fault handler should be implemeted in every class which has "something which might go wrong" This could be: 1) semaphores -> thread-related issues
2) sensors -> bad measurements / hanging
3) timeouts -> stuck in a endless loop
4) other ....
@Class constructor: Class A () : m_faultHandler{"Class A"}
@Faulty code: void faulty_function if(bug){ m_faultHandler.handleFault({ FaultHandler_n::severity::very_high,"faulty_function","we have found a bug" }); }
Definition at line 128 of file Fault_Handler.hpp.
Class Documentation
Fault_Handler::counters_t
struct Fault_Handler::counters_t
Definition at line 187 of file Fault_Handler.hpp.
Class Members
uint16_t high
uint16_t low
uint16_t medium
Constructor & Destructor Documentation
Fault_Handler()
Fault_Handler::Fault_Handler (const std::string & class_name) explicit
Definition at line 36 of file Fault_Handler.cpp.
     : m_name{class_name}, m_counters{0, 0, 0}
 {
 }
~Fault_Handler()
Fault_Handler::~Fault_Handler ()
Definition at line 41 of file Fault_Handler.cpp.
 {}
Member Function Documentation
check_value()
bool Fault_Handler::check_value (const uint16_t & count, const uint16_t & boundery) const inline private
decider function to test if the count value has exceeded the limit
Parameters
count : actual value of how many time a given fault has happend
boundery : the limit which must not be exceeded
Returns
error code
Definition at line 182 of file Fault_Handler.hpp.
     {
         return count >= boundery ? true : false;
     }
Referenced by handle().
countUp()
general_err_t Fault_Handler::countUp (const FaultHandler_n::msg_t & msg) private
count up the internal counter for a given level
Parameters
msg : message containing the level
Returns
error code
Definition at line 43 of file Fault_Handler.cpp.
 {
     // #lizard forgives the complexity
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Fault_Handler::handle >> ");
 #endif
     // Executable code:
     switch(msg.level)
     {
         case FaultHandler_n::severity::lowest:
         case FaultHandler_n::severity::very_low:
         case FaultHandler_n::severity::low:
             ++m_counters.low;
             break;
         case FaultHandler_n::severity::medium_low:
         case FaultHandler_n::severity::medium:
         case FaultHandler_n::severity::medium_high:
             ++m_counters.medium;
             break;
         case FaultHandler_n::severity::high:
         case FaultHandler_n::severity::very_high:
         case FaultHandler_n::severity::highest:
             ++m_counters.high;
             break;
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Fault_Handler::handle << ");
 #endif
     return GE_OK;
 }
References GE_OK, FaultHandler_n::high, Fault_Handler::counters_t::high, FaultHandler_n::highest, FaultHandler_n::msg_t::level, LOG_PRINT_INFO, LOG_TAG, FaultHandler_n::low, Fault_Handler::counters_t::low, FaultHandler_n::lowest, m_counters, FaultHandler_n::medium, Fault_Handler::counters_t::medium, FaultHandler_n::medium_high, FaultHandler_n::medium_low, FaultHandler_n::very_high, and FaultHandler_n::very_low.
Referenced by handleFault().
handle()
general_err_t Fault_Handler::handle (const FaultHandler_n::msg_t & msg) private
private function to handle the message
Parameters
msg : variable of the message class
Returns
error code
Definition at line 76 of file Fault_Handler.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Fault_Handler::toString >> ");
 #endif
     // Executable code:
     // check the low counter
     if(check_value(m_counters.low, FaultHandler_n::max_count_value_low))
     {
         Logger::write({GE_FAIL, GR_REBOOT, toString(msg)});
 #ifndef __UNITTEST__ // should not call exit in unittest mode
         Timeservice::wait_ms(10000);
         std::exit(-1);
 #endif
     }
     // check the medium counter
     if(check_value(m_counters.medium, FaultHandler_n::max_count_value_medium))
     {
         Logger::write({GE_FAIL, GR_REBOOT, toString(msg)});
 #ifndef __UNITTEST__ // should not call exit in unittest mode
         Timeservice::wait_ms(10000);
         std::exit(-1);
 #endif
     }
     // check the high counter
     if(check_value(m_counters.high, FaultHandler_n::max_count_value_high))
     {
         Logger::write({GE_FAIL, GR_REBOOT, toString(msg)});
 #ifndef __UNITTEST__ // should not call exit in unittest mode
         Timeservice::wait_ms(10000);
         std::exit(-1);
 #endif
     }
     // no critical bounderies are breached and so we will only be writing to log file
     Logger::write({GE_FAIL, GR_NO_RESPONSE, toString(msg)});
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Fault_Handler::toString << ");
 #endif
     return GE_OK;
 }
References check_value(), GE_FAIL, GE_OK, GR_NO_RESPONSE, GR_REBOOT, Fault_Handler::counters_t::high, LOG_PRINT_INFO, LOG_TAG, Fault_Handler::counters_t::low, m_counters, FaultHandler_n::max_count_value_high, FaultHandler_n::max_count_value_low, FaultHandler_n::max_count_value_medium, Fault_Handler::counters_t::medium, toString(), Timeservice::wait_ms(), and Logger::write().
Referenced by handleFault().
handleFault()
general_err_t Fault_Handler::handleFault (const FaultHandler_n::msg_t & msg)
a function to handle the internal faults
Parameters
msg a message class containing all relevant information
Returns
error code
Definition at line 122 of file Fault_Handler.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Fault_Handler::handleFault >> ");
 #endif
     // Executable code:
     countUp(msg); // count up the fault
     handle(msg); // decide if we need to act, this includes logging and exiting
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Fault_Handler::handleFault << ");
 #endif
     return GE_OK;
 }
References countUp(), GE_OK, handle(), LOG_PRINT_INFO, and LOG_TAG.
Referenced by MG996R::actuate(), Maintainer::check_system_functions(), Maintainer::periodic_restart(), and PWM_API_ESP32::setDutyCycle().
resetFaultCounter()
general_err_t Fault_Handler::resetFaultCounter (const FaultHandler_n::severity & level)
a function to reset the internal counter of a level
Parameters
level the relevant level to reset
Returns
error code
Definition at line 153 of file Fault_Handler.cpp.
 {
     // #lizard forgives the complexity
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Fault_Handler::reset >> ");
 #endif
     // Executable code:
     switch(level)
     {
         case FaultHandler_n::severity::lowest:
         case FaultHandler_n::severity::very_low:
         case FaultHandler_n::severity::low:
             m_counters.low = 0;
             break;
         case FaultHandler_n::severity::medium_low:
         case FaultHandler_n::severity::medium:
         case FaultHandler_n::severity::medium_high:
             m_counters.medium = 0;
             break;
         case FaultHandler_n::severity::high:
         case FaultHandler_n::severity::very_high:
         case FaultHandler_n::severity::highest:
             m_counters.high = 0;
             break;
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Fault_Handler::reset << ");
 #endif
     return GE_OK;
 }
References GE_OK, FaultHandler_n::high, Fault_Handler::counters_t::high, FaultHandler_n::highest, LOG_PRINT_INFO, LOG_TAG, FaultHandler_n::low, Fault_Handler::counters_t::low, FaultHandler_n::lowest, m_counters, FaultHandler_n::medium, Fault_Handler::counters_t::medium, FaultHandler_n::medium_high, FaultHandler_n::medium_low, FaultHandler_n::very_high, and FaultHandler_n::very_low.
severity2string()
std::string Fault_Handler::severity2string (const FaultHandler_n::severity & level) private
simple tostring method for logging purposes
Parameters
level : variable of the level
Returns
error code
Definition at line 186 of file Fault_Handler.cpp.
 {
     switch(level)
     {
         case FaultHandler_n::severity::lowest:
             return "lowest";
         case FaultHandler_n::severity::very_low:
             return "very_low";
         case FaultHandler_n::severity::low:
             return "low";
         case FaultHandler_n::severity::medium_low:
             return "medium_low";
         case FaultHandler_n::severity::medium:
             return "medium";
         case FaultHandler_n::severity::medium_high:
             return "medium_high";
         case FaultHandler_n::severity::high:
             return "high";
         case FaultHandler_n::severity::very_high:
             return "very_high";
         case FaultHandler_n::severity::highest:
             return "highest";
     }
     return "FAIL";
 }
References FaultHandler_n::high, FaultHandler_n::highest, FaultHandler_n::low, FaultHandler_n::lowest, FaultHandler_n::medium, FaultHandler_n::medium_high, FaultHandler_n::medium_low, FaultHandler_n::very_high, and FaultHandler_n::very_low.
Referenced by toString().
toString()
std::string Fault_Handler::toString (const FaultHandler_n::msg_t & msg) private
simple tostring method for logging purposes
Parameters
msg : variable of the message class
Returns
error code
Definition at line 138 of file Fault_Handler.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Fault_Handler::toString >> ");
 #endif
     // Executable code:
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Fault_Handler::toString << ");
 #endif
     return severity2string(msg.level) + "," + m_name + "," + msg.function_name + "," +
            msg.describtion;
 }
References FaultHandler_n::msg_t::describtion, FaultHandler_n::msg_t::function_name, FaultHandler_n::msg_t::level, LOG_PRINT_INFO, LOG_TAG, m_name, and severity2string().
Referenced by handle().
Member Data Documentation
m_counters
counters_t Fault_Handler::m_counters private
Definition at line 193 of file Fault_Handler.hpp.
Referenced by countUp(), handle(), and resetFaultCounter().
m_name
std::string Fault_Handler::m_name private
Definition at line 186 of file Fault_Handler.hpp.
Referenced by toString().
The documentation for this class was generated from the following files:
Components/Objects/FaultHandler/include/Fault_Handler.hpp
Components/Objects/FaultHandler/src/Fault_Handler.cpp