Embedded Library: GPIO_HAL Class Reference
GPIO_HAL Class Reference
#include <HAL.hpp>
Public Types
enum io_def_t { INPUT = 0, OUTPUT = 1 }
enum io_val_t { LOW = 0, HIGH = 1 }
enum io_intr_t { FALLING_EDGE = 0, RISING_EDGE, ANY_EDGE }
typedef int pin
Public Member Functions
GPIO_HAL ()=default
~GPIO_HAL ()
general_err_t setDirection (const GPIO_HAL::pin &pin, const GPIO_HAL::io_def_t &dir)
set the direction of the pin
general_err_t setValue (const GPIO_HAL::pin &pin, const GPIO_HAL::io_val_t &val)
set the value of the pin
GPIO_HAL::io_val_t getValue (const GPIO_HAL::pin &pin) const
read the value of the pin
general_err_t installInterruptDriver (const GPIO_HAL::pin &pin, void(*callbackfunction)(void *), const GPIO_HAL::io_intr_t &intr)
general_err_t enableInterrupt (const GPIO_HAL::pin &pin)
general_err_t disableInterrupt (const GPIO_HAL::pin &pin)
Detailed Description
Definition at line 76 of file HAL.hpp.
Member Typedef Documentation
pin
typedef int GPIO_HAL::pin
Definition at line 86 of file HAL.hpp.
Member Enumeration Documentation
io_def_t
enum GPIO_HAL::io_def_t
Enumerator
INPUT
OUTPUT
Definition at line 88 of file HAL.hpp.
     {
         INPUT = 0,
         OUTPUT = 1
     } io_def_t;
io_intr_t
enum GPIO_HAL::io_intr_t
Enumerator
FALLING_EDGE
RISING_EDGE
ANY_EDGE
Definition at line 98 of file HAL.hpp.
     {
         FALLING_EDGE = 0,
         RISING_EDGE,
         ANY_EDGE
     } io_intr_t;
io_val_t
enum GPIO_HAL::io_val_t
Enumerator
LOW
HIGH
Definition at line 93 of file HAL.hpp.
     {
         LOW = 0,
         HIGH = 1
     } io_val_t;
Constructor & Destructor Documentation
GPIO_HAL()
GPIO_HAL::GPIO_HAL () default
~GPIO_HAL()
GPIO_HAL::~GPIO_HAL () inline
Definition at line 105 of file HAL.hpp.
 {};
Member Function Documentation
disableInterrupt()
general_err_t GPIO_HAL::disableInterrupt (const GPIO_HAL::pin & pin)
Definition at line 135 of file HAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> GPIO_HAL::disableInterrupt >> ");
 #endif
     // Executable code:
 #ifdef __ESP32__
     return gpio_intr_disable(pin) == ESP_OK ? GE_OK : GE_FAIL; // disable the pin for interrupts
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< GPIO_HAL::disableInterrupt << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by GPIO_API::disableInterrupt().
enableInterrupt()
general_err_t GPIO_HAL::enableInterrupt (const GPIO_HAL::pin & pin)
Definition at line 118 of file HAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> GPIO_HAL::enableInterrupt >> ");
 #endif
     // Executable code:
 #ifdef __ESP32__
     return gpio_intr_enable(pin) == ESP_OK ? GE_OK : GE_FAIL; // Enable the pin for interrupts
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< GPIO_HAL::enableInterrupt << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by GPIO_API::enableInterrupt().
getValue()
GPIO_HAL::io_val_t GPIO_HAL::getValue (const GPIO_HAL::pin & pin) const
read the value of the pin
Attention
Parameters
[in] const HAL::pin& pin
Returns
GE_OK
Definition at line 109 of file HAL.cpp.
 {
 #ifdef __ESP32__
     return gpio_get_level(pin) == 1 ? GPIO_HAL::io_val_t::HIGH : GPIO_HAL::io_val_t::LOW;
 #else
     return GPIO_HAL::io_val_t::LOW;
 #endif
 }
Referenced by GPIO_API::isHigh(), and GPIO_API::isLow().
installInterruptDriver()
general_err_t GPIO_HAL::installInterruptDriver (const GPIO_HAL::pin & pin, void(*)(void *) callbackfunction, const GPIO_HAL::io_intr_t & intr)
Definition at line 152 of file HAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> GPIO_HAL::installInterruptDriver >> ");
 #endif
     // Executable code:
 #ifdef __ESP32__
     switch(intr)
     {
         case GPIO_HAL::io_intr_t::ANY_EDGE:
             gpio_set_intr_type(pin, GPIO_INTR_ANYEDGE);
             break;
         case GPIO_HAL::io_intr_t::FALLING_EDGE:
             gpio_set_intr_type(pin, GPIO_INTR_NEGEDGE);
             break;
         case GPIO_HAL::io_intr_t::RISING_EDGE:
             gpio_set_intr_type(pin, GPIO_INTR_POSEDGE);
             break;
         default:
             break;
     }
     // install gpio isr service
     gpio_install_isr_service(ESP_INTR_FLAG_LEVEL3); // Todo
     // hook isr handler for specific gpio pin
     gpio_isr_handler_add(pin, callbackfunction, NULL);
 #else
     // call the callback function for testing purposes
     callbackfunction(nullptr);
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< GPIO_HAL::installInterruptDriver << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by GPIO_API::installInterrupt().
setDirection()
general_err_t GPIO_HAL::setDirection (const GPIO_HAL::pin & pin, const GPIO_HAL::io_def_t & dir)
set the direction of the pin
Attention
Parameters
[in] const HAL::pin& pin
[in] const HAL::io_def& dir
Returns
GE_OK
Definition at line 50 of file HAL.cpp.
 {
 #ifdef __ESP32__
     if(gpio_set_direction(pin, dir == GPIO_HAL::io_def_t::OUTPUT ? GPIO_MODE_OUTPUT
                                                                  : GPIO_MODE_INPUT) == ESP_OK)
     {
         return GE_OK;
     }
     else
     {
         return GE_FAIL;
     }
 #else
     return GE_OK;
 #endif
 }
References GE_FAIL, and GE_OK.
Referenced by GPIO_API::setToInput(), and GPIO_API::setToOutput().
setValue()
general_err_t GPIO_HAL::setValue (const GPIO_HAL::pin & pin, const GPIO_HAL::io_val_t & val)
set the value of the pin
Attention
Parameters
[in] const HAL::pin& pin
[in] const HAL::io_val_t& val
Returns
GE_OK
Definition at line 81 of file HAL.cpp.
 {
 #ifdef __ESP32__
     if(gpio_set_level(pin, val == GPIO_HAL::io_val_t::HIGH ? true : false) == ESP_OK)
     {
         return GE_OK;
     }
     else
     {
         return GE_FAIL;
     }
 #else
     return GE_OK;
 #endif
 }
References GE_FAIL, and GE_OK.
Referenced by GPIO_API::setHigh(), and GPIO_API::setLow().
The documentation for this class was generated from the following files:
Components/Objects/Gpio/include/HAL.hpp
Components/Objects/Gpio/src/HAL.cpp