Embedded Library: PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE > Class Template Reference
PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE > Class Template Reference
#include <PeriodeEstimator.hpp>
Public Types
enum states : uint8_t { states::HIGH, states::MIDDLE, states::LOW, states::UNDEF }
Public Member Functions
PeriodeEstimator ()
~PeriodeEstimator ()
general_err_t addData (std::pair< uint64_t, uint64_t > data)
add data to the estimator in order to on-the-fly detect periods.
const auto getPeriodCounter ()
Get the Period Counter object.
Private Member Functions
general_err_t decideStateChange (const states &new_state)
general_err_t setInitialState (const states &new_state)
general_err_t setNextState (const states &new_state)
bool isExpectedState (const states &new_state)
Private Attributes
const uint64_t m_high_threshold
const uint64_t m_low_threshold
states m_current_state
states m_last_state
states m_next_expected
uint64_t m_counter
Static Private Attributes
static constexpr std::uint_fast8_t PERIODE_SCALER = 1
Detailed Description
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE>
class PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >
Definition at line 48 of file PeriodeEstimator.hpp.
Member Enumeration Documentation
states
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > enum PeriodeEstimator::states : uint8_t strong
Enumerator
HIGH
MIDDLE
LOW
UNDEF
Definition at line 54 of file PeriodeEstimator.hpp.
                       : uint8_t
     {
         HIGH,
         MIDDLE,
         LOW,
         UNDEF
     };
Constructor & Destructor Documentation
PeriodeEstimator()
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::PeriodeEstimator () inline
Definition at line 61 of file PeriodeEstimator.hpp.
         : m_high_threshold{HIGH_THRESHOLD}, m_low_threshold{LOW_THRESHOLD},
           m_current_state{states::UNDEF}, m_last_state{states::UNDEF}, m_counter{COUNTER_VALUE}
     {
         static_assert(LOW_THRESHOLD < HIGH_THRESHOLD);
         if(NVS<NVS_TYPE>::read_u64("INIT_KEY") != INIT_VALUE)
         {
             NVS<NVS_TYPE>::write_u64("COUNTER", COUNTER_VALUE);
             NVS<NVS_TYPE>::write_u64("INIT_KEY", INIT_VALUE);
         }
         else
         {
             m_counter = NVS<NVS_TYPE>::read_u64("COUNTER");
         }
     };
~PeriodeEstimator()
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::~PeriodeEstimator () inline
Definition at line 77 of file PeriodeEstimator.hpp.
 {};
Member Function Documentation
addData()
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > general_err_t PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::addData (std::pair< uint64_t, uint64_t > data) inline
add data to the estimator in order to on-the-fly detect periods.
The pair<uint64_t, uint64_t> is expected to be pair<Timestamp,Datapoint>
Parameters
data
Returns
general_err_t
Definition at line 87 of file PeriodeEstimator.hpp.
     {
         auto& datapoint = data.second;
         states new_state = states::UNDEF;
         new_state = datapoint > m_high_threshold
                         ? states::HIGH
                         : datapoint > m_low_threshold ? states::MIDDLE : states::LOW;
         return decideStateChange(new_state);
     }
Referenced by WaterEstimator_Service::mainFunction().
decideStateChange()
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > general_err_t PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::decideStateChange (const states & new_state) inline private
Definition at line 106 of file PeriodeEstimator.hpp.
     {
         if(m_current_state != new_state)
         {
             return m_current_state == states::UNDEF ? setInitialState(new_state)
                                                     : setNextState(new_state);
         }
         return GE_NO_DATA;
     }
Referenced by PeriodeEstimator< 1500, 1200, NVS_MOCK >::addData().
getPeriodCounter()
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > const auto PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::getPeriodCounter () inline
Get the Period Counter object.
Returns
auto const&
Definition at line 100 of file PeriodeEstimator.hpp.
     {
         return m_counter;
     }
Referenced by WaterEstimator_Service::mainFunction().
isExpectedState()
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > bool PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::isExpectedState (const states & new_state) inline private
Definition at line 146 of file PeriodeEstimator.hpp.
     {
         if(new_state == states::HIGH and m_current_state == states::MIDDLE and
            m_last_state == states::LOW)
         {
             return true;
         }
         if(new_state == states::MIDDLE and m_current_state == states::HIGH and
            m_last_state == states::MIDDLE)
         {
             return true;
         }
         if(new_state == states::LOW and m_current_state == states::MIDDLE and
            m_last_state == states::HIGH)
         {
             return true;
         }
         if(new_state == states::MIDDLE and m_current_state == states::LOW and
            m_last_state == states::MIDDLE)
         {
             return true;
         }
         return false;
     }
Referenced by PeriodeEstimator< 1500, 1200, NVS_MOCK >::setNextState().
setInitialState()
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > general_err_t PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::setInitialState (const states & new_state) inline private
Definition at line 115 of file PeriodeEstimator.hpp.
     {
         // only change the state from UNDEF to HIGH if
         // the new state is high
         // this is to ensure that we know what state we are in
         // from the beginning. We might loose 1 whole period, pr init
         // but that is an acceptable risk
         if(new_state == states::HIGH)
         {
             m_current_state = new_state;
             m_last_state = states::MIDDLE;
         }
         return GE_NO_DATA;
     }
Referenced by PeriodeEstimator< 1500, 1200, NVS_MOCK >::decideStateChange().
setNextState()
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > general_err_t PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::setNextState (const states & new_state) inline private
Definition at line 129 of file PeriodeEstimator.hpp.
     {
         if(isExpectedState(new_state))
         {
             m_last_state = m_current_state;
             m_current_state = new_state;
             if(m_current_state == states::HIGH)
             {
                 m_counter++;
                 NVS<NVS_TYPE>::write_u64("COUNTER", m_counter);
                 return GE_OK;
             }
         }
         return GE_NO_DATA;
     }
Referenced by PeriodeEstimator< 1500, 1200, NVS_MOCK >::decideStateChange().
Member Data Documentation
m_counter
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > uint64_t PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::m_counter private
Definition at line 175 of file PeriodeEstimator.hpp.
Referenced by PeriodeEstimator< 1500, 1200, NVS_MOCK >::getPeriodCounter(), and PeriodeEstimator< 1500, 1200, NVS_MOCK >::setNextState().
m_current_state
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > states PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::m_current_state private
Definition at line 172 of file PeriodeEstimator.hpp.
Referenced by PeriodeEstimator< 1500, 1200, NVS_MOCK >::decideStateChange(), PeriodeEstimator< 1500, 1200, NVS_MOCK >::isExpectedState(), PeriodeEstimator< 1500, 1200, NVS_MOCK >::setInitialState(), and PeriodeEstimator< 1500, 1200, NVS_MOCK >::setNextState().
m_high_threshold
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > const uint64_t PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::m_high_threshold private
Definition at line 170 of file PeriodeEstimator.hpp.
Referenced by PeriodeEstimator< 1500, 1200, NVS_MOCK >::addData().
m_last_state
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > states PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::m_last_state private
Definition at line 173 of file PeriodeEstimator.hpp.
Referenced by PeriodeEstimator< 1500, 1200, NVS_MOCK >::isExpectedState(), PeriodeEstimator< 1500, 1200, NVS_MOCK >::setInitialState(), and PeriodeEstimator< 1500, 1200, NVS_MOCK >::setNextState().
m_low_threshold
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > const uint64_t PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::m_low_threshold private
Definition at line 171 of file PeriodeEstimator.hpp.
Referenced by PeriodeEstimator< 1500, 1200, NVS_MOCK >::addData().
m_next_expected
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > states PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::m_next_expected private
Definition at line 174 of file PeriodeEstimator.hpp.
PERIODE_SCALER
template<uint64_t HIGH_THRESHOLD, uint64_t LOW_THRESHOLD, typename NVS_TYPE > constexpr std::uint_fast8_t PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::PERIODE_SCALER = 1 static constexpr private
Definition at line 176 of file PeriodeEstimator.hpp.
The documentation for this class was generated from the following file:
Components/AnalysisTools/PeriodEstimator/include/PeriodeEstimator.hpp