Embedded Library: HAL_ESP32 Class Reference
HAL_ESP32 Class Reference
#include <HAL.hpp>
Classes
struct config
Public Types
typedef int speed_mode
typedef int lcd_channel
typedef int pin
Public Member Functions
HAL_ESP32 (const config &conf)
~HAL_ESP32 ()
general_err_t setDutyCycle (const float &duty)
general_err_t setFrequency (const uint32_t &frequency)
general_err_t stop (void)
general_err_t destroy (void)
const auto & getConfig (void)
Private Member Functions
uint32_t calculateDutyCycleBasedOnResolution (const float &duty)
a converter function to convert the duty cycle in [%] to resolution based
Private Attributes
config m_conf
Detailed Description
Definition at line 76 of file HAL.hpp.
Class Documentation
HAL_ESP32::config
struct HAL_ESP32::config
Definition at line 93 of file HAL.hpp.
Class Members
lcd_channel channel
float duty
uint32_t frequency
pin m_pin
speed_mode mode
Member Typedef Documentation
lcd_channel
typedef int HAL_ESP32::lcd_channel
Definition at line 89 of file HAL.hpp.
pin
typedef int HAL_ESP32::pin
Definition at line 90 of file HAL.hpp.
speed_mode
typedef int HAL_ESP32::speed_mode
Definition at line 88 of file HAL.hpp.
Constructor & Destructor Documentation
HAL_ESP32()
HAL_ESP32::HAL_ESP32 (const config & conf)
Definition at line 41 of file HAL.cpp.
                                        : m_conf{conf}
 {
 #ifdef __ESP32__
     ledc_timer_config_t timer_conf;
     timer_conf.speed_mode = conf.mode;
     timer_conf.duty_resolution = LEDC_TIMER_10_BIT; // 8bit = 0 -> 1024 resolution
     timer_conf.timer_num = LEDC_TIMER_1;
     timer_conf.freq_hz = conf.frequency;
     timer_conf.clk_cfg = LEDC_AUTO_CLK; // deicde for yourself
     auto err = ledc_timer_config(&timer_conf);
     if(err != ESP_OK)
     {
         std::cout << " could not initialize ledc_timer_config  ... restarting ! \n";
         exit(-1);
     }
     ledc_channel_config_t led_conf;
     led_conf.gpio_num = conf.m_pin;
     led_conf.speed_mode = conf.mode;
     led_conf.channel = conf.channel;
     led_conf.intr_type = LEDC_INTR_DISABLE; // we do not use interrupts
     led_conf.timer_sel = LEDC_TIMER_1; // should not be needed to select timers
     led_conf.duty = 0;
     led_conf.hpoint = 0;
     err = ledc_channel_config(&led_conf);
     if(err != ESP_OK)
     {
         std::cout << " could not initialize ledc_channel_config ... restarting ! \n";
         exit(-1);
     }
 #endif
 }
~HAL_ESP32()
HAL_ESP32::~HAL_ESP32 ()
Definition at line 78 of file HAL.cpp.
 {}
Member Function Documentation
calculateDutyCycleBasedOnResolution()
uint32_t HAL_ESP32::calculateDutyCycleBasedOnResolution (const float & duty) private
a converter function to convert the duty cycle in [%] to resolution based
Attention
we are loosing some performance in the sense of math with floats, but this is not a time critical called function so we are willingly letting go.
Parameters
[in] const float &duty
[out] duty in resolution domain
Returns
GE_OK
Definition at line 184 of file HAL.cpp.
 {
     return (duty / 100) * 1024;
 }
Referenced by setDutyCycle().
destroy()
general_err_t HAL_ESP32::destroy (void)
Definition at line 155 of file HAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> HAL_ESP32::destroy >> ");
 #endif
     // Executable code:
     stop();
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< HAL_ESP32::destroy << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, LOG_TAG, and stop().
getConfig()
const auto& HAL_ESP32::getConfig (void) inline
Definition at line 109 of file HAL.hpp.
     {
         return m_conf;
     }
References m_conf.
setDutyCycle()
general_err_t HAL_ESP32::setDutyCycle (const float & duty)
Definition at line 80 of file HAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> HAL_ESP32::setDutyCycle >> ");
 #endif
     // Executable code:
 #ifdef __ESP32__
     auto err =
         ledc_set_duty(m_conf.mode, m_conf.channel, calculateDutyCycleBasedOnResolution(duty));
     if(err != ESP_OK)
     {
         std::cout << " could not  call ledc_set_duty ... restarting ! \n";
         exit(-1);
     }
     err = ledc_update_duty(m_conf.mode, m_conf.channel);
     if(err != ESP_OK)
     {
         std::cout << " could not  call ledc_update_duty ... restarting ! \n";
         exit(-1);
     }
 #endif
     // update duty cycle parameter
     m_conf.duty = duty;
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< HAL_ESP32::setDutyCycle << ");
 #endif
     return GE_OK;
 }
References calculateDutyCycleBasedOnResolution(), HAL_ESP32::config::channel, HAL_ESP32::config::duty, GE_OK, LOG_PRINT_INFO, LOG_TAG, m_conf, and HAL_ESP32::config::mode.
Referenced by PWM_API_ESP32::setDutyCycle().
setFrequency()
general_err_t HAL_ESP32::setFrequency (const uint32_t & frequency)
Definition at line 111 of file HAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> HAL_ESP32::setFrequency >> ");
 #endif
     // Executable code:
 #ifdef __ESP32__
     auto err = ledc_set_freq(m_conf.mode, LEDC_TIMER_0, frequency);
     if(err != ESP_OK)
     {
         std::cout << " could not  call ledc_set_freq ... restarting ! \n";
         exit(-1);
     }
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< HAL_ESP32::setFrequency << ");
 #endif
     // update frequency parameter
     m_conf.frequency = frequency;
     return GE_OK;
 }
References HAL_ESP32::config::frequency, GE_OK, LOG_PRINT_INFO, LOG_TAG, m_conf, and HAL_ESP32::config::mode.
Referenced by PWM_API_ESP32::setFrequency().
stop()
general_err_t HAL_ESP32::stop (void)
Definition at line 134 of file HAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> HAL_ESP32::stop >> ");
 #endif
     // Executable code:
 #ifdef __ESP32__
     auto err = ledc_stop(m_conf.mode, m_conf.channel, 0);
     if(err != ESP_OK)
     {
         std::cout << " could not  call ledc_stop ... restarting ! \n";
         exit(-1);
     }
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< HAL_ESP32::stop << ");
 #endif
     return GE_OK;
 }
References HAL_ESP32::config::channel, GE_OK, LOG_PRINT_INFO, LOG_TAG, m_conf, and HAL_ESP32::config::mode.
Referenced by destroy(), PWM_API_ESP32::stop(), and PWM_API_ESP32::~PWM_API_ESP32().
Member Data Documentation
m_conf
config HAL_ESP32::m_conf private
Definition at line 117 of file HAL.hpp.
Referenced by getConfig(), setDutyCycle(), setFrequency(), and stop().
The documentation for this class was generated from the following files:
Components/Objects/PWM/include/HAL.hpp
Components/Objects/PWM/src/HAL.cpp