Embedded Library: SensorControllerBase Class Reference
SensorControllerBase Class Reference abstract
#include <SensorControllerBase.hpp>
Classes
struct init_conf
Public Member Functions
SensorControllerBase (const init_conf &conf)
virtual ~SensorControllerBase ()
void setWantDataTrue ()
const auto & getSafeBuffer ()
const bool isDataReady ()
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Protected Member Functions
void setDataReadyTrue ()
general_err_t postData (const MQTT_Message &message, const std::string &topic="mqtt/burst_msg")
void postError (const general_err_t &err, const std::string &error_message)
virtual general_err_t main_function ()=0
Protected Attributes
MQTT_Message m_buffer_raw
MQTT_Message m_buffer_external
std::atomic< bool > m_want_data_flag
std::atomic< bool > m_data_ready_flag
const uint64_t m_delay
const db_id m_error_id
Private Member Functions
void setDataReady (bool flag)
void setWantData (bool flag)
void run (void *data) override
Body of the task to execute.
Private Attributes
mqtt_api_v2 m_mqtt
Detailed Description
Definition at line 53 of file SensorControllerBase.hpp.
Class Documentation
SensorControllerBase::init_conf
struct SensorControllerBase::init_conf
Definition at line 59 of file SensorControllerBase.hpp.
Class Members
msg_conf_t buffer_external_conf
msg_conf_t buffer_raw_conf
db_id error_code_id
uint64_t task_delay
Constructor & Destructor Documentation
SensorControllerBase()
SensorControllerBase::SensorControllerBase (const init_conf & conf) inline
Definition at line 67 of file SensorControllerBase.hpp.
         : m_buffer_raw{conf.buffer_raw_conf}, m_buffer_external{conf.buffer_external_conf},
           m_delay{conf.task_delay}, m_error_id{conf.error_code_id} {};
References SensorControllerBase::init_conf::buffer_raw_conf.
~SensorControllerBase()
virtual SensorControllerBase::~SensorControllerBase () inline virtual
Definition at line 70 of file SensorControllerBase.hpp.
 {};
Member Function Documentation
getSafeBuffer()
const auto& SensorControllerBase::getSafeBuffer () inline
Definition at line 78 of file SensorControllerBase.hpp.
     {
         return m_buffer_external;
     }
References m_buffer_external.
Referenced by DataBroker::main_function().
isDataReady()
const bool SensorControllerBase::isDataReady () inline
Definition at line 82 of file SensorControllerBase.hpp.
     {
         return m_data_ready_flag;
     }
References m_data_ready_flag.
Referenced by DataBroker::main_function().
main_function()
virtual general_err_t SensorControllerBase::main_function () protected pure virtual
Implemented in DistanceSensorController, and SensorControllerBase_MOCK.
Referenced by run().
postData()
general_err_t SensorControllerBase::postData (const MQTT_Message & message, const std::string & topic = "mqtt/burst_msg") protected
Definition at line 43 of file SensorControllerBase.cpp.
 {
     return m_mqtt.publish(topic, message.toString());
 }
References m_mqtt, mqtt_api_v2::publish(), and MQTT_Message::toString().
Referenced by DistanceSensorController::main_function().
postError()
void SensorControllerBase::postError (const general_err_t & err, const std::string & error_message) inline protected
Definition at line 96 of file SensorControllerBase.hpp.
     {
         ErrorCodeParser::postToMqtt(m_error_id, err, error_message);
     }
References m_error_id, and ErrorCodeParser::postToMqtt().
Referenced by run().
run()
void SensorControllerBase::run (void * data) override private virtual
Body of the task to execute.
This function must be implemented in the subclass that represents the actual task to run. When a task is started by calling start(), this is the code that is executed in the newly created task. WHY IS IT NOT PRIVATE???
Parameters
[in] data The data passed in to the newly started task.
Implements Task.
Definition at line 29 of file SensorControllerBase.cpp.
 {
     for(;;)
     {
         auto err = main_function();
         if(err != GE_OK)
         {
             postError(err, "Main function failed");
         }
         Timeservice::wait_ms(m_delay);
     }
 }
References GE_OK, m_delay, main_function(), postError(), and Timeservice::wait_ms().
setDataReady()
void SensorControllerBase::setDataReady (bool flag) inline private
Definition at line 109 of file SensorControllerBase.hpp.
     {
         m_data_ready_flag = flag;
     }
References m_data_ready_flag.
Referenced by setDataReadyTrue(), and setWantDataTrue().
setDataReadyTrue()
void SensorControllerBase::setDataReadyTrue () inline protected
Definition at line 88 of file SensorControllerBase.hpp.
     {
         setDataReady(true);
         setWantData(false);
     }
References setDataReady(), and setWantData().
Referenced by DistanceSensorController::updateInternalBuffer().
setWantData()
void SensorControllerBase::setWantData (bool flag) inline private
Definition at line 113 of file SensorControllerBase.hpp.
     {
         m_want_data_flag = flag;
     }
References m_want_data_flag.
Referenced by setDataReadyTrue(), and setWantDataTrue().
setWantDataTrue()
void SensorControllerBase::setWantDataTrue () inline
Definition at line 72 of file SensorControllerBase.hpp.
     {
         setWantData(true);
         setDataReady(false);
     }
References setDataReady(), and setWantData().
Referenced by DataBroker::main_function().
Member Data Documentation
m_buffer_external
MQTT_Message SensorControllerBase::m_buffer_external protected
Definition at line 102 of file SensorControllerBase.hpp.
Referenced by getSafeBuffer(), and DistanceSensorController::updateInternalBuffer().
m_buffer_raw
MQTT_Message SensorControllerBase::m_buffer_raw protected
Definition at line 101 of file SensorControllerBase.hpp.
Referenced by DistanceSensorController::main_function(), and DistanceSensorController::updateInternalBuffer().
m_data_ready_flag
std::atomic<bool> SensorControllerBase::m_data_ready_flag protected
Definition at line 104 of file SensorControllerBase.hpp.
Referenced by isDataReady(), setDataReady(), and DistanceSensorController::updateInternalBuffer().
m_delay
const uint64_t SensorControllerBase::m_delay protected
Definition at line 105 of file SensorControllerBase.hpp.
Referenced by run().
m_error_id
const db_id SensorControllerBase::m_error_id protected
Definition at line 106 of file SensorControllerBase.hpp.
Referenced by postError().
m_mqtt
mqtt_api_v2 SensorControllerBase::m_mqtt private
Definition at line 120 of file SensorControllerBase.hpp.
Referenced by postData().
m_want_data_flag
std::atomic<bool> SensorControllerBase::m_want_data_flag protected
Definition at line 103 of file SensorControllerBase.hpp.
Referenced by setWantData(), and DistanceSensorController::updateInternalBuffer().
The documentation for this class was generated from the following files:
Components/Interfaces/SensorControllerBase/include/SensorControllerBase.hpp
Components/Interfaces/SensorControllerBase/src/SensorControllerBase.cpp