Embedded Library: ActiveCurrentSensor Class Reference
ActiveCurrentSensor Class Reference final
#include <ActiveCurrentSensor.hpp>
Public Member Functions
ActiveCurrentSensor (const ADC_API_ESP32::config &adc_conf, const MQTT_Message::msg_conf_t &msg_conf)
~ActiveCurrentSensor ()
void run (void *data) override
Body of the task to execute.
void activateQueue ()
auto & isRunning ()
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Private Member Functions
general_err_t main_function (void)
Private Attributes
ADC_API_ESP32 m_adc
MQTT_Message m_msg
mqtt_api_v2 m_mqtt
std::atomic< bool > m_isRunning
FreeRTOS::Queue m_queue
Detailed Description
Definition at line 54 of file ActiveCurrentSensor.hpp.
Constructor & Destructor Documentation
ActiveCurrentSensor()
ActiveCurrentSensor::ActiveCurrentSensor (const ADC_API_ESP32::config & adc_conf, const MQTT_Message::msg_conf_t & msg_conf)
Definition at line 29 of file ActiveCurrentSensor.cpp.
     : m_adc{adc_conf}, m_msg{msg_conf}, m_isRunning{false}, m_queue{1,
                                                                     recieved_queue_message.size()}
 {
     // m_queue.initialize(1, recieved_queue_message.size());
 }
~ActiveCurrentSensor()
ActiveCurrentSensor::~ActiveCurrentSensor ()
Definition at line 36 of file ActiveCurrentSensor.cpp.
 {}
Member Function Documentation
activateQueue()
void ActiveCurrentSensor::activateQueue ()
Definition at line 38 of file ActiveCurrentSensor.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> ActiveCurrentSensor::activateQueue >> ");
 #endif
     // Executable code:
     m_queue.send(recieved_queue_message.c_str(), 5000);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  ActiveCurrentSensor::activateQueue << ");
 #endif
 }
References LOG_PRINT_INFO, LOG_TAG, m_queue, recieved_queue_message, and FreeRTOS::Queue::send().
isRunning()
auto& ActiveCurrentSensor::isRunning () inline
Definition at line 65 of file ActiveCurrentSensor.hpp.
     {
         return m_isRunning;
     }
References m_isRunning.
main_function()
general_err_t ActiveCurrentSensor::main_function (void) private
Definition at line 71 of file ActiveCurrentSensor.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> ActiveCurrentSensor::main_function >> ");
 #endif
     // Executable code:
     constexpr size_t AMOUNT_OF_MEASUREMENTS = 300;
     constexpr size_t WAIT_DELAY = 20;
     m_msg.clear(); // make sure it is cleared
     for(size_t i = 0; i < AMOUNT_OF_MEASUREMENTS; i++)
     {
         m_msg.addData(m_adc.measureValue());
         Timeservice::wait_ms(WAIT_DELAY);
     }
     m_mqtt.publish("mqtt/burst_msg", m_msg.toString());
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  ActiveCurrentSensor::main_function << ");
 #endif
     return GE_OK;
 }
References MQTT_Message::addData(), AMOUNT_OF_MEASUREMENTS, MQTT_Message::clear(), GE_OK, LOG_PRINT_INFO, LOG_TAG, m_adc, m_mqtt, m_msg, ADC_API_ESP32::measureValue(), mqtt_api_v2::publish(), MQTT_Message::toString(), WAIT_DELAY, and Timeservice::wait_ms().
Referenced by run().
run()
void ActiveCurrentSensor::run (void * data) override virtual
Body of the task to execute.
This function must be implemented in the subclass that represents the actual task to run. When a task is started by calling start(), this is the code that is executed in the newly created task. WHY IS IT NOT PRIVATE???
Parameters
[in] data The data passed in to the newly started task.
Implements Task.
Definition at line 51 of file ActiveCurrentSensor.cpp.
 {
     std::string str;
     for(;;)
     {
         if(!m_queue.recieve(&str, 50000)) // we should wait forever here
         {
             // check OTA flag
             // this might be a blocking call ( expected )
             Maintainer::checkOTAUpdate();
             m_isRunning = true;
             // run main function
             main_function();
             m_isRunning = false;
         }
     }
     // exit the thread
     // this->stop();
 }
References Maintainer::checkOTAUpdate(), m_isRunning, m_queue, main_function(), and FreeRTOS::Queue::recieve().
Member Data Documentation
m_adc
ADC_API_ESP32 ActiveCurrentSensor::m_adc private
Definition at line 73 of file ActiveCurrentSensor.hpp.
Referenced by main_function().
m_isRunning
std::atomic<bool> ActiveCurrentSensor::m_isRunning private
Definition at line 76 of file ActiveCurrentSensor.hpp.
Referenced by isRunning(), and run().
m_mqtt
mqtt_api_v2 ActiveCurrentSensor::m_mqtt private
Definition at line 75 of file ActiveCurrentSensor.hpp.
Referenced by main_function().
m_msg
MQTT_Message ActiveCurrentSensor::m_msg private
Definition at line 74 of file ActiveCurrentSensor.hpp.
Referenced by main_function().
m_queue
FreeRTOS::Queue ActiveCurrentSensor::m_queue private
Definition at line 77 of file ActiveCurrentSensor.hpp.
Referenced by activateQueue(), and run().
The documentation for this class was generated from the following files:
Components/Sensor/ActiveCurrentSensor/include/ActiveCurrentSensor.hpp
Components/Sensor/ActiveCurrentSensor/src/ActiveCurrentSensor.cpp