Embedded Library: Task Class Reference
Task Class Reference abstract
Encapsulate a runnable task.
#include <Task.h>
Public Member Functions
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
virtual void run (void *data)=0
Body of the task to execute.
void delay (int ms)
Suspend the task for the specified milliseconds.
Static Private Member Functions
static void runTask (void *pTaskInstance)
Private Attributes
xTaskHandle m_handle
std::string m_taskName
uint16_t m_stackSize
uint8_t m_priority
void * m_taskData
BaseType_t m_coreId
Detailed Description
Encapsulate a runnable task.
This class is designed to be subclassed with the method:
void run(void *data) { ... }
For example:
class CurlTestTask : public Task {
   void run(void *data) {
      // Do something
   }
};
implemented.
Definition at line 44 of file Task.h.
Constructor & Destructor Documentation
Task()
Task::Task (const std::string & taskName = "Task", const uint16_t & stackSize = 10000, const uint8_t & priority = 5)
Create an instance of the task class.
Parameters
[in] taskName The name of the task to create.
[in] stackSize The size of the stack.
Returns
N/A.
Definition at line 19 of file Task.cpp.
     : m_taskName{taskName}, m_stackSize{stackSize}, m_priority{priority}, m_taskData{nullptr}
 {
 #ifdef __ESP32__
     m_handle = nullptr;
     m_coreId = tskNO_AFFINITY;
 #else
     m_coreId = 0;
     m_handle = 0;
 #endif
 } // Task
~Task()
Task::~Task () virtual
Definition at line 31 of file Task.cpp.
 {} // ~Task
Member Function Documentation
delay()
void Task::delay (int ms)
Suspend the task for the specified milliseconds.
Parameters
[in] ms The delay time in milliseconds.
Returns
N/A.
Definition at line 40 of file Task.cpp.
 {
 #ifdef __ESP32__
     ::vTaskDelay(ms / portTICK_PERIOD_MS);
 #endif
 } // delay
run()
virtual void Task::run (void * data) pure virtual
Body of the task to execute.
This function must be implemented in the subclass that represents the actual task to run. When a task is started by calling start(), this is the code that is executed in the newly created task.
Parameters
[in] data The data passed in to the newly started task.
Implemented in Maintainer, and ActiveCurrentSensor.
Referenced by runTask().
runTask()
void Task::runTask (void * pTaskInstance) static private
Static class member that actually runs the target task.
The code here will run on the task thread.
Parameters
[in] pTaskInstance The task to run.
Definition at line 53 of file Task.cpp.
 {
     Task* pTask = static_cast<Task*>(pTaskInstance);
     pTask->run(pTask->m_taskData);
     pTask->stop();
 } // runTask
References m_taskData, run(), and stop().
Referenced by start().
setCore()
void Task::setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
Parameters
[in] coreId The id of the core.
Returns
N/A.
Definition at line 138 of file Task.cpp.
 {
     m_coreId = coreId;
 }
References m_coreId.
setName()
void Task::setName (const std::string & name)
Set the name of the task.
Parameters
[in] name The name for the task.
Returns
N/A.
Definition at line 126 of file Task.cpp.
 {
     m_taskName = name;
 } // setName
References m_taskName.
setPriority()
void Task::setPriority (uint8_t priority)
Set the priority of the task.
Parameters
[in] priority The priority for the task.
Returns
N/A.
Definition at line 115 of file Task.cpp.
 {
     m_priority = priority;
 } // setPriority
References m_priority.
setStackSize()
void Task::setStackSize (uint16_t stackSize)
Set the stack size of the task.
Parameters
[in] stackSize The size of the stack for the task.
Returns
N/A.
Definition at line 104 of file Task.cpp.
 {
     m_stackSize = stackSize;
 } // setStackSize
References m_stackSize.
start()
void Task::start (void * taskData = nullptr)
Start an instance of the task.
Parameters
[in] taskData Data to be passed into the task.
Returns
N/A.
Definition at line 66 of file Task.cpp.
 {
 #ifdef __ESP32__
     if(m_handle != nullptr)
     {
     }
     m_taskData = taskData;
     ::xTaskCreatePinnedToCore((TaskFunction_t)&runTask, m_taskName.c_str(), m_stackSize, this,
                               m_priority, &m_handle, m_coreId);
 #endif
 } // start
References m_coreId, m_handle, m_priority, m_stackSize, m_taskData, m_taskName, and runTask().
stop()
void Task::stop ()
Stop the task.
Returns
N/A.
Definition at line 84 of file Task.cpp.
 {
 #ifdef __ESP32__
     if(m_handle == nullptr)
     {
         return;
     }
     xTaskHandle temp = m_handle;
     m_handle = nullptr;
     ::vTaskDelete(temp);
 #endif
 } // stop
References m_handle, and xTaskHandle.
Referenced by runTask().
Member Data Documentation
m_coreId
BaseType_t Task::m_coreId private
Definition at line 75 of file Task.h.
Referenced by setCore(), and start().
m_handle
xTaskHandle Task::m_handle private
Definition at line 69 of file Task.h.
Referenced by start(), and stop().
m_priority
uint8_t Task::m_priority private
Definition at line 73 of file Task.h.
Referenced by setPriority(), and start().
m_stackSize
uint16_t Task::m_stackSize private
Definition at line 72 of file Task.h.
Referenced by setStackSize(), and start().
m_taskData
void* Task::m_taskData private
Definition at line 74 of file Task.h.
Referenced by runTask(), and start().
m_taskName
std::string Task::m_taskName private
Definition at line 71 of file Task.h.
Referenced by setName(), and start().
The documentation for this class was generated from the following files:
Components/RTOS/FreeRTOS/include/Task.h
Components/RTOS/FreeRTOS/src/Task.cpp