Embedded Library: isAlive_service Class Reference
isAlive_service Class Reference final
#include <isAlive_service.hpp>
Public Member Functions
isAlive_service (const db_id error_id, size_t delay, const db_id isAlive_id)
virtual ~isAlive_service (void)
Public Member Functions inherited from ServiceTimeBase<&Timeservice::wait_sec >
ServiceTimeBase (const MQTT_Message &buffer, const db_id error_id, const size_t delay)
virtual ~ServiceTimeBase (void)
Public Member Functions inherited from ServiceBase< MQTT_Message >
ServiceBase (const MQTT_Message &buffer, const db_id error_id)
Construct a new Service Base object.
virtual ~ServiceBase ()
const auto & isActive () const
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Private Member Functions
general_err_t mainFunction () override
Main function for the derived class to work in It is expected that the function is a single-run function And that it should not be blocking.
Private Attributes
MQTT_Message msg_alive
Additional Inherited Members
Protected Member Functions inherited from ServiceTimeBase<&Timeservice::wait_sec >
void run (void *data) override
loop for the service We are waiting "forever" on a queue recieve When we recieve something we will call the mainFunction() Which should be a single-end run for the derived class if any error happends it will be reported online.
Protected Member Functions inherited from ServiceBase< MQTT_Message >
virtual void setIsActive (bool isActive)
Set the Is Active object.
general_err_t postData (const MQTT_Message &message, const std::string &topic="mqtt/burst_msg")
Function to post data to database.
virtual general_err_t postError (const std::string &message, const general_err_t &err)
Method to post errors to the database.
Protected Attributes inherited from ServiceBase< MQTT_Message >
GPIO_API m_test_pin
const MQTT_Message & m_buffer
db_id m_error_id
Detailed Description
Definition at line 50 of file isAlive_service.hpp.
Constructor & Destructor Documentation
isAlive_service()
isAlive_service::isAlive_service (const db_id error_id, size_t delay, const db_id isAlive_id) inline
Definition at line 56 of file isAlive_service.hpp.
         : ServiceTimeBase<&Timeservice::wait_sec>(MQTT_Message{{db_id::CCTV01_DEBUG4, 1}}, error_id,
                                                   delay),
           msg_alive{{isAlive_id, 1}}
     {
         this->postError("[isAlive_service] :: Just rebooted", GE_OK);
     };
References CCTV01_DEBUG4.
~isAlive_service()
virtual isAlive_service::~isAlive_service (void) inline virtual
Definition at line 63 of file isAlive_service.hpp.
 {};
Member Function Documentation
mainFunction()
general_err_t isAlive_service::mainFunction () override private virtual
Main function for the derived class to work in It is expected that the function is a single-run function And that it should not be blocking.
Returns
general_err_t
Implements ServiceTimeBase<&Timeservice::wait_sec >.
Definition at line 29 of file isAlive_service.cpp.
 {
 #ifdef DEBUG
     std::cout << " >> isAlive_service::mainFunction >> \n";
 #endif
     // do magic
     std::cout << " sending isAlive signal \n";
     msg_alive.addData(10);
     postData(msg_alive);
     msg_alive.clear();
 #ifdef DEBUG
     std::cout << " << isAlive_service::mainFunction << \n";
 #endif
     return GE_OK;
 }
References MQTT_Message::addData(), MQTT_Message::clear(), GE_OK, msg_alive, and ServiceBase< MQTT_Message >::postData().
Member Data Documentation
msg_alive
MQTT_Message isAlive_service::msg_alive private
Definition at line 67 of file isAlive_service.hpp.
Referenced by mainFunction().
The documentation for this class was generated from the following files:
Components/Service/isAlive/include/isAlive_service.hpp
Components/Service/isAlive/src/isAlive_service.cpp