Embedded Library: mqtt_api_v2 Class Reference
mqtt_api_v2 Class Reference
#include <mqtt_api_v2.hpp>
Public Member Functions
mqtt_api_v2 (const std::string &uri=GLOBAL_MQTT_SERVER)
~mqtt_api_v2 ()
general_err_t publish (const std::string &topic, const std::string &payload)
FreeRTOS::Semaphore * subscribe (const std::string &topic)
general_err_t subscribe (const std::string &topic, general_err_t(*callbackfunction)(const char *data, const size_t data_length))
general_err_t getData (std::string *str)
Private Member Functions
general_err_t connect (void)
general_err_t disconnect (void)
Static Private Member Functions
static general_err_t handle_event (const char *topic, const size_t topic_length, const char *data, const size_t data_length)
Private Attributes
std::string m_uri
Detailed Description
Definition at line 95 of file mqtt_api_v2.hpp.
Constructor & Destructor Documentation
mqtt_api_v2()
mqtt_api_v2::mqtt_api_v2 (const std::string & uri = GLOBAL_MQTT_SERVER)
Definition at line 47 of file mqtt_api_v2.cpp.
                                              : m_uri{uri}
 {
     if(!m_initialized)
     {
         m_initialized = true;
         auto err = connect();
         if(!General_Error::check_error(err, "Cant initialize mqtt"))
         {
             exit(-1);
         }
         m_semaphore_subscribe.give();
         m_semaphore.give();
     }
 }
~mqtt_api_v2()
mqtt_api_v2::~mqtt_api_v2 ()
Definition at line 63 of file mqtt_api_v2.cpp.
 {}
Member Function Documentation
connect()
general_err_t mqtt_api_v2::connect (void) private
Definition at line 65 of file mqtt_api_v2.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MQTT_API::connect >> ");
 #endif
 #ifdef __ESP32__
     esp_mqtt_client_config_t mqtt_cfg = {
         .uri = m_uri.c_str(),
     };
     m_mqtt_cfg = mqtt_cfg;
     m_client = esp_mqtt_client_init(&m_mqtt_cfg);
     auto err = esp_mqtt_client_register_event(m_client, (esp_mqtt_event_id_t)ESP_EVENT_ANY_ID,
                                               &(mqtt_api_v2::mqtt_event_handler), m_client);
     if(err != ESP_OK)
     {
         return GE_FAIL;
     }
     err = esp_mqtt_client_start(m_client);
     if(err != ESP_OK)
     {
         return GE_FAIL;
     }
 #endif
 #ifdef __UNITTEST__
     m_connected = true;
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MQTT_API::connect << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, LOG_PRINT_INFO, LOG_TAG, m_client, m_connected, and m_uri.
disconnect()
general_err_t mqtt_api_v2::disconnect (void) private
Definition at line 106 of file mqtt_api_v2.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MQTT_API::disconnect >> ");
 #endif
     // Executable code:
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MQTT_API::disconnect << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
getData()
general_err_t mqtt_api_v2::getData (std::string * str)
Definition at line 249 of file mqtt_api_v2.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> mqtt_api_v2::getData >> ");
 #endif
     // Executable code:
     if(!m_connected)
     {
         return GE_NOT_CONNECTED;
     }
     if(!m_isSubscribed)
     {
         return GE_FAIL;
     }
     *str = m_data_recieved;
     if(!m_semaphore_subscribe.take(500, "subscribe init"))
     {
         return GE_SEMAPHORE_NOT_TAKEN;
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< mqtt_api_v2::getData << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_NOT_CONNECTED, GE_OK, GE_SEMAPHORE_NOT_TAKEN, LOG_PRINT_INFO, LOG_TAG, m_connected, m_data_recieved, m_isSubscribed, m_semaphore_subscribe, and FreeRTOS::Semaphore::take().
handle_event()
general_err_t mqtt_api_v2::handle_event (const char * topic, const size_t topic_length, const char * data, const size_t data_length) static private
Definition at line 219 of file mqtt_api_v2.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> mqtt_api_v2::handle_event >> ");
 #endif
     // Executable code:
     std::string topic_string{topic, topic_length};
     std::cout << " recieved topic is : " << topic_string << "\n";
     // lets make sure that we have the topic in our map
     if(mqtt_subscriber_pointer_map.end() == mqtt_subscriber_pointer_map.find(topic_string))
     {
         // we could not find the topic
         std::cout << " topic not found : " << topic_string << "\n";
         return GE_FAIL;
     }
     // if we do, lets call the callback function
     auto err = mqtt_subscriber_pointer_map.at(topic_string)(data, data_length);
     if(err != GE_OK)
     {
         return err;
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< mqtt_api_v2::handle_event << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, LOG_PRINT_INFO, LOG_TAG, and mqtt_subscriber_pointer_map.
publish()
general_err_t mqtt_api_v2::publish (const std::string & topic, const std::string & payload)
Definition at line 120 of file mqtt_api_v2.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> MQTT_API::publish >> ");
 #endif
     // Executable code:
     if(!m_connected)
     {
         return GE_NOT_CONNECTED;
     }
     if(!m_semaphore.take(500, "publish"))
     {
         return GE_SEMAPHORE_NOT_TAKEN;
     }
 #ifdef __ESP32__
     esp_mqtt_client_publish(m_client, topic.c_str(), payload.c_str(), payload.size(), 1, 0);
 #endif
     m_semaphore.give();
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< MQTT_API::publish << ");
 #endif
     return GE_OK;
 }
References GE_NOT_CONNECTED, GE_OK, GE_SEMAPHORE_NOT_TAKEN, FreeRTOS::Semaphore::give(), LOG_PRINT_INFO, LOG_TAG, m_client, m_connected, m_semaphore, and FreeRTOS::Semaphore::take().
Referenced by ActiveCurrentSensor::main_function(), SensorControllerBase::postData(), ServiceBase< MQTT_Message >::postData(), ErrorCodeParser::postToMqtt(), and hal_mqtt_log::write().
subscribe() [1/2]
FreeRTOS::Semaphore * mqtt_api_v2::subscribe (const std::string & topic)
Attention
THIS IS A SINGLETON FUNCTION WITH ONE (1) SUBSCRIBER UNIT
Parameters
[in]
Definition at line 165 of file mqtt_api_v2.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> mqtt_api_v2::subscribe >> ");
 #endif
     // take the semaphore
     if(!m_semaphore_subscribe.take(500, "subscribe init"))
     {
         return nullptr;
     }
     std::cout << " subsribing to topic : " << topic << "\n";
 #ifdef __ESP32__
     esp_mqtt_client_subscribe(m_client, topic.c_str(), 0);
 #endif
 #ifdef __UNITTEST__
     // we are now subscribed
     m_isSubscribed = true;
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< mqtt_api_v2::subscribe << ");
 #endif
     // return a pointer of the semaphore for subscibtion handling
     return &m_semaphore_subscribe;
 }
References LOG_PRINT_INFO, LOG_TAG, m_client, m_isSubscribed, m_semaphore_subscribe, and FreeRTOS::Semaphore::take().
subscribe() [2/2]
general_err_t mqtt_api_v2::subscribe (const std::string & topic, general_err_t(*)(const char *data, const size_t data_length) callbackfunction)
Definition at line 193 of file mqtt_api_v2.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> mqtt_api_v2::getData >> ");
 #endif
     // Executable code:
 #ifdef __ESP32__
     auto err = esp_mqtt_client_subscribe(m_client, topic.c_str(), 0);
     if(err != ESP_OK)
     {
         return GE_FAIL;
     }
 #endif
     mqtt_subscriber_pointer_map.insert(
         std::pair<const std::string, general_err_t (*)(const char* data, const size_t data_length)>(
             topic, callbackfunction));
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< mqtt_api_v2::getData << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, LOG_PRINT_INFO, LOG_TAG, m_client, and mqtt_subscriber_pointer_map.
Member Data Documentation
m_uri
std::string mqtt_api_v2::m_uri private
Definition at line 115 of file mqtt_api_v2.hpp.
Referenced by connect().
The documentation for this class was generated from the following files:
Components/Protocols/MQTT/include/mqtt_api_v2.hpp
Components/Protocols/MQTT/src/mqtt_api_v2.cpp