Embedded Library: Maintainer Class Reference
Maintainer Class Reference final
#include <Maintainer.hpp>
Public Member Functions
Maintainer (const wifi_conf_t &wifi_conf, const db_id &error_id, bool withPeriodicReboot=true, size_t delay_sec=60, int priority=2)
~Maintainer ()
void run (void *data) override
Body of the task to execute.
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Static Public Member Functions
static general_err_t install_system_test_fuction (bool(*callbackfunction)(void))
install a function for the test service in order to periodically check that everything is working as intended.
static general_err_t checkOTAUpdate (void)
static bool isOTAUpdateStarted (void)
Private Member Functions
general_err_t periodic_restart (void)
a private function to make sure the sensors are restarted every 6th hour.
general_err_t check_system_functions (void)
a private function which is called periodically to check the vector of function pointers
Private Attributes
Fault_Handler m_faulthandler
uint64_t start_time
size_t m_delay_sec
WiFi_SAL_esp32 m_wifi
const db_id m_error_id
const bool m_withPeriodicReboot
Detailed Description
Definition at line 87 of file Maintainer.hpp.
Constructor & Destructor Documentation
Maintainer()
Maintainer::Maintainer (const wifi_conf_t & wifi_conf, const db_id & error_id, bool withPeriodicReboot = true, size_t delay_sec = 60, int priority = 2) explicit
Definition at line 40 of file Maintainer.cpp.
     : m_faulthandler{"Maintainer"}, m_delay_sec{delay_sec}, m_wifi{wifi_conf}, m_error_id{error_id},
       m_withPeriodicReboot{withPeriodicReboot}
 {
     setPriority(priority);
     setName("Maintainer");
 #ifdef __UNITTEST__
     return;
 #endif
     auto err = m_wifi.connect();
     if(err != GE_OK)
     {
         std::cout << "[Maintainer] not able to connect to wifi, rebooting ...\n";
         Timeservice::wait_ms(1000);
         exit(-1);
     }
     size_t count = 1;
     do
     {
         std::cout << "[Maintainer] setting up sntp, attempt <" << (int)count << "/3> ...\n";
         err = Timeservice::initialize_sntp();
         Timeservice::wait_ms(1000);
     } while(err != GE_OK && count++ < 3);
     if(err != GE_OK)
     {
         std::cout << "[Maintainer] not able to get RTC, rebooting ...\n";
         Timeservice::wait_ms(1000);
         exit(-1);
     }
     std::cout << "[Maintainer] sntp successfully initialized in  <" << (int)count
               << "> attempts ...\n";
     start_time = Timeservice::getTimeNow();
 #ifdef __WITH_OTA__
     // in the maintainer class, we want to enable OTA service. In this point of the code we are sure
     // that we have a WiFi access, therefor we can safly start the service:
     m_mqtt.subscribe(MQTT_OTA_TOPIC, &(OTA::update));
 #endif
     ErrorCodeParser::postToMqtt(m_error_id, GE_TIMEOUT, "[Maintainer]:: We have just restarted");
 }
~Maintainer()
Maintainer::~Maintainer ()
Definition at line 83 of file Maintainer.cpp.
 {}
Member Function Documentation
check_system_functions()
general_err_t Maintainer::check_system_functions (void) private
a private function which is called periodically to check the vector of function pointers
Attention
if any tests fails we log it and restart
Returns
GE_OK
Definition at line 169 of file Maintainer.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Maintainer::check_system_functions >> ");
 #endif
     // Executable code:
     for(const auto& ele : maintainer_pointer_vec)
     {
         if(!ele())
         {
             m_faulthandler.handleFault({FaultHandler_n::severity::very_high,
                                         "Maintainer::check_system_functions",
                                         "A fault has been detected in the system checks!"});
             ErrorCodeParser::postToMqtt(m_error_id, GE_FAIL,
                                         "Function 'check_system_functions' failed to execute");
             return GE_FAIL;
         }
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Maintainer::check_system_functions << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, Fault_Handler::handleFault(), LOG_PRINT_INFO, LOG_TAG, m_error_id, m_faulthandler, maintainer_pointer_vec, ErrorCodeParser::postToMqtt(), and FaultHandler_n::very_high.
Referenced by run().
checkOTAUpdate()
general_err_t Maintainer::checkOTAUpdate (void) static
This function might be thread blocking if OTA update is in progress We want to use this function to test for OTA updates, if an update is in progress we want to make sure no other task is running.
Attention
: might be a blocking call
Definition at line 197 of file Maintainer.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Maintainer::checkOTAUpdate >> ");
 #endif
     // Executable code:
     if(Maintainer::isOTAUpdateStarted())
     {
         Timeservice::wait_ms(50000);
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Maintainer::checkOTAUpdate << ");
 #endif
     return GE_OK;
 }
References GE_OK, isOTAUpdateStarted(), LOG_PRINT_INFO, LOG_TAG, and Timeservice::wait_ms().
Referenced by ActiveCurrentSensor::run().
install_system_test_fuction()
general_err_t Maintainer::install_system_test_fuction (bool(*)(void) callbackfunction) static
install a function for the test service in order to periodically check that everything is working as intended.
Attention
The function must return a boolean with the definition : True -> test has passed, everything is working. False -> test has failed, we need to restart.
Parameters
[in] bool (*callbackfunction)(void)
Returns
GE_OK
Definition at line 99 of file Maintainer.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> enclosing_method >> ");
 #endif
     // Executable code:
     maintainer_pointer_vec.push_back(callbackfunction);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< enclosing_method << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, LOG_TAG, and maintainer_pointer_vec.
Referenced by TEST().
isOTAUpdateStarted()
static bool Maintainer::isOTAUpdateStarted (void) inline static
This function will return the status of the OTA_Update_flag, it is static because we want to be able to call this function as a standard wait
Definition at line 112 of file Maintainer.hpp.
     {
         return OTA::isUpdateStarted();
     }
References OTA::isUpdateStarted().
Referenced by checkOTAUpdate().
periodic_restart()
general_err_t Maintainer::periodic_restart (void) private
a private function to make sure the sensors are restarted every 6th hour.
Attention
Returns
GE_OK
Definition at line 138 of file Maintainer.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Maintainer::periodic_restart >> ");
 #endif
     // Executable code:
     if(Timeservice::getTimeNow() - start_time > PERIODIC_RESTART_TIME)
     {
         m_faulthandler.handleFault(
             {FaultHandler_n::severity::very_high, "periodic_restart", "We are forcing a restart"});
         ErrorCodeParser::postToMqtt(m_error_id, GE_TIMEOUT, "We are forcing a restart");
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Maintainer::periodic_restart << ");
 #endif
     return GE_OK;
 }
References GE_OK, GE_TIMEOUT, Timeservice::getTimeNow(), Fault_Handler::handleFault(), LOG_PRINT_INFO, LOG_TAG, m_error_id, m_faulthandler, PERIODIC_RESTART_TIME, ErrorCodeParser::postToMqtt(), start_time, and FaultHandler_n::very_high.
Referenced by run().
run()
void Maintainer::run (void * data) override virtual
Body of the task to execute.
This function must be implemented in the subclass that represents the actual task to run. When a task is started by calling start(), this is the code that is executed in the newly created task. WHY IS IT NOT PRIVATE???
Parameters
[in] data The data passed in to the newly started task.
Implements Task.
Definition at line 115 of file Maintainer.cpp.
 {
     for(;;)
     {
         Timeservice::wait_sec(m_delay_sec);
         check_system_functions();
         if(m_withPeriodicReboot)
         {
             periodic_restart();
         }
     }
 }
References check_system_functions(), m_delay_sec, m_withPeriodicReboot, periodic_restart(), and Timeservice::wait_sec().
Member Data Documentation
m_delay_sec
size_t Maintainer::m_delay_sec private
Definition at line 122 of file Maintainer.hpp.
Referenced by run().
m_error_id
const db_id Maintainer::m_error_id private
Definition at line 125 of file Maintainer.hpp.
Referenced by check_system_functions(), and periodic_restart().
m_faulthandler
Fault_Handler Maintainer::m_faulthandler private
Definition at line 120 of file Maintainer.hpp.
Referenced by check_system_functions(), and periodic_restart().
m_wifi
WiFi_SAL_esp32 Maintainer::m_wifi private
Definition at line 124 of file Maintainer.hpp.
m_withPeriodicReboot
const bool Maintainer::m_withPeriodicReboot private
Definition at line 126 of file Maintainer.hpp.
Referenced by run().
start_time
uint64_t Maintainer::start_time private
Definition at line 121 of file Maintainer.hpp.
Referenced by periodic_restart().
The documentation for this class was generated from the following files:
Components/Objects/Maintainer/include/Maintainer.hpp
Components/Objects/Maintainer/src/Maintainer.cpp