Embedded Library: Message_Handler Class Reference
Message_Handler Class Reference
#include <Message_Handler.hpp>
Static Public Member Functions
static general_err_t to_Postgres_Format (const Message_Protocol &msg, std::string *str)
Convert the message to a postgres sql format.
static const std::string to_Postgres_Form (const Message_Protocol &msg)
static std::string postgres_start (void)
static const std::string to_Postgres_Subject (const Message_Protocol &msg)
static std::string postgres_append (void)
static std::string postgres_end (void)
Detailed Description
Definition at line 74 of file Message_Handler.hpp.
Member Function Documentation
postgres_append()
static std::string Message_Handler::postgres_append (void) inline static
Definition at line 86 of file Message_Handler.hpp.
     {
         return ",";
     };
postgres_end()
static std::string Message_Handler::postgres_end (void) inline static
Definition at line 90 of file Message_Handler.hpp.
     {
         return ";";
     };
postgres_start()
static std::string Message_Handler::postgres_start (void) inline static
Definition at line 80 of file Message_Handler.hpp.
     {
         return "INSERT INTO MEASUREMENTS (tstz,sensor_id,value) VALUES ";
     };
to_Postgres_Form()
const std::string Message_Handler::to_Postgres_Form (const Message_Protocol & msg) static
Definition at line 96 of file Message_Handler.cpp.
 {
     std::string str;
     // Executable code:
     if(!msg.isValid())
     {
         std::cout << "NOT VALID DATA \n";
         return "";
     }
     if(msg.getBuffer().size() > MAX_SIZE)
     {
         std::cout << "BUFFER OVERFLOW \n";
         return "";
     }
     tm* time_now = gmtime(&msg.getBuffer().at(0).time_stamp.tv_sec);
     char buffer[80];
     strftime(buffer, 80, "'%Y-%m-%dT%H:%M:%S", time_now);
     char currentTime[84] = "";
     sprintf(currentTime, "%s.%ldZ'", buffer, (msg.getBuffer().at(0).time_stamp.tv_usec));
     str.append("INSERT INTO public.datapoints (tstz,entity_id,value) VALUES(");
     // timestamp
     str.append(currentTime);
     str.append(",");
     // Sensor id
     str.append(std::to_string(msg.getControl().id));
     str.append(",");
     // data, with 4 precision
     str.append(std::to_string(msg.getBuffer().at(0).data));
     str.append(");");
     return str;
 }
References Message_Protocol::getBuffer(), Message_Protocol::getControl(), msg_control_t::id, Message_Protocol::isValid(), and MAX_SIZE.
to_Postgres_Format()
general_err_t Message_Handler::to_Postgres_Format (const Message_Protocol & msg, std::string * str) static
Convert the message to a postgres sql format.
Parameters
[in] const Message_Protocol& msg
[in]
Definition at line 52 of file Message_Handler.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Message_Handler::to_Postgres_Format >> ");
 #endif
     // Executable code:
     // Executable code:
     if(!msg.isValid())
     {
         return GE_EMPTY;
     }
     if(msg.getBuffer().size() > MAX_SIZE)
     {
         return GE_OVERFLOW;
     }
     // clear the string
     str->clear();
     tm* time_now = gmtime(&msg.getBuffer().at(0).time_stamp.tv_sec);
     char buffer[80];
     strftime(buffer, 80, "'%Y-%m-%dT%H:%M:%S", time_now);
     char currentTime[84] = "";
     sprintf(currentTime, "%s.%ldZ'", buffer, (msg.getBuffer().at(0).time_stamp.tv_usec));
     str->append("INSERT INTO public.datapoints (tstz,entity_id,value) VALUES(");
     // timestamp
     str->append(currentTime);
     str->append(",");
     // Sensor id
     str->append(std::to_string(msg.getControl().id));
     str->append(",");
     // data, with 4 precision
     str->append(std::to_string(msg.getBuffer().at(0).data));
     str->append(");");
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Message_Handler::to_Postgres_Format << ");
 #endif
     return GE_OK;
 }
References GE_EMPTY, GE_OK, GE_OVERFLOW, Message_Protocol::getBuffer(), Message_Protocol::getControl(), msg_control_t::id, Message_Protocol::isValid(), LOG_PRINT_INFO, LOG_TAG, and MAX_SIZE.
to_Postgres_Subject()
const std::string Message_Handler::to_Postgres_Subject (const Message_Protocol & msg) static
Definition at line 133 of file Message_Handler.cpp.
 {
     std::string str;
     // Executable code:
     if(!msg.isValid())
     {
         std::cout << "NOT VALID DATA \n";
         return "";
     }
     if(msg.getBuffer().size() > MAX_SIZE)
     {
         std::cout << "BUFFER OVERFLOW \n";
         return "";
     }
     tm* time_now = gmtime(&msg.getBuffer().at(0).time_stamp.tv_sec);
     char buffer[80];
     strftime(buffer, 80, "'%Y-%m-%dT%H:%M:%S", time_now);
     char currentTime[84] = "";
     sprintf(currentTime, "%s.%ldZ'", buffer, (msg.getBuffer().at(0).time_stamp.tv_usec));
     str.append("(");
     // timestamp
     str.append(currentTime);
     str.append(",");
     // Sensor id
     str.append(std::to_string(msg.getControl().id));
     str.append(",");
     // data, with 4 precision
     str.append(std::to_string(msg.getBuffer().at(0).data));
     str.append(")");
     return str;
 }
References Message_Protocol::getBuffer(), Message_Protocol::getControl(), msg_control_t::id, Message_Protocol::isValid(), and MAX_SIZE.
The documentation for this class was generated from the following files:
Components/Objects/Message/include/Message_Handler.hpp
Components/Objects/Message/src/Message_Handler.cpp