Embedded Library: Sensor_Base< T, U > Class Template Reference
Sensor_Base< T, U > Class Template Reference abstract
#include <Sensor_Base.hpp>
Public Member Functions
Sensor_Base (const T &conf, const std::string &class_name="N/A")
virtual ~Sensor_Base ()
virtual general_err_t measure (void)=0
const U & getValue (void)
const U & handleSensor (void)
Protected Attributes
U m_value = 0
T m_conf
Fault_Handler m_faultHanlder
Detailed Description
template<typename T, typename U>
class Sensor_Base< T, U >
Definition at line 80 of file Sensor_Base.hpp.
Constructor & Destructor Documentation
Sensor_Base()
template<typename T , typename U > Sensor_Base< T, U >::Sensor_Base (const T & conf, const std::string & class_name = "N/A") inline
Definition at line 83 of file Sensor_Base.hpp.
         : m_value{0}, m_conf{conf}, m_faultHanlder{class_name} {};
~Sensor_Base()
template<typename T , typename U > virtual Sensor_Base< T, U >::~Sensor_Base () inline virtual
Definition at line 85 of file Sensor_Base.hpp.
 {};
Member Function Documentation
getValue()
template<typename T , typename U > const U& Sensor_Base< T, U >::getValue (void) inline
Definition at line 88 of file Sensor_Base.hpp.
     {
         return m_value;
     };
References Sensor_Base< T, U >::m_value.
Referenced by Sensor_Base< T, U >::handleSensor().
handleSensor()
template<typename T , typename U > const U& Sensor_Base< T, U >::handleSensor (void) inline
Definition at line 96 of file Sensor_Base.hpp.
     {
         return measure() == GE_OK ? getValue() : 0;
     }
References GE_OK, Sensor_Base< T, U >::getValue(), and Sensor_Base< T, U >::measure().
measure()
template<typename T , typename U > virtual general_err_t Sensor_Base< T, U >::measure (void) pure virtual
Referenced by Sensor_Base< T, U >::handleSensor().
Member Data Documentation
m_conf
template<typename T , typename U > T Sensor_Base< T, U >::m_conf protected
Definition at line 103 of file Sensor_Base.hpp.
m_faultHanlder
template<typename T , typename U > Fault_Handler Sensor_Base< T, U >::m_faultHanlder protected
Definition at line 104 of file Sensor_Base.hpp.
m_value
template<typename T , typename U > U Sensor_Base< T, U >::m_value = 0 protected
Definition at line 102 of file Sensor_Base.hpp.
Referenced by Sensor_Base< T, U >::getValue().
The documentation for this class was generated from the following file:
Components/Interfaces/SensorBase/include/Sensor_Base.hpp