Embedded Library: Curl_SAL Class Reference
Curl_SAL Class Reference
#include <Curl_SAL.hpp>
Public Member Functions
Curl_SAL (const std::string &server)
~Curl_SAL ()
general_err_t initialize (void)
initialize the block
general_err_t open (void)
Open the connection.
general_err_t close (void)
Close the connection.
general_err_t post (const std::string &str)
publish the content
Private Attributes
const std::string m_server
Detailed Description
Definition at line 79 of file Curl_SAL.hpp.
Constructor & Destructor Documentation
Curl_SAL()
Curl_SAL::Curl_SAL (const std::string & server) explicit
Definition at line 41 of file Curl_SAL.cpp.
 : m_server{server} {}
~Curl_SAL()
Curl_SAL::~Curl_SAL ()
Definition at line 43 of file Curl_SAL.cpp.
 {
 #ifdef __WITH_DATABASE__
     /* always cleanup */
     curl_easy_cleanup(m_curl);
     curl_global_cleanup();
 #endif
 }
Member Function Documentation
close()
general_err_t Curl_SAL::close (void)
Close the connection.
Returns
GE_OK
Definition at line 114 of file Curl_SAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Curl_SAL::rpi_publish >> ");
 #endif
     // Executable code:
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Curl_SAL::rpi_publish << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by http_interface::close().
initialize()
general_err_t Curl_SAL::initialize (void)
initialize the block
Returns
GE_OK
Definition at line 59 of file Curl_SAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Curl_SAL::initialize >> ");
 #endif
     // Executable code:
 #ifdef __WITH_DATABASE__
     /* In windows, this will init the winsock stuff */
     curl_global_init(CURL_GLOBAL_ALL);
     /* get a curl handle */
     m_curl = curl_easy_init();
     // set timeout for db connection
     curl_easy_setopt(m_curl, CURLOPT_CONNECTTIMEOUT, DB_CONNECTION_TIMEOUT);
     curl_easy_setopt(m_curl, CURLOPT_TIMEOUT, DB_SEND_TIMEOUT);
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Curl_SAL::initialize << ");
 #endif
     return GE_OK;
 }
References DB_CONNECTION_TIMEOUT, DB_SEND_TIMEOUT, GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by http_interface::initialize().
open()
general_err_t Curl_SAL::open (void)
Open the connection.
Attention
Returns
GE_OK
Definition at line 92 of file Curl_SAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Curl_SAL::rpi_close >> ");
 #endif
     // Executable code:
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Curl_SAL::rpi_close << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by http_interface::open().
post()
general_err_t Curl_SAL::post (const std::string & str)
publish the content
Attention
Parameters
[in] const std::string& str
Returns
GE_OK
Definition at line 139 of file Curl_SAL.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Curl_SAL::rpi_publish >> ");
 #endif
     // Executable code:
 #ifdef __WITH_DATABASE__
     CURLcode res;
     if(m_curl)
     {
         /* First set the URL that is about to receive our POST. This URL can
            just as well be a https:// URL if that is what should receive the
            data. */
 #endif
         // load server
         std::string local_server = m_server;
         // append http url
         local_server.append(str.c_str());
         std::cout << local_server << "\n";
 #ifdef __WITH_DATABASE__
         // send url to curl
         curl_easy_setopt(m_curl, CURLOPT_URL, local_server.c_str());
         /* Perform the request, res will get the return code */
         res = curl_easy_perform(m_curl);
         /* Check for errors */
         if(res != CURLE_OK)
         {
             fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));
             // return sad
             return GE_FAIL;
         }
     }
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Curl_SAL::rpi_publish << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, LOG_PRINT_INFO, LOG_TAG, and m_server.
Referenced by http_interface::post().
Member Data Documentation
m_server
const std::string Curl_SAL::m_server private
Definition at line 93 of file Curl_SAL.hpp.
Referenced by post().
The documentation for this class was generated from the following files:
Components/Protocols/HTTP/include/Curl_SAL.hpp
Components/Protocols/HTTP/src/Curl_SAL.cpp