Embedded Library: esp32Cam Class Reference
esp32Cam Class Reference
#include <esp32Cam.hpp>
Public Member Functions
general_err_t takePicture ()
This function takes a picture with the esp32 camera.
camera_fb_t * getPicture ()
Get the Picture object.
general_err_t releasePicture ()
release the image buffer
general_err_t getJPGPicture (uint8_t *out, size_t *length)
get the picture in JPG format
Static Public Member Functions
static esp32Cam & Instance ()
Singleton - constructor, this ensures us that only ONE(1) instance of esp32cam exists.
static general_err_t reboot_camera ()
reboot the camera
Private Member Functions
esp32Cam ()
~esp32Cam ()
Static Private Member Functions
static general_err_t init_camera ()
static general_err_t deinit_camera ()
Private Attributes
bool m_hasImageBeenReleased
camera_fb_t * m_pic
Detailed Description
Definition at line 67 of file esp32Cam.hpp.
Constructor & Destructor Documentation
esp32Cam()
esp32Cam::esp32Cam () inline private
Definition at line 123 of file esp32Cam.hpp.
                       : m_hasImageBeenReleased{true}, m_pic{nullptr}
     {
         auto err = init_camera();
         if(err != GE_OK)
         {
             Timeservice::wait_sec(5);
             exit(-1);
         }
     };
~esp32Cam()
esp32Cam::~esp32Cam () inline private
Definition at line 132 of file esp32Cam.hpp.
 {};
Member Function Documentation
deinit_camera()
general_err_t esp32Cam::deinit_camera () static private
Definition at line 196 of file esp32Cam.cpp.
 {
     auto err = GE_OK;
 #ifdef __ESP32__
     err = esp_camera_deinit() == ESP_OK ? GE_OK : GE_FAIL;
 #endif
     return err;
 }
References GE_FAIL, and GE_OK.
Referenced by reboot_camera().
getJPGPicture()
general_err_t esp32Cam::getJPGPicture (uint8_t * out, size_t * length)
get the picture in JPG format
Warning
we are using pointers here since the underlying SDK is requesting it
Parameters
out
length
Returns
general_err_t
Definition at line 166 of file esp32Cam.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> esp32Cam::getJPGPicture >> ");
 #endif
     // Executable code:
     // Executable code:
     if(m_hasImageBeenReleased)
     {
 #ifdef DEBUG
         std::cout << "Nothing to be returned! \n";
 #endif
         return GE_NO_DATA;
     }
 #ifdef __ESP32__
     if(!frame2jpg(m_pic, 80, &out, length))
     {
 #ifdef DEBUG
         std::cout << "Nothing to be returned! \n";
 #endif
         return GE_NO_DATA;
     }
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  esp32Cam::getJPGPicture << ");
 #endif
     return GE_OK;
 }
References GE_NO_DATA, GE_OK, LOG_PRINT_INFO, LOG_TAG, m_hasImageBeenReleased, and m_pic.
getPicture()
camera_fb_t * esp32Cam::getPicture ()
Get the Picture object.
Warning
This is a raw pointer, and should have been implemented as a smartpointer
Returns
camera_fb_t*
Definition at line 146 of file esp32Cam.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> esp32Cam::fcn >> ");
 #endif
     // Executable code:
     if(m_hasImageBeenReleased)
     {
 #ifdef DEBUG
         std::cout << "Nothing to be returned! \n";
 #endif
         return nullptr;
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  esp32Cam::fcn << ");
 #endif
     return m_pic;
 }
References LOG_PRINT_INFO, LOG_TAG, m_hasImageBeenReleased, and m_pic.
init_camera()
general_err_t esp32Cam::init_camera () static private
Definition at line 100 of file esp32Cam.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> esp32Cam::init_camera >> ");
 #endif
 // Executable code:
 #ifdef __ESP32__
     auto esp_err = esp_camera_init(&camera_config);
     if(esp_err != ESP_OK)
     {
         std::cout << " esp error is : " << (int)esp_err << "\n";
         return GE_FAIL;
     }
 #endif
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  esp32Cam::init_camera << ");
 #endif
     return GE_OK;
 }
References GE_FAIL, GE_OK, LOG_PRINT_INFO, and LOG_TAG.
Referenced by reboot_camera().
Instance()
static esp32Cam& esp32Cam::Instance () inline static
Singleton - constructor, this ensures us that only ONE(1) instance of esp32cam exists.
Returns
esp32Cam&
Definition at line 78 of file esp32Cam.hpp.
     {
         static esp32Cam instance;
         return instance;
     }
Referenced by TEST(), and TEST_GROUP().
reboot_camera()
general_err_t esp32Cam::reboot_camera () static
reboot the camera
Returns
general_err_t
Definition at line 205 of file esp32Cam.cpp.
 {
     std::cout << " rebooting camera ... \n";
     std::cout << " ... deinit ... \n";
     auto err = deinit_camera();
     if(err != GE_OK)
     {
         std::cout << " failed to deinit ...  we reboot\n";
         exit(-1);
     }
     std::cout << " deinit OK \n";
     std::cout << " init camera \n";
     err = init_camera();
     if(err != GE_OK)
     {
         std::cout << " failed to init ...  we reboot\n";
         exit(-1);
     }
     return GE_OK;
 }
References deinit_camera(), GE_OK, and init_camera().
releasePicture()
general_err_t esp32Cam::releasePicture ()
release the image buffer
Warning
it is required to call this whenever the prior image is not longer needed. We are blocking the opotunity to retrieve another image as long as this has not been called
Returns
general_err_t
Definition at line 122 of file esp32Cam.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> esp32Cam::fcn >> ");
 #endif
     if(m_hasImageBeenReleased)
     {
 #ifdef DEBUG
         std::cout << "Nothing to be released! \n";
 #endif
         return GE_NO_DATA;
     }
     // Executable code:
 #ifdef __ESP32__
     esp_camera_fb_return(m_pic);
 #endif
     m_hasImageBeenReleased = true;
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  esp32Cam::fcn << ");
 #endif
     return GE_OK;
 }
References GE_NO_DATA, GE_OK, LOG_PRINT_INFO, LOG_TAG, m_hasImageBeenReleased, and m_pic.
Referenced by TEST(), and TEST_GROUP().
takePicture()
general_err_t esp32Cam::takePicture ()
This function takes a picture with the esp32 camera.
Returns
: error code based on result
Definition at line 68 of file esp32Cam.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> esp32Cam::fcn>> ");
 #endif
     // Executable code:
     std::cout << "taking a picture! \n";
     if(!m_hasImageBeenReleased)
     {
 #ifdef DEBUG
         std::cout << "We have not released the previous image!!! \n";
 #endif
         return GE_NOT_READY;
     }
 #ifdef __ESP32__
     m_pic = esp_camera_fb_get();
 #endif
     m_hasImageBeenReleased = false;
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  esp32Cam:: << ");
 #endif
 #ifdef __UNITTEST__
     return GE_OK;
 #endif
     return m_pic == NULL ? GE_NO_DATA : GE_OK;
 }
References GE_NO_DATA, GE_NOT_READY, GE_OK, LOG_PRINT_INFO, LOG_TAG, m_hasImageBeenReleased, and m_pic.
Referenced by TEST().
Member Data Documentation
m_hasImageBeenReleased
bool esp32Cam::m_hasImageBeenReleased private
Definition at line 135 of file esp32Cam.hpp.
Referenced by getJPGPicture(), getPicture(), releasePicture(), and takePicture().
m_pic
camera_fb_t* esp32Cam::m_pic private
Definition at line 137 of file esp32Cam.hpp.
Referenced by getJPGPicture(), getPicture(), releasePicture(), and takePicture().
The documentation for this class was generated from the following files:
Components/Sensor/esp32Cam/include/esp32Cam.hpp
Components/Sensor/esp32Cam/src/esp32Cam.cpp