Embedded Library: jsmn_object Class Reference
jsmn_object Class Reference
#include <jsmn_object.hpp>
Static Public Member Functions
static int getParsedIntegerValue (const std::string &str, const std::string &key, const std::uint8_t size=128)
Get the Parsed Integer Value object.
Static Private Member Functions
static int jsoneq (const char *json, jsmntok_t *tok, const char *s)
simple function to compare the Key with the expected within json
static int json2int (const std::string &jsonstring, const jsmntype_t &type, int start, int stop)
simple function to retrive the int value within the json object
Detailed Description
Definition at line 39 of file jsmn_object.hpp.
Member Function Documentation
getParsedIntegerValue()
static int jsmn_object::getParsedIntegerValue (const std::string & str, const std::string & key, const std::uint8_t size = 128) inline static
Get the Parsed Integer Value object.
Parameters
str
key
Returns
int : retunr 0 if fail, parsed value otherwise
Definition at line 52 of file jsmn_object.hpp.
     {
         jsmn_parser p;
         jsmntok_t t[size]; /* We expect no more than 128 JSON tokens */
         jsmn_init(&p);
         auto res = jsmn_parse(&p, str.c_str(), str.size(), t,
                               size); // "s" is the char array holding the json content
         for(size_t i = 1; i < res; i++)
         {
             if(jsoneq(str.c_str(), &t[i], "value") == 0)
             {
                 return json2int(str, t[i + 1].type, t[i + 1].start, t[i + 1].end);
             }
         }
         return 0;
     }
References json2int(), and jsoneq().
Referenced by TEST().
json2int()
static int jsmn_object::json2int (const std::string & jsonstring, const jsmntype_t & type, int start, int stop) inline static private
simple function to retrive the int value within the json object
Parameters
jsonstring : string of the json
type : must be "JSMN_PRIMITIVE" which is either a number or boolean
start : start index within json string
stop : stop index within json string
Returns
int : the value read, return 0 on fail
Definition at line 100 of file jsmn_object.hpp.
     {
         if(type != JSMN_PRIMITIVE)
         {
             return 0; // not a number
         }
         return std::atoi(jsonstring.substr(start, stop - start).c_str());
     }
Referenced by getParsedIntegerValue().
jsoneq()
static int jsmn_object::jsoneq (const char * json, jsmntok_t * tok, const char * s) inline static private
simple function to compare the Key with the expected within json
Parameters
json : json string
tok : token
s : expected key
Returns
int : 1 on true, 0 on false
Definition at line 81 of file jsmn_object.hpp.
     {
         if(tok->type == JSMN_STRING && (int)strlen(s) == tok->end - tok->start &&
            strncmp(json + tok->start, s, tok->end - tok->start) == 0)
         {
             return 0;
         }
         return -1;
     }
Referenced by getParsedIntegerValue().
The documentation for this class was generated from the following file:
Components/Objects/JSMN/include/jsmn_object.hpp