Embedded Library: Components/Sensor/esp32Cam/test/test/esp32Cam_test.cpp File Reference
esp32Cam_test.cpp File Reference
#include "../../include/esp32Cam.hpp"
#include <iostream>
#include "CppUTest/TestHarness.h"
Functions
TEST_GROUP (ESP32CAM_GRP)
TEST (ESP32CAM_GRP, init)
TEST (ESP32CAM_GRP, initx2_fail)
TEST (ESP32CAM_GRP, singleton_initx2_fail)
TEST (ESP32CAM_GRP, singleton_initx2_release_OK)
TEST (ESP32CAM_GRP, release_fail)
TEST (ESP32CAM_GRP, release_OK)
TEST (ESP32CAM_GRP, get_img_fail)
Function Documentation
TEST() [1/7]
TEST (ESP32CAM_GRP , get_img_fail)
Definition at line 89 of file esp32Cam_test.cpp.
 {
     auto img = m_cam.getPicture();
     CHECK_EQUAL(nullptr, img);
 }
TEST() [2/7]
TEST (ESP32CAM_GRP , init)
Definition at line 27 of file esp32Cam_test.cpp.
 {
     auto err = m_cam.takePicture();
     CHECK_EQUAL(GE_OK, err);
 }
References GE_OK.
TEST() [3/7]
TEST (ESP32CAM_GRP , initx2_fail)
Definition at line 33 of file esp32Cam_test.cpp.
 {
     auto err = m_cam.takePicture();
     err = m_cam.takePicture(); // this should fail, because we have not release the image
     CHECK_EQUAL(GE_NOT_READY, err);
 }
References GE_NOT_READY.
TEST() [4/7]
TEST (ESP32CAM_GRP , release_fail)
Definition at line 68 of file esp32Cam_test.cpp.
 {
     auto err = m_cam.releasePicture();
     CHECK_EQUAL(GE_NO_DATA, err);
 }
References GE_NO_DATA.
TEST() [5/7]
TEST (ESP32CAM_GRP , release_OK)
Definition at line 75 of file esp32Cam_test.cpp.
 {
     auto err = m_cam.releasePicture();
     CHECK_EQUAL(GE_NO_DATA, err);
     for(size_t i = 0; i < 10; i++)
     {
         auto err = m_cam.takePicture();
         CHECK_EQUAL(GE_OK, err);
         err = m_cam.releasePicture();
         CHECK_EQUAL(GE_OK, err);
     }
 }
References GE_NO_DATA, and GE_OK.
TEST() [6/7]
TEST (ESP32CAM_GRP , singleton_initx2_fail)
Definition at line 41 of file esp32Cam_test.cpp.
 {
     esp32Cam& m_cam1 = esp32Cam::Instance();
     esp32Cam& m_cam2 = esp32Cam::Instance();
     auto err = m_cam1.takePicture();
     CHECK_EQUAL(GE_OK, err);
     err = m_cam2.takePicture();
     CHECK_EQUAL(GE_NOT_READY, err);
 }
References GE_NOT_READY, GE_OK, esp32Cam::Instance(), and esp32Cam::takePicture().
TEST() [7/7]
TEST (ESP32CAM_GRP , singleton_initx2_release_OK)
Definition at line 52 of file esp32Cam_test.cpp.
 {
     esp32Cam& m_cam1 = esp32Cam::Instance();
     esp32Cam& m_cam2 = esp32Cam::Instance();
     esp32Cam& m_cam3 = esp32Cam::Instance();
     auto err = m_cam1.takePicture();
     CHECK_EQUAL(GE_OK, err);
     err = m_cam2.takePicture();
     CHECK_EQUAL(GE_NOT_READY, err);
     err = m_cam3.releasePicture();
     CHECK_EQUAL(GE_OK, err);
     err = m_cam2.takePicture();
     CHECK_EQUAL(GE_OK, err);
 }
References GE_NOT_READY, GE_OK, esp32Cam::Instance(), esp32Cam::releasePicture(), and esp32Cam::takePicture().
TEST_GROUP()
TEST_GROUP (ESP32CAM_GRP)
Definition at line 13 of file esp32Cam_test.cpp.
{
     //esp32Cam m_cam;
     esp32Cam& m_cam = esp32Cam::Instance();
     void setup(){
     }
     void teardown(){
     // Uninit stuff
     m_cam.releasePicture();
     }
 };
References esp32Cam::Instance(), and esp32Cam::releasePicture().