Embedded Library: PWM_API_ESP32 Class Reference
PWM_API_ESP32 Class Reference final
#include <PWM_API_ESP32.hpp>
Public Member Functions
PWM_API_ESP32 (const HAL_ESP32::config &conf, const std::string &name)
following RAII @instantiation we activate and start PWM
~PWM_API_ESP32 ()
general_err_t setDutyCycle (const float &duty)
set the duty cycle of the pwm
general_err_t setFrequency (const uint32_t &frequency)
set the frequency of the pwm
Public Member Functions inherited from PWMBase< HAL_ESP32::config, HAL_ESP32 >
PWMBase (const HAL_ESP32::config &config, const std::string &name)
following RAII @instantiation we activate and start PWM
virtual ~PWMBase ()
Private Member Functions
general_err_t stop (void)
stop the pwm
Additional Inherited Members
Protected Attributes inherited from PWMBase< HAL_ESP32::config, HAL_ESP32 >
HAL_ESP32 m_hal
internal HAL object
Fault_Handler m_faulthanlder
internal faulthandler
Detailed Description
Definition at line 76 of file PWM_API_ESP32.hpp.
Constructor & Destructor Documentation
PWM_API_ESP32()
PWM_API_ESP32::PWM_API_ESP32 (const HAL_ESP32::config & conf, const std::string & name)
following RAII @instantiation we activate and start PWM
Definition at line 35 of file PWM_API_ESP32.cpp.
     : PWMBase(conf, name)
 {
 }
~PWM_API_ESP32()
PWM_API_ESP32::~PWM_API_ESP32 ()
Definition at line 40 of file PWM_API_ESP32.cpp.
 {
     m_hal.stop();
 }
References PWMBase< HAL_ESP32::config, HAL_ESP32 >::m_hal, and HAL_ESP32::stop().
Member Function Documentation
setDutyCycle()
general_err_t PWM_API_ESP32::setDutyCycle (const float & duty) virtual
set the duty cycle of the pwm
See also
PWMBase::setDutyCycle(const float& duty)
Attention
the function will call update() and automatically handle start/stop conditions for the pulse width modulation
Parameters
[in] const uint32_t &frequency
Returns
GE_OK
GE_OUT_OF_RANGE
Implements PWMBase< HAL_ESP32::config, HAL_ESP32 >.
Definition at line 60 of file PWM_API_ESP32.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> PWM_API::setDutyCycle >> ");
 #endif
     // Executable code:
     if(duty > 100.0)
     {
         m_faulthanlder.handleFault({FaultHandler_n::severity::low,
                                     "PWM_API_ESP32::setDutyCycle(const float &duty)",
                                     " duty cycle above 100 value is : " + std::to_string(duty)});
         return GE_OUT_OF_RANGE;
     }
     if(duty < 0.0)
     {
         m_faulthanlder.handleFault({FaultHandler_n::severity::low,
                                     "PWM_API_ESP32::setDutyCycle(const float &duty)",
                                     " duty cycle below 0 value is : " + std::to_string(duty)});
         return GE_OUT_OF_RANGE;
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< PWM_API::setDutyCycle << ");
 #endif
     return m_hal.setDutyCycle(duty);
 }
References GE_OUT_OF_RANGE, Fault_Handler::handleFault(), LOG_PRINT_INFO, LOG_TAG, FaultHandler_n::low, PWMBase< HAL_ESP32::config, HAL_ESP32 >::m_faulthanlder, PWMBase< HAL_ESP32::config, HAL_ESP32 >::m_hal, and HAL_ESP32::setDutyCycle().
Referenced by MG996R::actuate().
setFrequency()
general_err_t PWM_API_ESP32::setFrequency (const uint32_t & frequency) virtual
set the frequency of the pwm
See also
PWMBase::setFrequency(const uint32_t& frequency)
Attention
the function will call update() and automatically handle start/stop conditions for the pulse width modulation
Parameters
[in] const uint32_t &frequency
Returns
GE_OK
Implements PWMBase< HAL_ESP32::config, HAL_ESP32 >.
Definition at line 103 of file PWM_API_ESP32.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> PWM_API::setFrequency >> ");
 #endif
     // Executable code:
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< PWM_API::setFrequency << ");
 #endif
     return m_hal.setFrequency(frequency);
 }
References LOG_PRINT_INFO, LOG_TAG, PWMBase< HAL_ESP32::config, HAL_ESP32 >::m_hal, and HAL_ESP32::setFrequency().
stop()
general_err_t PWM_API_ESP32::stop (void) private virtual
stop the pwm
Attention
this is a private function
Returns
GE_OK
Implements PWMBase< HAL_ESP32::config, HAL_ESP32 >.
Definition at line 128 of file PWM_API_ESP32.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> PWM_API::stop >> ");
 #endif
     // Executable code:
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< PWM_API::stop << ");
 #endif
     return m_hal.stop();
 }
References LOG_PRINT_INFO, LOG_TAG, PWMBase< HAL_ESP32::config, HAL_ESP32 >::m_hal, and HAL_ESP32::stop().
The documentation for this class was generated from the following files:
Components/Objects/PWM/include/PWM_API_ESP32.hpp
Components/Objects/PWM/src/PWM_API_ESP32.cpp