Embedded Library: Utility_Image Class Reference
Utility_Image Class Reference
#include <Utility_Image.hpp>
Public Types
enum loader_conf { loader_conf::color, loader_conf::gray }
enum object_color { object_color::GREEN, object_color::RED, object_color::BLUE }
Static Public Member Functions
static cv::Mat load_image (const std::string &path, const loader_conf &conf=loader_conf::color)
static void view_image (const cv::Mat &m, const std::string &name="Viewer")
static cv::Mat zoom (const cv::Mat &img, double scale=5)
static cv::Mat draw_ellipse (const cv::Mat &img, const std::vector< cv::RotatedRect > &vec)
static void wait (uint16_t time_ms=0)
static void saveImage (const timeval &time, const cv::Mat &m, const std::string &name, const std::string &path)
static general_err_t getROI (const cv::Mat &src, const cv::Rect ROI, cv::Mat &dist)
get a Region of interest of the image
static general_err_t putDate (cv::Mat &img)
simple function to place a date at the top left corner of the image
static general_err_t putFPS (cv::Mat &img, const uint16_t fps)
simple function to put measured fps at the top right corner of an image
static general_err_t putMask (const cv::Mat &src, cv::Mat &dist, const cv::Point &start, const cv::Point &end)
PutMask Place a rectangle mask over an image defined by the rect.
static general_err_t rotateImage (cv::Mat &src, const double newAngle)
static general_err_t equalizeIllumination (const cv::Mat &src, cv::Mat &dist)
Normalize/equalize the brighness in the image to reduce impact of Illumination noises.
Detailed Description
Definition at line 76 of file Utility_Image.hpp.
Member Enumeration Documentation
loader_conf
enum Utility_Image::loader_conf strong
Enumerator
color
gray
Definition at line 82 of file Utility_Image.hpp.
     {
         color,
         gray
     };
object_color
enum Utility_Image::object_color strong
Enumerator
GREEN
RED
BLUE
Definition at line 87 of file Utility_Image.hpp.
     {
         GREEN,
         RED,
         BLUE
     };
Member Function Documentation
draw_ellipse()
cv::Mat Utility_Image::draw_ellipse (const cv::Mat & img, const std::vector< cv::RotatedRect > & vec) static
Definition at line 60 of file Utility_Image.cpp.
 {
     auto m = img.clone();
     cv::Scalar color = cv::Scalar(0, 255, 0);
     for(auto ele : vec)
     {
         cv::ellipse(m, ele, color);
     }
     return m;
 }
References vec.
equalizeIllumination()
general_err_t Utility_Image::equalizeIllumination (const cv::Mat & src, cv::Mat & dist) static
Normalize/equalize the brighness in the image to reduce impact of Illumination noises.
Attention
Parameters
[in] const cv::Mat &src
[in]
Definition at line 256 of file Utility_Image.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Utility_Image::equalizeIllumination >> ");
 #endif
     // Executable code:
     // we are not going to redeclare this vector on every single image
     static std::vector<cv::Mat> equalizer_subset{3};
     cv::cvtColor(src, dist, cv::COLOR_RGB2Lab);
     cv::split(dist, equalizer_subset);
     cv::equalizeHist(equalizer_subset.at(0), equalizer_subset.at(0));
     cv::merge(equalizer_subset, dist);
     cv::cvtColor(dist, dist, cv::COLOR_Lab2RGB);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Utility_Image::equalizeIllumination << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, LOG_TAG, and basic_utils::split().
getROI()
general_err_t Utility_Image::getROI (const cv::Mat & src, const cv::Rect ROI, cv::Mat & dist) static
get a Region of interest of the image
Attention
Parameters
[in] const cv::Mat &src
[in] const cv::Rect ROI
[out] cv::Mat &dist
[out]
Definition at line 190 of file Utility_Image.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> enclosing_method >> ");
 #endif
     // Executable code:
     dist = cv::Mat(src, ROI);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< enclosing_method << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
load_image()
cv::Mat Utility_Image::load_image (const std::string & path, const loader_conf & conf = loader_conf::color) static
Definition at line 31 of file Utility_Image.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Load_Image::load_image >> ");
 #endif
     // Executable code:
     if(conf == loader_conf::gray)
         return cv::imread(path, cv::IMREAD_GRAYSCALE);
     // return color img
     return cv::imread(path);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Load_Image::load_image << ");
 #endif
 }
References conf, gray, LOG_PRINT_INFO, and LOG_TAG.
putDate()
general_err_t Utility_Image::putDate (cv::Mat & img) static
simple function to place a date at the top left corner of the image
Attention
Parameters
[in] cv::Mat &img
[out] cv::Mat &img
Returns
GE_OK
Definition at line 101 of file Utility_Image.cpp.
 {
     cv::putText(img, Timeservice::getCurrentDate(), {30, 30}, 1, 2, {255, 255, 0}, 3);
     return GE_OK;
 }
References GE_OK, and Timeservice::getCurrentDate().
putFPS()
general_err_t Utility_Image::putFPS (cv::Mat & img, const uint16_t fps) static
simple function to put measured fps at the top right corner of an image
Attention
Parameters
[in] cv::Mat &img
[in] const uint16_t fps
[out] cv::Mat &img
Returns
GE_OK
Definition at line 123 of file Utility_Image.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Utility_Image::putFPS >> ");
 #endif
     // Executable code:
     cv::putText(img, std::to_string(fps), {img.cols - 100, 30}, 1, 2, {255, 255, 0}, 3);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Utility_Image::putFPS << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
putMask()
general_err_t Utility_Image::putMask (const cv::Mat & src, cv::Mat & dist, const cv::Point & start, const cv::Point & end) static
PutMask Place a rectangle mask over an image defined by the rect.
Attention
Parameters
[in] const Image &src
[in]
Definition at line 156 of file Utility_Image.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> putMask >> ");
 #endif
     // Executable code:
     src.copyTo(dist);
     cv::rectangle(dist, start, end, cv::Scalar(0, 255, 0), -1, cv::LINE_8);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< putMask << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
rotateImage()
general_err_t Utility_Image::rotateImage (cv::Mat & src, const double newAngle) static
Attention
Parameters
[in] int newAngle
[in / out] cv::Mat &src
Returns
GE_OK
applie an affine transforation to image.
Definition at line 220 of file Utility_Image.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Utility_Image::rotateImage >> ");
 #endif
     // Executable code:
     cv::Point2f pt(src.cols / 2., src.rows / 2.); // point from where to rotate
     cv::Mat r = cv::getRotationMatrix2D(pt, newAngle, 1.0); // Mat object for storing after rotation
     cv::warpAffine(src, src, r,
                    cv::Size(src.cols, src.rows));
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Utility_Image::rotateImage << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, and LOG_TAG.
saveImage()
void Utility_Image::saveImage (const timeval & time, const cv::Mat & m, const std::string & name, const std::string & path) static
Definition at line 76 of file Utility_Image.cpp.
 {
     std::string full_path;
     full_path =
         path + std::to_string(time.tv_sec) + "_" + std::to_string(time.tv_usec) + name + ".png";
     std::cout << "writing to path : " << full_path << "\n";
     imwrite(full_path.c_str(), m);
 }
view_image()
void Utility_Image::view_image (const cv::Mat & m, const std::string & name = "Viewer") static
Definition at line 47 of file Utility_Image.cpp.
 {
     namedWindow(name, cv::WINDOW_NORMAL);
     cv::imshow(name, m);
 }
Referenced by Background_Extractor::view().
wait()
void Utility_Image::wait (uint16_t time_ms = 0) static
Definition at line 71 of file Utility_Image.cpp.
 {
     cv::waitKey(time_ms);
 }
zoom()
cv::Mat Utility_Image::zoom (const cv::Mat & img, double scale = 5) static
Definition at line 53 of file Utility_Image.cpp.
 {
     cv::Mat m;
     cv::resize(img, m, cv::Size(), scale, scale, cv::INTER_NEAREST);
     return m;
 }
Referenced by Background_Extractor::view().
The documentation for this class was generated from the following files:
Components/AnalysisTools/ImageAnalysis_OpenCV/include/Utility_Image.hpp
Components/AnalysisTools/ImageAnalysis_OpenCV/src/Utility_Image.cpp