Embedded Library: Components/AnalysisTools/ImageAnalysis_OpenCV/test/test/cc_test.cpp File Reference
cc_test.cpp File Reference
#include "../../include/ConnectedComponents.hpp"
#include <iostream>
#include "CppUTest/TestHarness.h"
Functions
TEST_GROUP (CC_GRP)
TEST (CC_GRP, draw_empty1)
TEST (CC_GRP, count_connected_components_empty1)
TEST (CC_GRP, count_connected_components_empty2)
Function Documentation
TEST() [1/3]
TEST (CC_GRP , count_connected_components_empty1)
Definition at line 28 of file cc_test.cpp.
 {
     cv::Mat m1, m2;
     auto count = ConnectedComponents::maxConnectedComponents(m1);
     CHECK_EQUAL(0, count);
 }
References ConnectedComponents::maxConnectedComponents().
TEST() [2/3]
TEST (CC_GRP , count_connected_components_empty2)
Definition at line 35 of file cc_test.cpp.
 {
     cv::Mat m1, m2;
     auto container = ConnectedComponents::statsConnectedComponents(m1);
     CHECK_EQUAL(0, container.amount_of_connections);
     CHECK_EQUAL(0, container.maxConnected);
 }
References ConnectedComponents::statsConnectedComponents().
TEST() [3/3]
TEST (CC_GRP , draw_empty1)
Definition at line 21 of file cc_test.cpp.
 {
     cv::Mat m1, m2;
     auto err = ConnectedComponents::drawConnectedComponents(m1, m2);
     CHECK_EQUAL(GE_EMPTY, err);
 }
References ConnectedComponents::drawConnectedComponents(), and GE_EMPTY.
TEST_GROUP()
TEST_GROUP (CC_GRP)
Definition at line 13 of file cc_test.cpp.
                   {void setup(){
 } void teardown(){
     // Uninit stuff
 }};