Embedded Library: OnlineDetector_service Class Reference
OnlineDetector_service Class Reference final
#include <OnlineDetector_service.hpp>
Public Member Functions
OnlineDetector_service (size_t queue_size, size_t size_of_item, const db_id error_id)
virtual ~OnlineDetector_service (void)
Public Member Functions inherited from ServiceBase< MQTT_Message >
ServiceBase (size_t queue_size, size_t size_of_item, const MQTT_Message &buffer, const db_id error_id)
Construct a new Service Base object.
virtual ~ServiceBase ()
const auto & isActive () const
auto & getQueue ()
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Private Member Functions
general_err_t mainFunction () override
Main function for the derived class to work in It is expected that the function is a single-run function And that it should not be blocking.
Private Attributes
MQTT_Message msg_sucess
MQTT_Message msg_fail
Additional Inherited Members
Protected Member Functions inherited from ServiceBase< MQTT_Message >
virtual void setIsActive (bool isActive)
Set the Is Active object.
general_err_t postData (const MQTT_Message &message, const std::string &topic="mqtt/burst_msg")
Function to post data to database.
void run (void *data) override
loop for the service We are waiting "forever" on a queue recieve When we recieve something we will call the mainFunction() Which should be a single-end run for the derived class if any error happends it will be reported online.
Protected Attributes inherited from ServiceBase< MQTT_Message >
FreeRTOS::Queue m_queue
GPIO_API m_test_pin
const MQTT_Message & m_buffer
Detailed Description
Definition at line 51 of file OnlineDetector_service.hpp.
Constructor & Destructor Documentation
OnlineDetector_service()
OnlineDetector_service::OnlineDetector_service (size_t queue_size, size_t size_of_item, const db_id error_id) inline
Definition at line 57 of file OnlineDetector_service.hpp.
         : ServiceBase(queue_size, size_of_item, MQTT_Message{{db_id::CCTV01_DEBUG4, 1}}, error_id),
           msg_sucess{{db_id::ONLINEDETECTOR_ERROR_CODE, 1}}, msg_fail{
                                                                  {db_id::ONLINEDETECTOR_REACH_TIME,
                                                                   1}}
     {
     }
References CCTV01_DEBUG4.
~OnlineDetector_service()
virtual OnlineDetector_service::~OnlineDetector_service (void) inline virtual
Definition at line 64 of file OnlineDetector_service.hpp.
 {};
Member Function Documentation
mainFunction()
general_err_t OnlineDetector_service::mainFunction () override private virtual
Main function for the derived class to work in It is expected that the function is a single-run function And that it should not be blocking.
Returns
general_err_t
Implements ServiceBase< MQTT_Message >.
Definition at line 29 of file OnlineDetector_service.cpp.
 {
 #ifdef DEBUG
     std::cout << " >> OnlineDetector_service::main_function >> \n";
 #endif
 // do magic
 #ifdef __ESP32__
     bool res = Ping_API::isReachable<Ping_SAL_esp32>("www.google.dk");
 #else
     bool res = true;
 #endif
     if(!res)
     {
         std::cout << " not able to reach server ... \n";
         //  msg_fail.addData(10);
         // postData(msg_fail);
         //  msg_fail.clear();
     }
     else
     {
         std::cout << " able to reach server ... \n";
         msg_sucess.addData(20);
         postData(msg_sucess);
         msg_sucess.clear();
     }
 #ifdef DEBUG
     std::cout << " << OnlineDetector_service::main_function << \n";
 #endif
     return GE_OK;
 }
References MQTT_Message::addData(), MQTT_Message::clear(), GE_OK, msg_sucess, and ServiceBase< MQTT_Message >::postData().
Member Data Documentation
msg_fail
MQTT_Message OnlineDetector_service::msg_fail private
Definition at line 70 of file OnlineDetector_service.hpp.
msg_sucess
MQTT_Message OnlineDetector_service::msg_sucess private
Definition at line 69 of file OnlineDetector_service.hpp.
Referenced by mainFunction().
The documentation for this class was generated from the following files:
Components/Service/OnlineDetector/include/OnlineDetector_service.hpp
Components/Service/OnlineDetector/src/OnlineDetector_service.cpp