Embedded Library: DistanceSensorController_HW_TEST Class Reference
DistanceSensorController_HW_TEST Class Reference
#include <DistanceSensorController.hpp>
Public Member Functions
DistanceSensorController_HW_TEST (const DistanceSensorController::config &conf, const GPIO_HAL::pin test_pin)
~DistanceSensorController_HW_TEST ()
Public Member Functions inherited from DistanceSensorController
DistanceSensorController (const DistanceSensorController::config &conf)
~DistanceSensorController ()
Public Member Functions inherited from SensorControllerBase
SensorControllerBase (const init_conf &conf)
virtual ~SensorControllerBase ()
void setWantDataTrue ()
const auto & getSafeBuffer ()
const bool isDataReady ()
void setDataReady (bool flag)
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Private Member Functions
virtual general_err_t main_function () override
Private Attributes
GPIO_API m_test_pin
Additional Inherited Members
Protected Member Functions inherited from SensorControllerBase
void setDataReadyTrue ()
general_err_t postData (const MQTT_Message &message, const std::string &topic="mqtt/burst_msg")
void postError (const general_err_t &err, const std::string &error_message)
Protected Attributes inherited from SensorControllerBase
MQTT_Message m_buffer_raw
MQTT_Message m_buffer_external
std::atomic< bool > m_want_data_flag
std::atomic< bool > m_data_ready_flag
const uint64_t m_delay
const db_id m_error_id
Detailed Description
Definition at line 80 of file DistanceSensorController.hpp.
Constructor & Destructor Documentation
DistanceSensorController_HW_TEST()
DistanceSensorController_HW_TEST::DistanceSensorController_HW_TEST (const DistanceSensorController::config & conf, const GPIO_HAL::pin test_pin) inline
Definition at line 83 of file DistanceSensorController.hpp.
         : DistanceSensorController(conf), m_test_pin{test_pin}
     {
         m_test_pin.setToOutput();
     }
~DistanceSensorController_HW_TEST()
DistanceSensorController_HW_TEST::~DistanceSensorController_HW_TEST () inline
Definition at line 89 of file DistanceSensorController.hpp.
 {};
Member Function Documentation
main_function()
virtual general_err_t DistanceSensorController_HW_TEST::main_function () inline override private virtual
Reimplemented from DistanceSensorController.
Definition at line 93 of file DistanceSensorController.hpp.
     {
         m_test_pin.setHigh();
         auto err = DistanceSensorController::main_function();
         m_test_pin.setLow();
         return err;
     }
References m_test_pin, DistanceSensorController::main_function(), GPIO_API::setHigh(), and GPIO_API::setLow().
Member Data Documentation
m_test_pin
GPIO_API DistanceSensorController_HW_TEST::m_test_pin private
Definition at line 89 of file DistanceSensorController.hpp.
Referenced by main_function().
The documentation for this class was generated from the following file:
Components/Controller/DistanceSensorController/include/DistanceSensorController.hpp