Embedded Library: WaterEstimator_Service Class Reference
WaterEstimator_Service Class Reference final
#include <WaterEstimator_Service.hpp>
Public Member Functions
WaterEstimator_Service (size_t queue_size, size_t size_of_item, const MQTT_Message &buffer, const db_id error_id)
~WaterEstimator_Service ()
Public Member Functions inherited from ServiceQueueBase< MQTT_Message >
ServiceQueueBase (size_t queue_size, size_t size_of_item, const MQTT_Message &buffer, const db_id error_id)
virtual ~ServiceQueueBase ()
auto & getQueue ()
Public Member Functions inherited from ServiceBase< MQTT_Message >
ServiceBase (const MQTT_Message &buffer, const db_id error_id)
Construct a new Service Base object.
virtual ~ServiceBase ()
const auto & isActive () const
Public Member Functions inherited from Task
Task (const std::string &taskName="Task", const uint16_t &stackSize=10000, const uint8_t &priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (const std::string &name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
void delay (int ms)
Suspend the task for the specified milliseconds.
Private Member Functions
general_err_t mainFunction ()
Main function for the derived class to work in It is expected that the function is a single-run function And that it should not be blocking.
Private Attributes
MQTT_Message msg_max
MQTT_Message msg_min
MQTT_Message msg_count
PeriodeEstimator< 1500, 1200, NVS_MOCK > m_estimator
Additional Inherited Members
Protected Member Functions inherited from ServiceQueueBase< MQTT_Message >
void run (void *data) override
loop for the service We are waiting "forever" on a queue recieve When we recieve something we will call the mainFunction() Which should be a single-end run for the derived class if any error happends it will be reported online.
Protected Member Functions inherited from ServiceBase< MQTT_Message >
virtual void setIsActive (bool isActive)
Set the Is Active object.
general_err_t postData (const MQTT_Message &message, const std::string &topic="mqtt/burst_msg")
Function to post data to database.
virtual general_err_t postError (const std::string &message, const general_err_t &err)
Method to post errors to the database.
Protected Attributes inherited from ServiceQueueBase< MQTT_Message >
FreeRTOS::Queue m_queue
Protected Attributes inherited from ServiceBase< MQTT_Message >
GPIO_API m_test_pin
const MQTT_Message & m_buffer
db_id m_error_id
Detailed Description
Definition at line 48 of file WaterEstimator_Service.hpp.
Constructor & Destructor Documentation
WaterEstimator_Service()
WaterEstimator_Service::WaterEstimator_Service (size_t queue_size, size_t size_of_item, const MQTT_Message & buffer, const db_id error_id) inline
Definition at line 54 of file WaterEstimator_Service.hpp.
         : ServiceQueueBase(queue_size, size_of_item, buffer, error_id),
           msg_max{{db_id::WATERSTATION_MAX_ADC_VAL, 1}},
           msg_min{{db_id::WATERSTATION_MIN_ADC_VAL, 1}}, msg_count{
                                                              {db_id::WATERSTATION_COUNTER, 100}} {};
References WATERSTATION_MAX_ADC_VAL.
~WaterEstimator_Service()
WaterEstimator_Service::~WaterEstimator_Service () inline
Definition at line 60 of file WaterEstimator_Service.hpp.
 {};
Member Function Documentation
mainFunction()
general_err_t WaterEstimator_Service::mainFunction () private virtual
Main function for the derived class to work in It is expected that the function is a single-run function And that it should not be blocking.
Returns
general_err_t
Implements ServiceQueueBase< MQTT_Message >.
Definition at line 29 of file WaterEstimator_Service.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> WaterEstimator_Service::mainFunction >> ");
 #endif
     // Executable code:
     uint64_t max_value = 0;
     uint64_t min_value = 50000;
     for(const auto& ele : m_buffer.getData())
     {
         if(ele.second > max_value)
         {
             max_value = ele.second;
         }
         if(ele.second < min_value)
         {
             min_value = ele.second;
         }
         auto err = m_estimator.addData(ele);
         if(err == GE_OK)
         {
             msg_count.addData(m_estimator.getPeriodCounter());
         }
     }
     msg_max.addData(max_value);
     msg_min.addData(min_value);
     // postData(msg_max);
     // postData(msg_min);
     postData(msg_count);
     msg_max.clear();
     msg_min.clear();
     msg_count.clear();
     std::cout << " max value is : " << (int)max_value << " min value is : " << (int)min_value
               << " count is : " << m_estimator.getPeriodCounter() << "\n";
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<<  WaterEstimator_Service::mainFunction << ");
 #endif
     return GE_OK;
 }
References PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::addData(), MQTT_Message::addData(), MQTT_Message::clear(), GE_OK, MQTT_Message::getData(), PeriodeEstimator< HIGH_THRESHOLD, LOW_THRESHOLD, NVS_TYPE >::getPeriodCounter(), LOG_PRINT_INFO, LOG_TAG, ServiceBase< MQTT_Message >::m_buffer, m_estimator, msg_count, msg_max, msg_min, and ServiceBase< MQTT_Message >::postData().
Member Data Documentation
m_estimator
PeriodeEstimator<1500, 1200, NVS_MOCK> WaterEstimator_Service::m_estimator private
Definition at line 70 of file WaterEstimator_Service.hpp.
Referenced by mainFunction().
msg_count
MQTT_Message WaterEstimator_Service::msg_count private
Definition at line 66 of file WaterEstimator_Service.hpp.
Referenced by mainFunction().
msg_max
MQTT_Message WaterEstimator_Service::msg_max private
Definition at line 64 of file WaterEstimator_Service.hpp.
Referenced by mainFunction().
msg_min
MQTT_Message WaterEstimator_Service::msg_min private
Definition at line 65 of file WaterEstimator_Service.hpp.
Referenced by mainFunction().
The documentation for this class was generated from the following files:
Components/Service/WaterEstimator/include/WaterEstimator_Service.hpp
Components/Service/WaterEstimator/src/WaterEstimator_Service.cpp