Embedded Library: Message_Protocol Class Reference
Message_Protocol Class Reference
#include <Message_Protocol.hpp>
Public Member Functions
Message_Protocol (const msg_control_t &cnt, const msg_data_t &data)
Message_Protocol ()
~Message_Protocol ()
general_err_t setControl (const msg_control_t &cnt)
set the control parameters
const msg_control_t & getControl (void) const
get the control parameter
general_err_t addData (const msg_data_t &data)
add data to the buffer
const std::vector< msg_data_t > & getBuffer (void) const
get the buffer
general_err_t clear (void)
clear the buffer and uninitialize the package
general_err_t toString (std::string *str) const
bool isValid (void) const
check if the protocol is valid
Static Public Member Functions
static size_t parameterCount (void)
static size_t controlParameterCount (void)
static size_t dataParameterCount (void)
Private Attributes
msg_control_t m_control
std::vector< msg_data_t > m_buffer
bool m_initialized = false
bool m_valid = false
Detailed Description
Definition at line 93 of file Message_Protocol.hpp.
Constructor & Destructor Documentation
Message_Protocol() [1/2]
Message_Protocol::Message_Protocol (const msg_control_t & cnt, const msg_data_t & data)
Definition at line 38 of file Message_Protocol.cpp.
     : m_control{cnt}, m_initialized{true}
 {
     m_buffer.push_back(data);
 }
Message_Protocol() [2/2]
Message_Protocol::Message_Protocol ()
Definition at line 36 of file Message_Protocol.cpp.
 {}
~Message_Protocol()
Message_Protocol::~Message_Protocol ()
Definition at line 44 of file Message_Protocol.cpp.
 {}
Member Function Documentation
addData()
general_err_t Message_Protocol::addData (const msg_data_t & data)
add data to the buffer
Parameters
[in] const msg_data_t<T>& data
Returns
GE_OK
Definition at line 85 of file Message_Protocol.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> enclosing_method >> ");
 #endif
     // Executable code:
     if(!m_initialized)
     {
         return GE_NOT_INITIALIZED;
     }
     m_buffer.push_back(data);
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< enclosing_method << ");
 #endif
     return GE_OK;
 }
References GE_NOT_INITIALIZED, GE_OK, LOG_PRINT_INFO, LOG_TAG, m_buffer, and m_initialized.
clear()
general_err_t Message_Protocol::clear (void)
clear the buffer and uninitialize the package
Returns
GE_OK
Definition at line 140 of file Message_Protocol.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Message_Protocol::clear >> ");
 #endif
     // Executable code:
     m_initialized = false;
     m_control = {0, 0};
     m_buffer.clear();
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Message_Protocol::clear << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, LOG_TAG, m_buffer, m_control, and m_initialized.
controlParameterCount()
static size_t Message_Protocol::controlParameterCount (void) inline static
Definition at line 110 of file Message_Protocol.hpp.
     {
         return 2;
     }; // id + flag  = 2
dataParameterCount()
static size_t Message_Protocol::dataParameterCount (void) inline static
Definition at line 114 of file Message_Protocol.hpp.
     {
         return 3;
     }; // 2xtime + data = 3
getBuffer()
const std::vector< msg_data_t > & Message_Protocol::getBuffer (void) const
get the buffer
Returns
GE_OK
Definition at line 112 of file Message_Protocol.cpp.
 {
     return m_buffer;
 }
References m_buffer.
Referenced by Message_Handler::to_Postgres_Form(), Message_Handler::to_Postgres_Format(), and Message_Handler::to_Postgres_Subject().
getControl()
const msg_control_t & Message_Protocol::getControl (void) const
get the control parameter
Returns
N/A
Definition at line 126 of file Message_Protocol.cpp.
 {
     return m_control;
 }
References m_control.
Referenced by Message_Handler::to_Postgres_Form(), Message_Handler::to_Postgres_Format(), and Message_Handler::to_Postgres_Subject().
isValid()
bool Message_Protocol::isValid (void) const
check if the protocol is valid
Returns
N/A
Definition at line 211 of file Message_Protocol.cpp.
 {
     return ((m_buffer.size() == 0) or !m_initialized) ? false : true;
 }
References m_buffer, and m_initialized.
Referenced by Message_Handler::to_Postgres_Form(), Message_Handler::to_Postgres_Format(), and Message_Handler::to_Postgres_Subject().
parameterCount()
static size_t Message_Protocol::parameterCount (void) inline static
Definition at line 106 of file Message_Protocol.hpp.
     {
         return 5;
     }; // id + flag + 2xtime + data = 5
setControl()
general_err_t Message_Protocol::setControl (const msg_control_t & cnt)
set the control parameters
Parameters
[in] const msg_control_t& cnt
Returns
GE_OK
Definition at line 57 of file Message_Protocol.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> enclosing_method >> ");
 #endif
     // Executable code:
     m_control = cnt;
     // we are now initialized
     m_initialized = true;
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< enclosing_method << ");
 #endif
     return GE_OK;
 }
References GE_OK, LOG_PRINT_INFO, LOG_TAG, m_control, and m_initialized.
toString()
general_err_t Message_Protocol::toString (std::string * str) const
Attention
[CONTROL PARAMS] [ BUFFER ....] -----------------------------------------------------—.... | | | | | | | | ID | Flag | SEC | USEC | DATA | SEC | | | | | | | | ------------------------------------------------------—.....
Parameters
[out] std::string* str
Returns
GE_OK
Definition at line 174 of file Message_Protocol.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> Message_Protocol::toString >> ");
 #endif
     // clear the input parameter
     str->clear();
     // Executable code:
     str->append(std::to_string(m_control.id));
     str->append(",");
     str->append(std::to_string(m_control.flag));
     for(auto const& ele : m_buffer)
     {
         str->append(",");
         str->append(std::to_string(ele.time_stamp.tv_sec));
         str->append(",");
         str->append(std::to_string(ele.time_stamp.tv_usec));
         str->append(",");
         str->append(std::to_string(ele.data));
     }
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< Message_Protocol::toString << ");
 #endif
     return GE_OK;
 }
References msg_control_t::flag, GE_OK, msg_control_t::id, LOG_PRINT_INFO, LOG_TAG, m_buffer, and m_control.
Member Data Documentation
m_buffer
std::vector<msg_data_t> Message_Protocol::m_buffer private
Definition at line 120 of file Message_Protocol.hpp.
Referenced by addData(), clear(), getBuffer(), isValid(), and toString().
m_control
msg_control_t Message_Protocol::m_control private
Definition at line 117 of file Message_Protocol.hpp.
Referenced by clear(), getControl(), setControl(), and toString().
m_initialized
bool Message_Protocol::m_initialized = false private
Definition at line 121 of file Message_Protocol.hpp.
Referenced by addData(), clear(), isValid(), and setControl().
m_valid
bool Message_Protocol::m_valid = false private
Definition at line 122 of file Message_Protocol.hpp.
The documentation for this class was generated from the following files:
Components/Objects/Message/include/Message_Protocol.hpp
Components/Objects/Message/src/Message_Protocol.cpp