Embedded Library: jpge::jpeg_encoder Class Reference
jpge::jpeg_encoder Class Reference
#include <jpge.h>
Public Member Functions
jpeg_encoder ()
~jpeg_encoder ()
bool init (output_stream *pStream, int width, int height, int src_channels, const params &comp_params=params())
bool process_scanline (const void *pScanline)
void deinit ()
Private Types
enum { JPGE_OUT_BUF_SIZE = 512 }
typedef int32 sample_array_t
Private Member Functions
jpeg_encoder (const jpeg_encoder &)
jpeg_encoder & operator= (const jpeg_encoder &)
bool jpg_open (int p_x_res, int p_y_res, int src_channels)
void flush_output_buffer ()
void put_bits (uint bits, uint len)
void emit_byte (uint8 i)
void emit_word (uint i)
void emit_marker (int marker)
void emit_jfif_app0 ()
void emit_dqt ()
void emit_sof ()
void emit_dht (uint8 *bits, uint8 *val, int index, bool ac_flag)
void emit_dhts ()
void emit_sos ()
void compute_quant_table (int32 *dst, const int16 *src)
void load_quantized_coefficients (int component_num)
void load_block_8_8_grey (int x)
void load_block_8_8 (int x, int y, int c)
void load_block_16_8 (int x, int c)
void load_block_16_8_8 (int x, int c)
void code_coefficients_pass_two (int component_num)
void code_block (int component_num)
void process_mcu_row ()
bool process_end_of_image ()
void load_mcu (const void *src)
void clear ()
void init ()
Private Attributes
output_stream * m_pStream
params m_params
uint8 m_num_components
uint8 m_comp_h_samp [3]
uint8 m_comp_v_samp [3]
int m_image_x
int m_image_y
int m_image_bpp
int m_image_bpl
int m_image_x_mcu
int m_image_y_mcu
int m_image_bpl_xlt
int m_image_bpl_mcu
int m_mcus_per_row
int m_mcu_x
int m_mcu_y
uint8 * m_mcu_lines [16]
uint8 m_mcu_y_ofs
sample_array_t m_sample_array [64]
int16 m_coefficient_array [64]
int m_last_dc_val [3]
uint8 m_out_buf [JPGE_OUT_BUF_SIZE]
uint8 * m_pOut_buf
uint m_out_buf_left
uint32 m_bit_buffer
uint m_bits_in
uint8 m_pass_num
bool m_all_stream_writes_succeeded
Detailed Description
Definition at line 68 of file jpge.h.
Member Typedef Documentation
sample_array_t
typedef int32 jpge::jpeg_encoder::sample_array_t private
Definition at line 96 of file jpge.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
JPGE_OUT_BUF_SIZE
Definition at line 97 of file jpge.h.
     {
         JPGE_OUT_BUF_SIZE = 512
     };
Constructor & Destructor Documentation
jpeg_encoder() [1/2]
jpge::jpeg_encoder::jpeg_encoder ()
Definition at line 877 of file jpge.cpp.
 {
     clear();
 }
References clear().
~jpeg_encoder()
jpge::jpeg_encoder::~jpeg_encoder ()
Definition at line 882 of file jpge.cpp.
 {
     deinit();
 }
References deinit().
jpeg_encoder() [2/2]
jpge::jpeg_encoder::jpeg_encoder (const jpeg_encoder &) private
Member Function Documentation
clear()
void jpge::jpeg_encoder::clear () private
Definition at line 870 of file jpge.cpp.
 {
     m_mcu_lines[0] = NULL;
     m_pass_num = 0;
     m_all_stream_writes_succeeded = true;
 }
References m_all_stream_writes_succeeded, m_mcu_lines, and m_pass_num.
Referenced by deinit(), and jpeg_encoder().
code_block()
void jpge::jpeg_encoder::code_block (int component_num) private
Definition at line 610 of file jpge.cpp.
 {
     DCT2D(m_sample_array);
     load_quantized_coefficients(component_num);
     code_coefficients_pass_two(component_num);
 }
References code_coefficients_pass_two(), jpge::DCT2D(), load_quantized_coefficients(), and m_sample_array.
Referenced by process_mcu_row().
code_coefficients_pass_two()
void jpge::jpeg_encoder::code_coefficients_pass_two (int component_num) private
Definition at line 539 of file jpge.cpp.
 {
     int i, j, run_len, nbits, temp1, temp2;
     int16* pSrc = m_coefficient_array;
     uint* codes[2];
     uint8* code_sizes[2];
     if(component_num == 0)
     {
         codes[0] = m_huff_codes[0 + 0];
         codes[1] = m_huff_codes[2 + 0];
         code_sizes[0] = m_huff_code_sizes[0 + 0];
         code_sizes[1] = m_huff_code_sizes[2 + 0];
     }
     else
     {
         codes[0] = m_huff_codes[0 + 1];
         codes[1] = m_huff_codes[2 + 1];
         code_sizes[0] = m_huff_code_sizes[0 + 1];
         code_sizes[1] = m_huff_code_sizes[2 + 1];
     }
     temp1 = temp2 = pSrc[0] - m_last_dc_val[component_num];
     m_last_dc_val[component_num] = pSrc[0];
     if(temp1 < 0)
     {
         temp1 = -temp1;
         temp2--;
     }
     nbits = 0;
     while(temp1)
     {
         nbits++;
         temp1 >>= 1;
     }
     put_bits(codes[0][nbits], code_sizes[0][nbits]);
     if(nbits)
         put_bits(temp2 & ((1 << nbits) - 1), nbits);
     for(run_len = 0, i = 1; i < 64; i++)
     {
         if((temp1 = m_coefficient_array[i]) == 0)
             run_len++;
         else
         {
             while(run_len >= 16)
             {
                 put_bits(codes[1][0xF0], code_sizes[1][0xF0]);
                 run_len -= 16;
             }
             if((temp2 = temp1) < 0)
             {
                 temp1 = -temp1;
                 temp2--;
             }
             nbits = 1;
             while(temp1 >>= 1)
                 nbits++;
             j = (run_len << 4) + nbits;
             put_bits(codes[1][j], code_sizes[1][j]);
             put_bits(temp2 & ((1 << nbits) - 1), nbits);
             run_len = 0;
         }
     }
     if(run_len)
         put_bits(codes[1][0], code_sizes[1][0]);
 }
References m_coefficient_array, jpge::m_huff_code_sizes, jpge::m_huff_codes, m_last_dc_val, and put_bits().
Referenced by code_block().
compute_quant_table()
void jpge::jpeg_encoder::compute_quant_table (int32 * dst, const int16 * src) private
Definition at line 719 of file jpge.cpp.
 {
     int32 q;
     if(m_params.m_quality < 50)
         q = 5000 / m_params.m_quality;
     else
         q = 200 - m_params.m_quality * 2;
     for(int i = 0; i < 64; i++)
     {
         int32 j = *pSrc++;
         j = (j * q + 50L) / 100L;
         *pDst++ = JPGE_MIN(JPGE_MAX(j, 1), 255);
     }
 }
References JPGE_MAX, JPGE_MIN, m_params, and jpge::params::m_quality.
Referenced by jpg_open().
deinit()
void jpge::jpeg_encoder::deinit ()
Definition at line 900 of file jpge.cpp.
 {
     jpge_free(m_mcu_lines[0]);
     clear();
 }
References clear(), jpge::jpge_free(), and m_mcu_lines.
Referenced by init(), and ~jpeg_encoder().
emit_byte()
void jpge::jpeg_encoder::emit_byte (uint8 i) private
Definition at line 294 of file jpge.cpp.
 {
     *m_pOut_buf++ = i;
     if(--m_out_buf_left == 0)
     {
         flush_output_buffer();
     }
 }
References flush_output_buffer(), m_out_buf_left, and m_pOut_buf.
Referenced by emit_dht(), emit_dqt(), emit_jfif_app0(), emit_marker(), emit_sof(), emit_sos(), emit_word(), and put_bits().
emit_dht()
void jpge::jpeg_encoder::emit_dht (uint8 * bits, uint8 * val, int index, bool ac_flag) private
Definition at line 383 of file jpge.cpp.
 {
     emit_marker(M_DHT);
     int length = 0;
     for(int i = 1; i <= 16; i++)
         length += bits[i];
     emit_word(length + 2 + 1 + 16);
     emit_byte(static_cast<uint8>(index + (ac_flag << 4)));
     for(int i = 1; i <= 16; i++)
         emit_byte(bits[i]);
     for(int i = 0; i < length; i++)
         emit_byte(val[i]);
 }
References emit_byte(), emit_marker(), emit_word(), and jpge::M_DHT.
Referenced by emit_dhts().
emit_dhts()
void jpge::jpeg_encoder::emit_dhts () private
Definition at line 402 of file jpge.cpp.
 {
     emit_dht(m_huff_bits[0 + 0], m_huff_val[0 + 0], 0, false);
     emit_dht(m_huff_bits[2 + 0], m_huff_val[2 + 0], 0, true);
     if(m_num_components == 3)
     {
         emit_dht(m_huff_bits[0 + 1], m_huff_val[0 + 1], 1, false);
         emit_dht(m_huff_bits[2 + 1], m_huff_val[2 + 1], 1, true);
     }
 }
References emit_dht(), jpge::m_huff_bits, jpge::m_huff_val, and m_num_components.
Referenced by jpg_open().
emit_dqt()
void jpge::jpeg_encoder::emit_dqt () private
Definition at line 353 of file jpge.cpp.
 {
     for(int i = 0; i < ((m_num_components == 3) ? 2 : 1); i++)
     {
         emit_marker(M_DQT);
         emit_word(64 + 1 + 2);
         emit_byte(static_cast<uint8>(i));
         for(int j = 0; j < 64; j++)
             emit_byte(static_cast<uint8>(m_quantization_tables[i][j]));
     }
 }
References emit_byte(), emit_marker(), emit_word(), jpge::M_DQT, m_num_components, and jpge::m_quantization_tables.
Referenced by jpg_open().
emit_jfif_app0()
void jpge::jpeg_encoder::emit_jfif_app0 () private
Definition at line 334 of file jpge.cpp.
 {
     emit_marker(M_APP0);
     emit_word(2 + 4 + 1 + 2 + 1 + 2 + 2 + 1 + 1);
     emit_byte(0x4A);
     emit_byte(0x46);
     emit_byte(0x49);
     emit_byte(0x46); /* Identifier: ASCII "JFIF" */
     emit_byte(0);
     emit_byte(1); /* Major version */
     emit_byte(1); /* Minor version */
     emit_byte(0); /* Density unit */
     emit_word(1);
     emit_word(1);
     emit_byte(0); /* No thumbnail image */
     emit_byte(0);
 }
References emit_byte(), emit_marker(), emit_word(), and jpge::M_APP0.
Referenced by jpg_open().
emit_marker()
void jpge::jpeg_encoder::emit_marker (int marker) private
Definition at line 327 of file jpge.cpp.
 {
     emit_byte(uint8(0xFF));
     emit_byte(uint8(marker));
 }
References emit_byte().
Referenced by emit_dht(), emit_dqt(), emit_jfif_app0(), emit_sof(), emit_sos(), jpg_open(), and process_end_of_image().
emit_sof()
void jpge::jpeg_encoder::emit_sof () private
Definition at line 366 of file jpge.cpp.
 {
     emit_marker(M_SOF0); /* baseline */
     emit_word(3 * m_num_components + 2 + 5 + 1);
     emit_byte(8); /* precision */
     emit_word(m_image_y);
     emit_word(m_image_x);
     emit_byte(m_num_components);
     for(int i = 0; i < m_num_components; i++)
     {
         emit_byte(static_cast<uint8>(i + 1)); /* component ID     */
         emit_byte((m_comp_h_samp[i] << 4) + m_comp_v_samp[i]); /* h and v sampling */
         emit_byte(i > 0); /* quant. table num */
     }
 }
References emit_byte(), emit_marker(), emit_word(), m_comp_h_samp, m_comp_v_samp, m_image_x, m_image_y, m_num_components, and jpge::M_SOF0.
Referenced by jpg_open().
emit_sos()
void jpge::jpeg_encoder::emit_sos () private
Definition at line 414 of file jpge.cpp.
 {
     emit_marker(M_SOS);
     emit_word(2 * m_num_components + 2 + 1 + 3);
     emit_byte(m_num_components);
     for(int i = 0; i < m_num_components; i++)
     {
         emit_byte(static_cast<uint8>(i + 1));
         if(i == 0)
             emit_byte((0 << 4) + 0);
         else
             emit_byte((1 << 4) + 1);
     }
     emit_byte(0); /* spectral selection */
     emit_byte(63);
     emit_byte(0);
 }
References emit_byte(), emit_marker(), emit_word(), m_num_components, and jpge::M_SOS.
Referenced by jpg_open().
emit_word()
void jpge::jpeg_encoder::emit_word (uint i) private
Definition at line 320 of file jpge.cpp.
 {
     emit_byte(uint8(i >> 8));
     emit_byte(uint8(i & 0xFF));
 }
References emit_byte().
Referenced by emit_dht(), emit_dqt(), emit_jfif_app0(), emit_sof(), and emit_sos().
flush_output_buffer()
void jpge::jpeg_encoder::flush_output_buffer () private
Definition at line 282 of file jpge.cpp.
 {
     if(m_out_buf_left != JPGE_OUT_BUF_SIZE)
     {
         m_all_stream_writes_succeeded =
             m_all_stream_writes_succeeded &&
             m_pStream->put_buf(m_out_buf, JPGE_OUT_BUF_SIZE - m_out_buf_left);
     }
     m_pOut_buf = m_out_buf;
     m_out_buf_left = JPGE_OUT_BUF_SIZE;
 }
References JPGE_OUT_BUF_SIZE, m_all_stream_writes_succeeded, m_out_buf, m_out_buf_left, m_pOut_buf, m_pStream, and jpge::output_stream::put_buf().
Referenced by emit_byte(), and process_end_of_image().
init() [1/2]
void jpge::jpeg_encoder::init () private
init() [2/2]
bool jpge::jpeg_encoder::init (output_stream * pStream, int width, int height, int src_channels, const params & comp_params = params())
Definition at line 887 of file jpge.cpp.
 {
     deinit();
     if(((!pStream) || (width < 1) || (height < 1)) ||
        ((src_channels != 1) && (src_channels != 3) && (src_channels != 4)) ||
        (!comp_params.check()))
         return false;
     m_pStream = pStream;
     m_params = comp_params;
     return jpg_open(width, height, src_channels);
 }
References jpge::params::check(), deinit(), jpg_open(), m_params, and m_pStream.
jpg_open()
bool jpge::jpeg_encoder::jpg_open (int p_x_res, int p_y_res, int src_channels) private
Definition at line 735 of file jpge.cpp.
 {
     m_num_components = 3;
     switch(m_params.m_subsampling)
     {
         case Y_ONLY: {
             m_num_components = 1;
             m_comp_h_samp[0] = 1;
             m_comp_v_samp[0] = 1;
             m_mcu_x = 8;
             m_mcu_y = 8;
             break;
         }
         case H1V1: {
             m_comp_h_samp[0] = 1;
             m_comp_v_samp[0] = 1;
             m_comp_h_samp[1] = 1;
             m_comp_v_samp[1] = 1;
             m_comp_h_samp[2] = 1;
             m_comp_v_samp[2] = 1;
             m_mcu_x = 8;
             m_mcu_y = 8;
             break;
         }
         case H2V1: {
             m_comp_h_samp[0] = 2;
             m_comp_v_samp[0] = 1;
             m_comp_h_samp[1] = 1;
             m_comp_v_samp[1] = 1;
             m_comp_h_samp[2] = 1;
             m_comp_v_samp[2] = 1;
             m_mcu_x = 16;
             m_mcu_y = 8;
             break;
         }
         case H2V2: {
             m_comp_h_samp[0] = 2;
             m_comp_v_samp[0] = 2;
             m_comp_h_samp[1] = 1;
             m_comp_v_samp[1] = 1;
             m_comp_h_samp[2] = 1;
             m_comp_v_samp[2] = 1;
             m_mcu_x = 16;
             m_mcu_y = 16;
         }
     }
     m_image_x = p_x_res;
     m_image_y = p_y_res;
     m_image_bpp = src_channels;
     m_image_bpl = m_image_x * src_channels;
     m_image_x_mcu = (m_image_x + m_mcu_x - 1) & (~(m_mcu_x - 1));
     m_image_y_mcu = (m_image_y + m_mcu_y - 1) & (~(m_mcu_y - 1));
     m_image_bpl_xlt = m_image_x * m_num_components;
     m_image_bpl_mcu = m_image_x_mcu * m_num_components;
     m_mcus_per_row = m_image_x_mcu / m_mcu_x;
     if((m_mcu_lines[0] = static_cast<uint8*>(jpge_malloc(m_image_bpl_mcu * m_mcu_y))) == NULL)
     {
         return false;
     }
     for(int i = 1; i < m_mcu_y; i++)
         m_mcu_lines[i] = m_mcu_lines[i - 1] + m_image_bpl_mcu;
     if(m_last_quality != m_params.m_quality)
     {
         m_last_quality = m_params.m_quality;
         compute_quant_table(m_quantization_tables[0], s_std_lum_quant);
         compute_quant_table(m_quantization_tables[1], s_std_croma_quant);
     }
     if(!m_huff_initialized)
     {
         m_huff_initialized = true;
         memcpy(m_huff_bits[0 + 0], s_dc_lum_bits, 17);
         memcpy(m_huff_val[0 + 0], s_dc_lum_val, DC_LUM_CODES);
         memcpy(m_huff_bits[2 + 0], s_ac_lum_bits, 17);
         memcpy(m_huff_val[2 + 0], s_ac_lum_val, AC_LUM_CODES);
         memcpy(m_huff_bits[0 + 1], s_dc_chroma_bits, 17);
         memcpy(m_huff_val[0 + 1], s_dc_chroma_val, DC_CHROMA_CODES);
         memcpy(m_huff_bits[2 + 1], s_ac_chroma_bits, 17);
         memcpy(m_huff_val[2 + 1], s_ac_chroma_val, AC_CHROMA_CODES);
         compute_huffman_table(&m_huff_codes[0 + 0][0], &m_huff_code_sizes[0 + 0][0],
                               m_huff_bits[0 + 0], m_huff_val[0 + 0]);
         compute_huffman_table(&m_huff_codes[2 + 0][0], &m_huff_code_sizes[2 + 0][0],
                               m_huff_bits[2 + 0], m_huff_val[2 + 0]);
         compute_huffman_table(&m_huff_codes[0 + 1][0], &m_huff_code_sizes[0 + 1][0],
                               m_huff_bits[0 + 1], m_huff_val[0 + 1]);
         compute_huffman_table(&m_huff_codes[2 + 1][0], &m_huff_code_sizes[2 + 1][0],
                               m_huff_bits[2 + 1], m_huff_val[2 + 1]);
     }
     m_out_buf_left = JPGE_OUT_BUF_SIZE;
     m_pOut_buf = m_out_buf;
     m_bit_buffer = 0;
     m_bits_in = 0;
     m_mcu_y_ofs = 0;
     m_pass_num = 2;
     memset(m_last_dc_val, 0, 3 * sizeof(m_last_dc_val[0]));
     // Emit all markers at beginning of image file.
     emit_marker(M_SOI);
     emit_jfif_app0();
     emit_dqt();
     emit_sof();
     emit_dhts();
     emit_sos();
     return m_all_stream_writes_succeeded;
 }
References jpge::AC_CHROMA_CODES, jpge::AC_LUM_CODES, jpge::compute_huffman_table(), compute_quant_table(), jpge::DC_CHROMA_CODES, jpge::DC_LUM_CODES, emit_dhts(), emit_dqt(), emit_jfif_app0(), emit_marker(), emit_sof(), emit_sos(), jpge::H1V1, jpge::H2V1, jpge::H2V2, jpge::jpge_malloc(), JPGE_OUT_BUF_SIZE, m_all_stream_writes_succeeded, m_bit_buffer, m_bits_in, m_comp_h_samp, m_comp_v_samp, jpge::m_huff_bits, jpge::m_huff_code_sizes, jpge::m_huff_codes, jpge::m_huff_initialized, jpge::m_huff_val, m_image_bpl, m_image_bpl_mcu, m_image_bpl_xlt, m_image_bpp, m_image_x, m_image_x_mcu, m_image_y, m_image_y_mcu, m_last_dc_val, jpge::m_last_quality, m_mcu_lines, m_mcu_x, m_mcu_y, m_mcu_y_ofs, m_mcus_per_row, m_num_components, m_out_buf, m_out_buf_left, m_params, m_pass_num, m_pOut_buf, jpge::params::m_quality, jpge::m_quantization_tables, jpge::M_SOI, jpge::params::m_subsampling, jpge::s_ac_chroma_bits, jpge::s_ac_chroma_val, jpge::s_ac_lum_bits, jpge::s_ac_lum_val, jpge::s_dc_chroma_bits, jpge::s_dc_chroma_val, jpge::s_dc_lum_bits, jpge::s_dc_lum_val, jpge::s_std_croma_quant, jpge::s_std_lum_quant, and jpge::Y_ONLY.
Referenced by init().
load_block_16_8()
void jpge::jpeg_encoder::load_block_16_8 (int x, int c) private
Definition at line 471 of file jpge.cpp.
 {
     uint8 *pSrc1, *pSrc2;
     sample_array_t* pDst = m_sample_array;
     x = (x * (16 * 3)) + c;
     int a = 0, b = 2;
     for(int i = 0; i < 16; i += 2, pDst += 8)
     {
         pSrc1 = m_mcu_lines[i + 0] + x;
         pSrc2 = m_mcu_lines[i + 1] + x;
         pDst[0] = ((pSrc1[0 * 3] + pSrc1[1 * 3] + pSrc2[0 * 3] + pSrc2[1 * 3] + a) >> 2) - 128;
         pDst[1] = ((pSrc1[2 * 3] + pSrc1[3 * 3] + pSrc2[2 * 3] + pSrc2[3 * 3] + b) >> 2) - 128;
         pDst[2] = ((pSrc1[4 * 3] + pSrc1[5 * 3] + pSrc2[4 * 3] + pSrc2[5 * 3] + a) >> 2) - 128;
         pDst[3] = ((pSrc1[6 * 3] + pSrc1[7 * 3] + pSrc2[6 * 3] + pSrc2[7 * 3] + b) >> 2) - 128;
         pDst[4] = ((pSrc1[8 * 3] + pSrc1[9 * 3] + pSrc2[8 * 3] + pSrc2[9 * 3] + a) >> 2) - 128;
         pDst[5] = ((pSrc1[10 * 3] + pSrc1[11 * 3] + pSrc2[10 * 3] + pSrc2[11 * 3] + b) >> 2) - 128;
         pDst[6] = ((pSrc1[12 * 3] + pSrc1[13 * 3] + pSrc2[12 * 3] + pSrc2[13 * 3] + a) >> 2) - 128;
         pDst[7] = ((pSrc1[14 * 3] + pSrc1[15 * 3] + pSrc2[14 * 3] + pSrc2[15 * 3] + b) >> 2) - 128;
         int temp = a;
         a = b;
         b = temp;
     }
 }
References m_mcu_lines, and m_sample_array.
Referenced by process_mcu_row().
load_block_16_8_8()
void jpge::jpeg_encoder::load_block_16_8_8 (int x, int c) private
Definition at line 495 of file jpge.cpp.
 {
     uint8* pSrc1;
     sample_array_t* pDst = m_sample_array;
     x = (x * (16 * 3)) + c;
     for(int i = 0; i < 8; i++, pDst += 8)
     {
         pSrc1 = m_mcu_lines[i + 0] + x;
         pDst[0] = ((pSrc1[0 * 3] + pSrc1[1 * 3]) >> 1) - 128;
         pDst[1] = ((pSrc1[2 * 3] + pSrc1[3 * 3]) >> 1) - 128;
         pDst[2] = ((pSrc1[4 * 3] + pSrc1[5 * 3]) >> 1) - 128;
         pDst[3] = ((pSrc1[6 * 3] + pSrc1[7 * 3]) >> 1) - 128;
         pDst[4] = ((pSrc1[8 * 3] + pSrc1[9 * 3]) >> 1) - 128;
         pDst[5] = ((pSrc1[10 * 3] + pSrc1[11 * 3]) >> 1) - 128;
         pDst[6] = ((pSrc1[12 * 3] + pSrc1[13 * 3]) >> 1) - 128;
         pDst[7] = ((pSrc1[14 * 3] + pSrc1[15 * 3]) >> 1) - 128;
     }
 }
References m_mcu_lines, and m_sample_array.
Referenced by process_mcu_row().
load_block_8_8()
void jpge::jpeg_encoder::load_block_8_8 (int x, int y, int c) private
Definition at line 451 of file jpge.cpp.
 {
     uint8* pSrc;
     sample_array_t* pDst = m_sample_array;
     x = (x * (8 * 3)) + c;
     y <<= 3;
     for(int i = 0; i < 8; i++, pDst += 8)
     {
         pSrc = m_mcu_lines[y + i] + x;
         pDst[0] = pSrc[0 * 3] - 128;
         pDst[1] = pSrc[1 * 3] - 128;
         pDst[2] = pSrc[2 * 3] - 128;
         pDst[3] = pSrc[3 * 3] - 128;
         pDst[4] = pSrc[4 * 3] - 128;
         pDst[5] = pSrc[5 * 3] - 128;
         pDst[6] = pSrc[6 * 3] - 128;
         pDst[7] = pSrc[7 * 3] - 128;
     }
 }
References m_mcu_lines, and m_sample_array.
Referenced by process_mcu_row().
load_block_8_8_grey()
void jpge::jpeg_encoder::load_block_8_8_grey (int x) private
Definition at line 432 of file jpge.cpp.
 {
     uint8* pSrc;
     sample_array_t* pDst = m_sample_array;
     x <<= 3;
     for(int i = 0; i < 8; i++, pDst += 8)
     {
         pSrc = m_mcu_lines[i] + x;
         pDst[0] = pSrc[0] - 128;
         pDst[1] = pSrc[1] - 128;
         pDst[2] = pSrc[2] - 128;
         pDst[3] = pSrc[3] - 128;
         pDst[4] = pSrc[4] - 128;
         pDst[5] = pSrc[5] - 128;
         pDst[6] = pSrc[6] - 128;
         pDst[7] = pSrc[7] - 128;
     }
 }
References m_mcu_lines, and m_sample_array.
Referenced by process_mcu_row().
load_mcu()
void jpge::jpeg_encoder::load_mcu (const void * src) private
Definition at line 673 of file jpge.cpp.
 {
     const uint8* Psrc = reinterpret_cast<const uint8*>(pSrc);
     uint8* pDst = m_mcu_lines[m_mcu_y_ofs]; // OK to write up to m_image_bpl_xlt bytes to pDst
     if(m_num_components == 1)
     {
         if(m_image_bpp == 3)
             RGB_to_Y(pDst, Psrc, m_image_x);
         else
             memcpy(pDst, Psrc, m_image_x);
     }
     else
     {
         if(m_image_bpp == 3)
             RGB_to_YCC(pDst, Psrc, m_image_x);
         else
             Y_to_YCC(pDst, Psrc, m_image_x);
     }
     // Possibly duplicate pixels at end of scanline if not a multiple of 8 or 16
     if(m_num_components == 1)
         memset(m_mcu_lines[m_mcu_y_ofs] + m_image_bpl_xlt, pDst[m_image_bpl_xlt - 1],
                m_image_x_mcu - m_image_x);
     else
     {
         const uint8 y = pDst[m_image_bpl_xlt - 3 + 0], cb = pDst[m_image_bpl_xlt - 3 + 1],
                     cr = pDst[m_image_bpl_xlt - 3 + 2];
         uint8* q = m_mcu_lines[m_mcu_y_ofs] + m_image_bpl_xlt;
         for(int i = m_image_x; i < m_image_x_mcu; i++)
         {
             *q++ = y;
             *q++ = cb;
             *q++ = cr;
         }
     }
     if(++m_mcu_y_ofs == m_mcu_y)
     {
         process_mcu_row();
         m_mcu_y_ofs = 0;
     }
 }
References m_image_bpl_xlt, m_image_bpp, m_image_x, m_image_x_mcu, m_mcu_lines, m_mcu_y, m_mcu_y_ofs, m_num_components, process_mcu_row(), jpge::RGB_to_Y(), jpge::RGB_to_YCC(), and jpge::Y_to_YCC().
Referenced by process_scanline().
load_quantized_coefficients()
void jpge::jpeg_encoder::load_quantized_coefficients (int component_num) private
Definition at line 514 of file jpge.cpp.
 {
     int32* q = m_quantization_tables[component_num > 0];
     int16* pDst = m_coefficient_array;
     for(int i = 0; i < 64; i++)
     {
         sample_array_t j = m_sample_array[s_zag[i]];
         if(j < 0)
         {
             if((j = -j + (*q >> 1)) < *q)
                 *pDst++ = 0;
             else
                 *pDst++ = static_cast<int16>(-(j / *q));
         }
         else
         {
             if((j = j + (*q >> 1)) < *q)
                 *pDst++ = 0;
             else
                 *pDst++ = static_cast<int16>((j / *q));
         }
         q++;
     }
 }
References m_coefficient_array, jpge::m_quantization_tables, m_sample_array, and jpge::s_zag.
Referenced by code_block().
operator=()
jpeg_encoder& jpge::jpeg_encoder::operator= (const jpeg_encoder &) private
process_end_of_image()
bool jpge::jpeg_encoder::process_end_of_image () private
Definition at line 848 of file jpge.cpp.
 {
     if(m_mcu_y_ofs)
     {
         if(m_mcu_y_ofs < 16)
         { // check here just to shut up static analysis
             for(int i = m_mcu_y_ofs; i < m_mcu_y; i++)
             {
                 memcpy(m_mcu_lines[i], m_mcu_lines[m_mcu_y_ofs - 1], m_image_bpl_mcu);
             }
         }
         process_mcu_row();
     }
     put_bits(0x7F, 7);
     emit_marker(M_EOI);
     flush_output_buffer();
     m_all_stream_writes_succeeded = m_all_stream_writes_succeeded && m_pStream->put_buf(NULL, 0);
     m_pass_num++; // purposely bump up m_pass_num, for debugging
     return true;
 }
References emit_marker(), flush_output_buffer(), m_all_stream_writes_succeeded, jpge::M_EOI, m_image_bpl_mcu, m_mcu_lines, m_mcu_y, m_mcu_y_ofs, m_pass_num, m_pStream, process_mcu_row(), put_bits(), and jpge::output_stream::put_buf().
Referenced by process_scanline().
process_mcu_row()
void jpge::jpeg_encoder::process_mcu_row () private
Definition at line 617 of file jpge.cpp.
 {
     if(m_num_components == 1)
     {
         for(int i = 0; i < m_mcus_per_row; i++)
         {
             load_block_8_8_grey(i);
             code_block(0);
         }
     }
     else if((m_comp_h_samp[0] == 1) && (m_comp_v_samp[0] == 1))
     {
         for(int i = 0; i < m_mcus_per_row; i++)
         {
             load_block_8_8(i, 0, 0);
             code_block(0);
             load_block_8_8(i, 0, 1);
             code_block(1);
             load_block_8_8(i, 0, 2);
             code_block(2);
         }
     }
     else if((m_comp_h_samp[0] == 2) && (m_comp_v_samp[0] == 1))
     {
         for(int i = 0; i < m_mcus_per_row; i++)
         {
             load_block_8_8(i * 2 + 0, 0, 0);
             code_block(0);
             load_block_8_8(i * 2 + 1, 0, 0);
             code_block(0);
             load_block_16_8_8(i, 1);
             code_block(1);
             load_block_16_8_8(i, 2);
             code_block(2);
         }
     }
     else if((m_comp_h_samp[0] == 2) && (m_comp_v_samp[0] == 2))
     {
         for(int i = 0; i < m_mcus_per_row; i++)
         {
             load_block_8_8(i * 2 + 0, 0, 0);
             code_block(0);
             load_block_8_8(i * 2 + 1, 0, 0);
             code_block(0);
             load_block_8_8(i * 2 + 0, 1, 0);
             code_block(0);
             load_block_8_8(i * 2 + 1, 1, 0);
             code_block(0);
             load_block_16_8(i, 1);
             code_block(1);
             load_block_16_8(i, 2);
             code_block(2);
         }
     }
 }
References code_block(), load_block_16_8(), load_block_16_8_8(), load_block_8_8(), load_block_8_8_grey(), m_comp_h_samp, m_comp_v_samp, m_mcus_per_row, and m_num_components.
Referenced by load_mcu(), and process_end_of_image().
process_scanline()
bool jpge::jpeg_encoder::process_scanline (const void * pScanline)
Definition at line 906 of file jpge.cpp.
 {
     if((m_pass_num < 1) || (m_pass_num > 2))
     {
         return false;
     }
     if(m_all_stream_writes_succeeded)
     {
         if(!pScanline)
         {
             if(!process_end_of_image())
             {
                 return false;
             }
         }
         else
         {
             load_mcu(pScanline);
         }
     }
     return m_all_stream_writes_succeeded;
 }
References load_mcu(), m_all_stream_writes_succeeded, m_pass_num, and process_end_of_image().
put_bits()
void jpge::jpeg_encoder::put_bits (uint bits, uint len) private
Definition at line 303 of file jpge.cpp.
 {
     uint8 c = 0;
     m_bit_buffer |= ((uint32)bits << (24 - (m_bits_in += len)));
     while(m_bits_in >= 8)
     {
         c = (uint8)((m_bit_buffer >> 16) & 0xFF);
         emit_byte(c);
         if(c == 0xFF)
         {
             emit_byte(0);
         }
         m_bit_buffer <<= 8;
         m_bits_in -= 8;
     }
 }
References emit_byte(), m_bit_buffer, and m_bits_in.
Referenced by code_coefficients_pass_two(), and process_end_of_image().
Member Data Documentation
m_all_stream_writes_succeeded
bool jpge::jpeg_encoder::m_all_stream_writes_succeeded private
Definition at line 123 of file jpge.h.
Referenced by clear(), flush_output_buffer(), jpg_open(), process_end_of_image(), and process_scanline().
m_bit_buffer
uint32 jpge::jpeg_encoder::m_bit_buffer private
Definition at line 120 of file jpge.h.
Referenced by jpg_open(), and put_bits().
m_bits_in
uint jpge::jpeg_encoder::m_bits_in private
Definition at line 121 of file jpge.h.
Referenced by jpg_open(), and put_bits().
m_coefficient_array
int16 jpge::jpeg_encoder::m_coefficient_array[64] private
Definition at line 114 of file jpge.h.
Referenced by code_coefficients_pass_two(), and load_quantized_coefficients().
m_comp_h_samp
uint8 jpge::jpeg_encoder::m_comp_h_samp[3] private
Definition at line 105 of file jpge.h.
Referenced by emit_sof(), jpg_open(), and process_mcu_row().
m_comp_v_samp
uint8 jpge::jpeg_encoder::m_comp_v_samp[3] private
Definition at line 105 of file jpge.h.
Referenced by emit_sof(), jpg_open(), and process_mcu_row().
m_image_bpl
int jpge::jpeg_encoder::m_image_bpl private
Definition at line 106 of file jpge.h.
Referenced by jpg_open().
m_image_bpl_mcu
int jpge::jpeg_encoder::m_image_bpl_mcu private
Definition at line 108 of file jpge.h.
Referenced by jpg_open(), and process_end_of_image().
m_image_bpl_xlt
int jpge::jpeg_encoder::m_image_bpl_xlt private
Definition at line 108 of file jpge.h.
Referenced by jpg_open(), and load_mcu().
m_image_bpp
int jpge::jpeg_encoder::m_image_bpp private
Definition at line 106 of file jpge.h.
Referenced by jpg_open(), and load_mcu().
m_image_x
int jpge::jpeg_encoder::m_image_x private
Definition at line 106 of file jpge.h.
Referenced by emit_sof(), jpg_open(), and load_mcu().
m_image_x_mcu
int jpge::jpeg_encoder::m_image_x_mcu private
Definition at line 107 of file jpge.h.
Referenced by jpg_open(), and load_mcu().
m_image_y
int jpge::jpeg_encoder::m_image_y private
Definition at line 106 of file jpge.h.
Referenced by emit_sof(), and jpg_open().
m_image_y_mcu
int jpge::jpeg_encoder::m_image_y_mcu private
Definition at line 107 of file jpge.h.
Referenced by jpg_open().
m_last_dc_val
int jpge::jpeg_encoder::m_last_dc_val[3] private
Definition at line 116 of file jpge.h.
Referenced by code_coefficients_pass_two(), and jpg_open().
m_mcu_lines
uint8* jpge::jpeg_encoder::m_mcu_lines[16] private
Definition at line 111 of file jpge.h.
Referenced by clear(), deinit(), jpg_open(), load_block_16_8(), load_block_16_8_8(), load_block_8_8(), load_block_8_8_grey(), load_mcu(), and process_end_of_image().
m_mcu_x
int jpge::jpeg_encoder::m_mcu_x private
Definition at line 110 of file jpge.h.
Referenced by jpg_open().
m_mcu_y
int jpge::jpeg_encoder::m_mcu_y private
Definition at line 110 of file jpge.h.
Referenced by jpg_open(), load_mcu(), and process_end_of_image().
m_mcu_y_ofs
uint8 jpge::jpeg_encoder::m_mcu_y_ofs private
Definition at line 112 of file jpge.h.
Referenced by jpg_open(), load_mcu(), and process_end_of_image().
m_mcus_per_row
int jpge::jpeg_encoder::m_mcus_per_row private
Definition at line 109 of file jpge.h.
Referenced by jpg_open(), and process_mcu_row().
m_num_components
uint8 jpge::jpeg_encoder::m_num_components private
Definition at line 104 of file jpge.h.
Referenced by emit_dhts(), emit_dqt(), emit_sof(), emit_sos(), jpg_open(), load_mcu(), and process_mcu_row().
m_out_buf
uint8 jpge::jpeg_encoder::m_out_buf[JPGE_OUT_BUF_SIZE] private
Definition at line 117 of file jpge.h.
Referenced by flush_output_buffer(), and jpg_open().
m_out_buf_left
uint jpge::jpeg_encoder::m_out_buf_left private
Definition at line 119 of file jpge.h.
Referenced by emit_byte(), flush_output_buffer(), and jpg_open().
m_params
params jpge::jpeg_encoder::m_params private
Definition at line 103 of file jpge.h.
Referenced by compute_quant_table(), init(), and jpg_open().
m_pass_num
uint8 jpge::jpeg_encoder::m_pass_num private
Definition at line 122 of file jpge.h.
Referenced by clear(), jpg_open(), process_end_of_image(), and process_scanline().
m_pOut_buf
uint8* jpge::jpeg_encoder::m_pOut_buf private
Definition at line 118 of file jpge.h.
Referenced by emit_byte(), flush_output_buffer(), and jpg_open().
m_pStream
output_stream* jpge::jpeg_encoder::m_pStream private
Definition at line 102 of file jpge.h.
Referenced by flush_output_buffer(), init(), and process_end_of_image().
m_sample_array
sample_array_t jpge::jpeg_encoder::m_sample_array[64] private
Definition at line 113 of file jpge.h.
Referenced by code_block(), load_block_16_8(), load_block_16_8_8(), load_block_8_8(), load_block_8_8_grey(), and load_quantized_coefficients().
The documentation for this class was generated from the following files:
Components/ThirdpartAPI/image_conversions/include/jpge.h
Components/ThirdpartAPI/image_conversions/src/jpge.cpp