Embedded Library: FreeRTOS::Semaphore Class Reference
FreeRTOS::Semaphore Class Reference
#include <FreeRTOS.h>
Public Member Functions
Semaphore (const std::string &owner="<Unknown>")
~Semaphore ()
void give ()
Give a semaphore. The Semaphore is given.
void give (uint32_t value)
Give a semaphore. The Semaphore is given with an associated value.
void giveFromISR ()
Give a semaphore from an ISR.
void setName (const std::string &name)
Set the name of the semaphore.
bool take (const std::string &owner="<Unknown>")
Take a semaphore. Take a semaphore and wait indefinitely.
bool take (uint32_t timeoutMs, const std::string &owner="<Unknown>")
Take a semaphore. Take a semaphore but return if we haven't obtained it in the given period of milliseconds.
std::string toString ()
Create a string representation of the semaphore.
uint32_t wait (const std::string &owner="<Unknown>")
Wait for a semaphore to be released by trying to take it and then releasing it again.
Private Attributes
int m_semaphore = 0
int m_pthread_mutex = 0
std::string m_name
std::string m_owner
uint32_t m_value
bool m_usePthreads
Detailed Description
Definition at line 48 of file FreeRTOS.h.
Constructor & Destructor Documentation
Semaphore()
FreeRTOS::Semaphore::Semaphore (const std::string & owner = "<Unknown>")
Definition at line 124 of file FreeRTOS.cpp.
     : m_name{name}, m_owner{"<N/A>"}, m_value{0}, m_usePthreads{false}
 {
 #ifdef __ESP32__
     if(m_usePthreads)
     {
         pthread_mutex_init(&m_pthread_mutex, nullptr);
     }
     else
     {
         //  m_semaphore = xSemaphoreCreateMutex();
         /*
          * apperently a bug has been happening in the FreeRTOS due to Mutex, so maybe binary
          * semaphore is acceptable, -> usually semaphore is used as a single lock, so why not?
          * 190813-bug, can binary work? :: https://github.com/espressif/arduino-esp32/issues/2723
          */
         m_semaphore = xSemaphoreCreateBinary();
         // it looks like, whenever a semaphore is created
         // we have to release it ?? @gliese
         give();
     }
 #endif
 }
~Semaphore()
FreeRTOS::Semaphore::~Semaphore ()
Definition at line 148 of file FreeRTOS.cpp.
 {
 #ifdef __ESP32__
     if(m_usePthreads)
     {
         pthread_mutex_destroy(&m_pthread_mutex);
     }
     else
     {
         vSemaphoreDelete(m_semaphore);
     }
 #endif
 }
References m_semaphore.
Member Function Documentation
give() [1/2]
void FreeRTOS::Semaphore::give ()
Give a semaphore. The Semaphore is given.
Definition at line 166 of file FreeRTOS.cpp.
 {
 #ifdef __ESP32__
     ESP_LOGV(LOG_TAG, "Semaphore giving: %s", toString().c_str());
     if(m_usePthreads)
     {
         pthread_mutex_unlock(&m_pthread_mutex);
     }
     else
     {
         xSemaphoreGive(m_semaphore);
     }
 #endif
     m_owner = std::string("<N/A>");
 } // Semaphore::give
References LOG_TAG, and m_semaphore.
Referenced by esp32_http_sal::get(), and mqtt_api_v2::publish().
give() [2/2]
void FreeRTOS::Semaphore::give (uint32_t value)
Give a semaphore. The Semaphore is given with an associated value.
Parameters
[in] value The value to associate with the semaphore.
Definition at line 188 of file FreeRTOS.cpp.
 {
     m_value = value;
     give();
 } // give
giveFromISR()
void FreeRTOS::Semaphore::giveFromISR ()
Give a semaphore from an ISR.
Definition at line 197 of file FreeRTOS.cpp.
 {
 #ifdef __ESP32__
     BaseType_t higherPriorityTaskWoken;
     if(m_usePthreads)
     {
         assert(false); // @suppress("Function cannot be resolved") // @suppress("Invalid arguments")
     }
     else
     {
         xSemaphoreGiveFromISR(m_semaphore, &higherPriorityTaskWoken);
     }
 #endif
 } // giveFromISR
References BaseType_t, and m_semaphore.
setName()
void FreeRTOS::Semaphore::setName (const std::string & name)
Set the name of the semaphore.
Parameters
[in] name The name of the semaphore.
Definition at line 304 of file FreeRTOS.cpp.
 {
     m_name = name;
 } // setName
take() [1/2]
bool FreeRTOS::Semaphore::take (const std::string & owner = "<Unknown>")
Take a semaphore. Take a semaphore and wait indefinitely.
Parameters
[in] owner The new owner (for debugging)
Returns
True if we took the semaphore.
Definition at line 218 of file FreeRTOS.cpp.
 {
 #ifdef __ESP32__
     ESP_LOGV(LOG_TAG, "Semaphore taking: %s for %s", toString().c_str(), owner.c_str());
     bool rc = false;
     if(m_usePthreads)
     {
         pthread_mutex_lock(&m_pthread_mutex);
     }
     else
     {
         rc = ::xSemaphoreTake(m_semaphore, portMAX_DELAY);
     }
     m_owner = owner;
     if(rc)
     {
         ESP_LOGV(LOG_TAG, "Semaphore taken:  %s", toString().c_str());
     }
     else
     {
         ESP_LOGE(LOG_TAG, "Semaphore NOT taken:  %s", toString().c_str());
     }
     return rc;
 #else
     return true;
 #endif
 } // Semaphore::take
References LOG_TAG, and m_semaphore.
Referenced by esp32_http_sal::get(), mqtt_api_v2::getData(), mqtt_api_v2::publish(), and mqtt_api_v2::subscribe().
take() [2/2]
bool FreeRTOS::Semaphore::take (uint32_t timeoutMs, const std::string & owner = "<Unknown>")
Take a semaphore. Take a semaphore but return if we haven't obtained it in the given period of milliseconds.
Parameters
[in] timeoutMs Timeout in milliseconds.
[in] owner The new owner (for debugging)
Returns
True if we took the semaphore.
Definition at line 253 of file FreeRTOS.cpp.
 {
 #ifdef __ESP32__
     ESP_LOGV(LOG_TAG, "Semaphore taking: %s for %s", toString().c_str(), owner.c_str());
     bool rc = false;
     if(m_usePthreads)
     {
         ESP_LOGW(LOG_TAG, "We apparently don't have a timed wait for pthreads.  %s",
                  toString().c_str());
         //  assert(false);  // We apparently don't have a timed wait for pthreads. //
         //@suppress("Function cannot be resolved")
     }
     else
     {
         rc = ::xSemaphoreTake(m_semaphore, timeoutMs / portTICK_PERIOD_MS);
     }
     m_owner = owner;
     if(rc)
     {
         ESP_LOGV(LOG_TAG, "Semaphore taken:  %s", toString().c_str());
     }
     else
     {
         ESP_LOGE(LOG_TAG, "Semaphore NOT taken:  %s", toString().c_str());
     }
     return rc;
 #else
     return true;
 #endif
 } // Semaphore::take
References LOG_TAG, and m_semaphore.
toString()
std::string FreeRTOS::Semaphore::toString ()
Create a string representation of the semaphore.
Returns
A string representation of the semaphore.
Definition at line 288 of file FreeRTOS.cpp.
 {
 #ifdef __ESP32__
     std::stringstream stringStream;
     stringStream << "name: " << m_name << " (0x" << std::hex << std::setfill('0')
                  << (uint32_t)m_semaphore << "), owner: " << m_owner;
     return stringStream.str();
 #else
     return "";
 #endif
 } // toString
References m_semaphore.
Referenced by wait().
wait()
uint32_t FreeRTOS::Semaphore::wait (const std::string & owner = "<Unknown>")
Wait for a semaphore to be released by trying to take it and then releasing it again.
Parameters
[in] owner A debug tag.
Returns
The value associated with the semaphore.
Definition at line 92 of file FreeRTOS.cpp.
 {
 #ifdef __ESP32__
     ESP_LOGV(LOG_TAG, ">> wait: Semaphore waiting: %s for %s", toString().c_str(), owner.c_str());
     if(m_usePthreads)
     {
         pthread_mutex_lock(&m_pthread_mutex);
     }
     else
     {
         xSemaphoreTake(m_semaphore, portMAX_DELAY);
         //  xSemaphoreTake(m_semaphore,  3000/portTICK_PERIOD_MS);
     }
     m_owner = owner;
     if(m_usePthreads)
     {
         pthread_mutex_unlock(&m_pthread_mutex);
     }
     else
     {
         xSemaphoreGive(m_semaphore);
     }
     ESP_LOGV(LOG_TAG, "<< wait: Semaphore released: %s", toString().c_str());
     m_owner = std::string("<N/A>");
 #endif
     return m_value;
 } // wait
References LOG_TAG, m_owner, m_pthread_mutex, m_semaphore, m_usePthreads, m_value, and toString().
Member Data Documentation
m_name
std::string FreeRTOS::Semaphore::m_name private
Definition at line 70 of file FreeRTOS.h.
m_owner
std::string FreeRTOS::Semaphore::m_owner private
Definition at line 71 of file FreeRTOS.h.
Referenced by wait().
m_pthread_mutex
int FreeRTOS::Semaphore::m_pthread_mutex = 0 private
Definition at line 68 of file FreeRTOS.h.
Referenced by wait().
m_semaphore
int FreeRTOS::Semaphore::m_semaphore = 0 private
Definition at line 67 of file FreeRTOS.h.
Referenced by wait().
m_usePthreads
bool FreeRTOS::Semaphore::m_usePthreads private
Definition at line 73 of file FreeRTOS.h.
Referenced by wait().
m_value
uint32_t FreeRTOS::Semaphore::m_value private
Definition at line 72 of file FreeRTOS.h.
Referenced by wait().
The documentation for this class was generated from the following files:
Components/RTOS/FreeRTOS/include/FreeRTOS.h
Components/RTOS/FreeRTOS/src/FreeRTOS.cpp