Embedded Library: QueryAddSensorData Class Reference
QueryAddSensorData Class Reference final
#include <QueryAddSensorData.hpp>
Public Member Functions
QueryAddSensorData ()=default
~QueryAddSensorData ()
std::string start (void) override
std::string content (const QueryDataMessage &msg) override
Public Member Functions inherited from QueryBase< QueryDataMessage >
virtual std::string append (void)
virtual std::string end (void)
Detailed Description
Definition at line 55 of file QueryAddSensorData.hpp.
Constructor & Destructor Documentation
QueryAddSensorData()
QueryAddSensorData::QueryAddSensorData () default
~QueryAddSensorData()
QueryAddSensorData::~QueryAddSensorData () inline
Definition at line 62 of file QueryAddSensorData.hpp.
 {};
Member Function Documentation
content()
std::string QueryAddSensorData::content (const QueryDataMessage & msg) override virtual
Implements QueryBase< QueryDataMessage >.
Definition at line 36 of file QueryAddSensorData.cpp.
 {
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, ">> QueryAddSensorData::append >> ");
 #endif
     // Executable code:
     std::string str;
     // Executable code:
     if(msg.isEmpty())
     {
         std::cout << "NOT VALID DATA \n";
         return "";
     }
     timeval tval;
     tval.tv_sec = msg.getBuffer().at(0).time_stamp / 1000;
     tval.tv_usec = (msg.getBuffer().at(0).time_stamp % 1000) * 1000;
     // get the millisec part
     tm* time_now = gmtime(&tval.tv_sec);
     char buffer[80];
     strftime(buffer, 80, "'%Y-%m-%dT%H:%M:%S", time_now);
     char currentTime[84] = "";
     sprintf(currentTime, "%s.%ldZ'", buffer, (tval.tv_usec));
     str.append("(");
     // timestamp
     str.append(currentTime);
     str.append(",");
     // Sensor id
     str.append(std::to_string(msg.getId()));
     str.append(",");
     // data, with 4 precision
     auto data = msg.getBuffer().at(0).data;
     str.append(std::to_string(data));
     str.append(")");
 #ifdef DEBUG
     LOG_PRINT_INFO(LOG_TAG, "<< QueryAddSensorData::append << ");
 #endif
     return str;
 }
References QueryMessageBase< T >::getBuffer(), QueryMessageBase< T >::getId(), QueryMessageBase< T >::isEmpty(), LOG_PRINT_INFO, and LOG_TAG.
start()
std::string QueryAddSensorData::start (void) inline override virtual
Implements QueryBase< QueryDataMessage >.
Definition at line 63 of file QueryAddSensorData.hpp.
     {
         return "INSERT INTO public.datapoints (tstz,entity_id,value) VALUES ";
     };
The documentation for this class was generated from the following files:
Components/Objects/QueryTools/include/QueryAddSensorData.hpp
Components/Objects/QueryTools/src/QueryAddSensorData.cpp