Embedded Library: FreeRTOS::Queue Class Reference
FreeRTOS::Queue Class Reference
#include <FreeRTOS.h>
Public Member Functions
Queue (size_t amount_of_items, size_t size_of_item)
Construct a new Queue object.
~Queue ()
virtual int send (const void *const item_to_send, size_t delay)
Send data to the queue.
int recieve (void *pvBuffer, size_t delay)
Recieve data from the queue.
Private Attributes
int m_handle = 0
Detailed Description
Definition at line 76 of file FreeRTOS.h.
Constructor & Destructor Documentation
Queue()
FreeRTOS::Queue::Queue (size_t amount_of_items, size_t size_of_item) explicit
Construct a new Queue object.
Initialize the queue.
Parameters
amount_of_items
size_of_item : use sizeof(ITEM_OF_INTEREST)
[in] amount of items
[in] size of one item
Definition at line 315 of file FreeRTOS.cpp.
 {
 #ifdef __ESP32__
     m_handle = xQueueCreate(amount_of_items, size_of_item);
 #endif
 }
~Queue()
FreeRTOS::Queue::~Queue ()
Definition at line 322 of file FreeRTOS.cpp.
 {}
Member Function Documentation
recieve()
int FreeRTOS::Queue::recieve (void * pvBuffer, size_t delay)
Recieve data from the queue.
Parameters
[out] buffer with recieved item
[in] delay willing to wait
Definition at line 343 of file FreeRTOS.cpp.
 {
     if(m_handle == 0)
     { // error
         return 1;
     }
 #ifdef __ESP32__
     BaseType_t xStatus = xQueueReceive(m_handle, pvBuffer, delay);
     if(xStatus != pdPASS)
     {
         std::cout << " NOT ABLE TO RECIEVE FROM QUEUE!!"
                   << "\n";
         return 1;
     }
 #endif
     // ok
     return 0;
 }
References BaseType_t, and basic_utils::delay().
Referenced by ActiveCurrentSensor::run().
send()
int FreeRTOS::Queue::send (const void *const item_to_send, size_t delay) virtual
Send data to the queue.
Parameters
[in] item willing to send
[in] delay willing to wait
Definition at line 324 of file FreeRTOS.cpp.
 {
     if(m_handle == 0)
     { // error
         return 1;
     }
 #ifdef __ESP32__
     BaseType_t xStatus = xQueueSend(m_handle, item_to_send, delay);
     if(xStatus != pdPASS)
     {
         std::cout << " NOT ABLE TO SEND TO QUEUE!!"
                   << "\n";
         return 1;
     }
 #endif
     // ok
     return 0;
 }
References BaseType_t, and basic_utils::delay().
Referenced by ActiveCurrentSensor::activateQueue().
Member Data Documentation
m_handle
int FreeRTOS::Queue::m_handle = 0 private
Definition at line 105 of file FreeRTOS.h.
The documentation for this class was generated from the following files:
Components/RTOS/FreeRTOS/include/FreeRTOS.h
Components/RTOS/FreeRTOS/src/FreeRTOS.cpp